### ISSUE TITLE
Allow viewing adjacent pages while working on a page

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1000]
**User story/persona**
As a user, I want to be able to see the previous and next pages for the page I am working on in the activity UI. When I click the previous or next page, I don't want to lose my work if it is unsaved. I might only be checking those images for reference. However, I do want the page/asset-level metadata to be updated and the transcription plain text to be available (i.e. if I can't decipher a word on one page, maybe someone else has already figured it out on another page). Also, I don't want to lose my starting place, I might want to go back there.

**Additional context**
We need to implement a custom control for this and not use the open seadragon reference strip to navigate prev/next.

**Comment by acdha** [comment]
I retitled this to make it more distinct from another thing which we might want to add: buttons and/or keyboard shortcuts to jump to the next/previous asset which you can work on.
