### ISSUE TITLE
Grouping of thumbnails in activity UI grid view

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1001]
**User story/persona**
As a user, I want to scroll through thumbnails in the grid view and know which thumbnails might be related to one another as part of the same item, project, or campaign. I'd like to see category separators or some other type of groupings of things in the grid that belong together.

**Comment by acdha** [comment]
When @jbresner and I were talking about this last, my first thought for an MVP was that we'd break it down to the next level below the current sort/filtering options: i.e. if you were sorting by Year, we'd split on every year boundary, sort by Campaign (well, I guess not any more 😁) would segment by campaign unless you had an active campaign filter and then it would use the project, etc. I think that could potentially offer some neat ways to surface the metadata at those levels as well but it'd definitely involve some custom code for the various settings.
