### ISSUE TITLE
Add a retry for API failures

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#1032]
We should update the promise chain in `fetchJSON` to more gracefully handle failures: I'm wondering whether that is adding a few time-delayed retries to everything using [`fetchJSON`](https://github.com/LibraryOfCongress/concordia/blob/f19666e02ac7a1d341df0678eb7c7e6cf8c0b667/concordia/static/js/action-app/utils/api.js#L11 ) or specifically in calls such as [`fetchAssetPage()`](https://github.com/LibraryOfCongress/concordia/blob/f19666e02ac7a1d341df0678eb7c7e6cf8c0b667/concordia/static/js/action-app/index.js#L520) but we can make the experience smoother.

This has apparently happened on a dozen times or so: https://errorlogging.loc.gov/share/issue/836067cff35041759988db0700417796/

**Comment by rstorey** [comment]
This is good-enough done for now. I will test it along with the other changes made in Sprint 26.
