### ISSUE TITLE
Topics: more unit tests and refactor the transcription status filtering view & test logic out

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1037]
We should have some tests covering the non-API views as well, which might be a good time to refactor the transcription status filtering view & test logic out since it's being used in multiple places.

_Originally posted by @acdha in https://github.com/LibraryOfCongress/concordia/pull/894#issuecomment-497081335_

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-56](https://staff.loc.gov/tasks/browse/CONCD-56)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
