### ISSUE TITLE
Restore Related Links uniqueness constraint

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1038]
Should we make those relationships nullable so we can still have the uniqueness constraints on non-null values?

_Originally posted by @acdha in https://github.com/LibraryOfCongress/concordia/pull/894_

**Comment by rabiloc** [comment]
The uniqueness constraint was about making sure we didn’t have duplicate links in the list
I think it’s probably fine to leave that up to the community managers
To make sure they populate the correct links
