### ISSUE TITLE
Share UI is offscreen in certain cases

### ISSUE THREAD

**Issue by jbresner** [LibraryOfCongress/concordia#1048]
On the activity view screen, when the asset list is toggled closed, if a user clicks on the share button, the dropdown of share options is partially off screen (see attached screenshot).

Instead of left-aligning the dropdown with the button, please right-align it to make sure it's fully displayed (see attached comp).

![Screen Shot 2019-06-04 at 12 20 49 PM](https://user-images.githubusercontent.com/4275957/58896429-fe9da600-86c3-11e9-861c-0eccb48d2182.png)

![Asset View - Share](https://user-images.githubusercontent.com/4275957/58896468-0bba9500-86c4-11e9-9e6b-cb53c092f4e5.png)

**Comment by rstorey** [comment]
This is in master and will be released shortly
