### ISSUE TITLE
Revise the "More Info" button to better reflect the button's behavior

### ISSUE THREAD

**Issue by jbresner** [LibraryOfCongress/concordia#1049]
The "More info" button on the activity screen currently has a button for "More info" that also has an "angle-down arrow". This original design was when clicking on the button would have opened text within the same screen. Since the button now opens a modal window, the angle-down arrow doesn't make sense so for now, please remove it (see screen shot).

![Screen Shot 2019-06-04 at 12 30 10 PM](https://user-images.githubusercontent.com/4275957/58896858-e5492980-86c4-11e9-9298-163a43651b17.png)

**Comment by rstorey** [comment]
This is in master and will be released shortly
