### ISSUE TITLE
System announcement message in site-wide banner

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1059]
**User story/persona**
As a community manager, I want to publish a system announcement in a site-wide banner so that I can make users aware of new features, problems or outages.

Stems from #901

**Comment by acdha** [comment]
If the intention is to be able to use this in the event of outages we should probably have it hosted in S3 with a bit of JavaScript which loads that and injects it on the pages which we care about. wdl.org has used this code:

```javascript
jQuery(function($) {
    'use strict';

    var now = new Date(),
        cacheKey = (1900 + now.getYear()) + '-' + (now.getMonth() + 1) + '-' + now.getDate(),
        baseUrl = 'https://static.wdl.org/site-messages/' + document.location.hostname;

    $.ajax({
        url: baseUrl + '/homepage.' + LANGUAGE_CODE + '.html?' + cacheKey,
        dataType: 'html',
        cache: true
    }).success(function(data) {
        if (!!data && data.length > 0) {
            $(data).prependTo(document.body);
        }
    });
});
```

As part of that, we should also confirm that we have the `Cache-Control` `serve-stale-if-error` semantics enabled for at least the homepage and see about a custom error page on the CDN.

**Comment by acdha** [comment]
If the intention is to be able to use this in the event of outages we should probably have it hosted in S3 with a bit of JavaScript which loads that and injects it on the pages which we care about. wdl.org has used this code:

```javascript
jQuery(function($) {
    'use strict';

    var now = new Date(),
        cacheKey = (1900 + now.getYear()) + '-' + (now.getMonth() + 1) + '-' + now.getDate(),
        baseUrl = 'https://static.wdl.org/site-messages/' + document.location.hostname;

    $.ajax({
        url: baseUrl + '/homepage.' + LANGUAGE_CODE + '.html?' + cacheKey,
        dataType: 'html',
        cache: true
    }).success(function(data) {
        if (!!data && data.length > 0) {
            $(data).prependTo(document.body);
        }
    });
});
```

As part of that, we should also confirm that we have the `Cache-Control` `serve-stale-if-error` semantics enabled for at least the homepage and see about a custom error page on the CDN.

**Comment by acdha** [comment]
If the intention is to be able to use this in the event of outages we should probably have it hosted in S3 with a bit of JavaScript which loads that and injects it on the pages which we care about. wdl.org has used this code:

```javascript
jQuery(function($) {
    'use strict';

    var now = new Date(),
        cacheKey = (1900 + now.getYear()) + '-' + (now.getMonth() + 1) + '-' + now.getDate(),
        baseUrl = 'https://static.wdl.org/site-messages/' + document.location.hostname;

    $.ajax({
        url: baseUrl + '/homepage.' + LANGUAGE_CODE + '.html?' + cacheKey,
        dataType: 'html',
        cache: true
    }).success(function(data) {
        if (!!data && data.length > 0) {
            $(data).prependTo(document.body);
        }
    });
});
```

As part of that, we should also confirm that we have the `Cache-Control` `serve-stale-if-error` semantics enabled for at least the homepage and see about a custom error page on the CDN.

**Comment by acdha** [comment]
If the intention is to be able to use this in the event of outages we should probably have it hosted in S3 with a bit of JavaScript which loads that and injects it on the pages which we care about. wdl.org has used this code:

```javascript
jQuery(function($) {
    'use strict';

    var now = new Date(),
        cacheKey = (1900 + now.getYear()) + '-' + (now.getMonth() + 1) + '-' + now.getDate(),
        baseUrl = 'https://static.wdl.org/site-messages/' + document.location.hostname;

    $.ajax({
        url: baseUrl + '/homepage.' + LANGUAGE_CODE + '.html?' + cacheKey,
        dataType: 'html',
        cache: true
    }).success(function(data) {
        if (!!data && data.length > 0) {
            $(data).prependTo(document.body);
        }
    });
});
```

As part of that, we should also confirm that we have the `Cache-Control` `serve-stale-if-error` semantics enabled for at least the homepage and see about a custom error page on the CDN.
