### ISSUE TITLE
Restrict script and style tags in any places where admin can input HTML

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1061]
> The format changes seem reasonable but since this allows substantially more scope for mistakes which might not be obvious, I'm wondering whether we should enable CodeMirror for the admin change UI and enable the HTML linter (see https://codemirror.net/doc/manual.html#addon_lint) at the very least. There might be an argument for restricting the contents to, say, not allow `<script>` or `<style>`, too, to limit the damage if someone's account is compromised.

_Originally posted by @acdha in https://github.com/LibraryOfCongress/concordia/pull/1058#pullrequestreview-250576647

**Comment by acdha** [comment]
I made a simple addition of [bleach](https://bleach.readthedocs.io/en/latest/) to the admin for the SimpleContentBlock and {Campaign,Project} description fields. This is running in the default mode where it escapes any unexpected HTML values. We could have it strip them but given the context I'm also wondering whether we might simply want to do something like have it throw a form validation error and leave the input unmodified.
