### ISSUE TITLE
Fullscreen button makes the background color change

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1073]
**What behavior did you observe? Please describe the bug**
When I clicked the Fullscreen button, the background turned black and it made the other action buttons very difficult to see.

**How can we reproduce the bug?**

1. Go to any asset detail page in Chrome or Firefox.
2. Click on our Fullscreen button.
3. Press Escape key.
4. Use the Browser-native Fullscreen View.

**What is the expected behavior?**
When I clicked on the in-page Fullscreen button, the background color turned black.
When I used the browser fullscreen function, the background color remained the original color.

**Got screenshots? This helps us identify the issue**
![Screen Shot 2019-07-01 at 4 12 43 PM](https://user-images.githubusercontent.com/5270415/60463989-61c71d80-9c1b-11e9-8c70-8b04bc021dc8.png)
![Screen Shot 2019-07-01 at 4 12 29 PM](https://user-images.githubusercontent.com/5270415/60464001-64c20e00-9c1b-11e9-9857-76bd238c6c22.png)

**Desktop (please complete the following information):**

-   OS: Mac
-   Browser: Chrome, Firefox

**Comment by acdha** [comment]
This is a regression — https://github.com/LibraryOfCongress/concordia/blob/d2be83c40a7610556a5c14c622a2c08fad0e56ed/concordia/static/scss/base.scss#L51-L55 should probably be updated to add the element which the fullscreen API is called on.
