### ISSUE TITLE
Win 7 / LIB-managed Chrome Quick Tips overlap issue

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1078]
**What behavior did you observe? Please describe the bug**
In the classic interface on the asset detail page, the bar with the Quick Tips and Questions buttons overlaps the image viewer area.

**How can we reproduce the bug?**

1. On a Windows 7 system using Chrome (i.e. LIB desktop)
2. Click on the Let's Go button on the home page
3. Scroll down to where the Quick Tips button is located
4. Try to click on the part of the Quick Tips button that overlaps the image

**What is the expected behavior?**
Clicking the Quick Tips button should open the Quick Tips slider.
The "Need help" text should be legible.
The bar with the buttons should display the same in all versions of Chrome / Windows.

**Got screenshots? This helps us identify the issue**

![quick_tips](https://user-images.githubusercontent.com/5270415/60834915-cfc99280-a18f-11e9-81b7-32a08e572edb.png)

**Desktop (please complete the following information):**

-   OS: Windows 7 (LIB desktop, does not occur on Citrix)
-   Browser: Chrome (LIB managed)

**Comment by acdha** [comment]
This also reproduces on an unmanaged Chrome 75.0.3770.100, but not Firefox or Safari. I'm wondering whether it's a function of screen size/density.

**Comment by acdha** [comment]
The `height: 100%` on `#asset-image` isn't calculated the same in Chrome as the other browsers. Adding `overflow: hidden` appears to fix that but I'd want to test more whether or not that is the best approach.
