### ISSUE TITLE
Change title and description to be BTP focused

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1082]
When someone searches for By the People, it takes them to the about page. Updating the tag and adding a description to help SEO. 

* [ ] Change the prefix in the HTML `<title>` from `Crowd` to `By the People` 
* [ ] Add a meta description tag: 

    ```
    <meta name="description" content="Crowdsourcing project By the People invites anyone to become a Library of Congress virtual volunteer. Explore, transcribe, review, and tag digital collections to improve search and readability and open new avenues of research." />
    ```

**Comment by acdha** [comment]
Which pages should the meta description go on — I'm assuming the focus is on the homepage, since our campaign, project, item, and asset pages already use their respective metadata?

**Comment by elainekamlley** [comment]
Correct, homepage!
