### ISSUE TITLE
Lomax notebook items taking a few days to import

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#1083]
Description: 

Alan Lomax notebook items loading unevenly in test and stage. Some asset pages appear, some do not. In the three items I tested the first dozen or few dozen pages didn't load, but later pages did.

Currently visible examples (as of 7/29/19, 4pm):

- https://crowd-stage.loc.gov/campaigns/alan-lomax-collections/british-isles-and-northern-europe/afc2004004.ms040229/?page=1 

and 

-  https://crowd-stage.loc.gov/campaigns/alan-lomax-collections/british-isles-and-northern-europe/afc2004004.ms040229/?page=4

**How can we reproduce the bug?**

1. import a new Lomax item to either test or [stage Lomax campaign](https://crowd-stage.loc.gov/admin/concordia/project/40/change/?_changelist_filters=campaign__id__exact%3D12): i.e. https://www.loc.gov/item/afc2004004.ms070331/

Elaine and I have tested on a few different machines, operating systems, browsers, all to the same effect. 

This is the import log from stage: 

![Screen Shot 2019-07-29 at 3 53 05 PM](https://user-images.githubusercontent.com/6482891/62078392-93330900-b21a-11e9-87b3-c0075b42f4b0.png)

Materials eventually loaded in test, but I'm not sure why. The import log looks pretty similar in test.

**Comment by VVH** [comment]
I tried importing more things into test than to stage. For stage I just included things that had fully imported in test. 

Test log: 


2 weeks, 3 days ago | 2 weeks, 3 days ago | - | - | https://www.loc.gov/item/afc2004004.ms070208/ |  
-- | -- | -- | -- | -- | --
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/afc2004004.ms030246/ |  
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/afc2004004.ms030255/ |  
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/2007660382/ |  
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/afc2004004.ms030255/ |  
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/afc2004004.ms040256/ |  
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/afc2004004.ms040256/ |  
  | 2 weeks, 4 days ago | - | - | https://www.loc.gov/item/afc2004004.ms070208/ |  
  | 1 month, 1 week ago | - | - | https://www.loc.gov/item/afc2004004.ms040229/

**Comment by acdha** [comment]
Did you attempt to retry the incomplete items? It's possible that they're stuck in the retry back-off delay period if there was degraded availability for the source server.

**Comment by VVH** [comment]
Looking at the test log, I retried ms030255 2x, and ms040256 2x, ditto ms070208. I gave a day between the first and second try for ms070208. 

When I tried ms070208 in stage I gave it 2 weeks between attempts.

**Comment by acdha** [comment]
The retries all appeared to have finished now, after the network connection errors reported earlier

**Comment by acdha** [comment]
I wonder whether this was related to a code deployment updating the service while it was running — perhaps @rstorey might know more about that.
