### ISSUE TITLE
Rate limiting uses wrong IP

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1100]
**What behavior did you observe? Please describe the bug**
When 100 anonymous users are simultaneously using the site, the 101th user is unable to reserve any assets at all.

**Additional context**
https://django-ratelimit.readthedocs.io/en/latest/security.html#client-ip-address

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-54](https://staff.loc.gov/tasks/browse/CONCD-54)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
