### ISSUE TITLE
Set up cloudwatch logging for login attempts

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1102]
Successful and unsuccessful login attempts need to be kept in an auditable log in Cloudwatch.

**Comment by rstorey** [comment]
See https://aws.amazon.com/blogs/aws/cloudwatch-log-service/

**Comment by rstorey** [comment]
See #1118 for follow-up work to this.

**Comment by rstorey** [comment]
It seems to be double-logging the messages in ECS.

**Comment by acdha** [comment]
Does the handler have propagate=true? That’s plausibly correct if at some point we want to have it go to CloudWatch but still log to stdout.

**Comment by rstorey** [comment]
https://github.com/LibraryOfCongress/concordia/pull/1125 documents the problem. It doesn't have anything to do with these specific changes, and I don't think it's propagate or the logging configuration. There's something about warning level messages and running with daphne that is duplicating all the warnings in the log.
