### ISSUE TITLE
Optimize performance of site_report task

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1107]
There are a fair number of queries going on here — if performance is acceptable we can table it but if not we might want to have these count calls count the distinct values for the published field & sum the results so we only walk the assets table once.

_Originally posted by @acdha in https://github.com/LibraryOfCongress/concordia/pull/1087_

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-52](https://staff.loc.gov/tasks/browse/CONCD-52)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
