### ISSUE TITLE
Dedupe code in site_report task

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1108]
From #1087 

> I'm a little iffy about the degree of duplication between the campaign and task reports but I'm not sure how much more time you have available to work on this:
> 
> ```
> ~/P/concordia (topic-site-reports|✚1) $ docker run -it --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze concordia/tasks.py
> Starting analysis
> Running structure: Done!
> Running duplication: Done!
> 
> == concordia/tasks.py (8 issues) ==
> 1-333: File `tasks.py` has 255 lines of code (exceeds 250 allowed). Consider refactoring. [structure]
> 26-95: Function `site_report` has 42 lines of code (exceeds 25 allowed). Consider refactoring. [structure]
> 97-167: Similar blocks of code found in 2 locations. Consider refactoring. [duplication]
> 97-168: Function `topic_report` has 36 lines of code (exceeds 25 allowed). Consider refactoring. [structure]
> 170-246: Similar blocks of code found in 2 locations. Consider refactoring. [duplication]
> 170-247: Function `campaign_report` has 36 lines of code (exceeds 25 allowed). Consider refactoring. [structure]
> 250-286: Function `calculate_difficulty_values` has a Cognitive Complexity of 9 (exceeds 5 allowed). Consider refactoring. [structure]
> 289-319: Function `populate_asset_years` has a Cognitive Complexity of 15 (exceeds 5 allowed). Consider refactoring. [structure]
> ```
> 
> It does seem like we should avoid the test coverage dropping, however.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-51](https://staff.loc.gov/tasks/browse/CONCD-51)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
