### ISSUE TITLE
Improve test coverage for site report task

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1109]
For testing, I'd be inclined to run our existing campaign / project / item / asset creation test utilities a few times so we have enough to cover each of the unique states, n > 1 tags by n > 1 users, etc. and then simply test the site report totals at the end.  It feels like we should be able to that in a helper function which would be called with the containing Campaign or Topic but I'd want to think about that more.

_Originally posted by @acdha in https://github.com/LibraryOfCongress/concordia/pull/1087#issuecomment-524330505_

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
