### ISSUE TITLE
Add slug field to bulk import process

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#1111]
**User story/persona**
As an admin I want to be able to set my slug field from within the bulk import spreadsheet. 

Sometimes the project names are very long and I want to create a shorter slug. 

**Acceptance Criteria**
-As an admin I can set the slug before bulk import. 
-If no slug is specified in the new slug column, the slug creator could be the same as it is now for when we import bulk data.

**Comment by elainekamlley** [comment]
In dev and needs testing

Testing plan: 

- [ ] Create a mock spreadsheet with added slugs
- [ ] Then run ingest
