### ISSUE TITLE
Assets on stage not rendering for first 5 pages of results

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#1113]
Steps and behavior/appearance: 

- I used the bulk uploader to import two items to a new Campaign in stage: https://crowd-stage.loc.gov/campaigns/hell-upon-earth/

- The 1-page item (a letter) renders fine, and around 2/3 of the pages in the diary item render as well, but only once you click 5 pages deep into the display results. First 4 pages of results aren't showing. I uploaded a few hours ago, so don't think it's just a lag issue.

- When you click on one of the assets that's not rendering it takes you to asset viewer w/ no image, just a grey box on the left with the error message as you see in the screenshot.

![image](https://user-images.githubusercontent.com/6482891/65278606-73bdab80-dafa-11e9-844c-1ffba073fd67.png)
  
This is where the results are for the diary: https://crowd-stage.loc.gov/campaigns/hell-upon-earth/diary-and-letter/mss52410001/?page=1

I think we saw this issue during Suffrage upload as well. I can't remember what the solution was though.

**Comment by tmcandid** [comment]
What in the fuck is this

**Comment by elainekamlley** [comment]
On review, a comment posted here did not fall within our [comment policy](https://www.loc.gov/legal/comment-and-posting-policy/) and we have removed it.

**Comment by rstorey** [comment]
Here's what I did to fix the problem:
1. Log in to the admin section.
2. Go to Import Item Assets under the Importer section of the admin pages.
3. Filter by unstarted.
4. Select all.
5. Choose the "Retry" option from the Actions dropdown box and click Go.
6. Wait a few minutes.

In this case, it was only 30 things that had been unstarted, so it completed almost as soon as the retry jobs were queued. @VVH please check and let me know if there are still any missing images.

**Comment by rstorey** [comment]
We should also add these steps to the admin documentation.
