### ISSUE TITLE
Consider doing direct-to-cloudwatch login event logging

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1118]
- [ ] Consider doing direct-to-cloudwatch logging with watchtower or logbeam: This seems reasonable but I was wondering whether we want to either make sure that we're not logging every HTTP request to the same log (whether by not logging them or extracting the login related records to a separate file with a longer retention period). One option would be using something like https://github.com/kislyuk/watchtower or https://github.com/osperlabs/logbeam to create a direct-to-CloudWatch handler.

Update 2021-05-07: no current use cases exist to support the two check boxes below:
- [ ] Consider a password reset function for users identified in audit as having entered password in username field: One other concern with logging: it's not uncommon for people to type their passwords into the username field but we want to log that for them to be meaningful, so we need to make sure that we restrict access to these and (potentially) explore having a way to force people to change their password if we see this. Question: how would we know which user had entered their password in the username field and therefore know which user's password to reset?

- [ ] Consider including requesting IP: On a related PII note, should we include the requesting IP?

_Originally posted by @acdha in https://github.com/LibraryOfCongress/concordia/pull/1116_

**Comment by rstorey** [comment]
Would like @elainekamlley and @lalgee to weigh in on the second and third questions. The context for this is that we are now (in dev) logging successful and failed login attempts in our application log, which is automatically saved in CloudWatch. We can use the steps described here: https://aws.amazon.com/blogs/aws/cloudwatch-log-service/ to set up a metric filter and an alarm for excessive failed login attempts.

**Comment by lalgee** [comment]
@jkueloc we don't have use cases to support either the 2nd and 3rd options.  so no need to implement at this time.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-48](https://staff.loc.gov/tasks/browse/CONCD-48)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
