### ISSUE TITLE
User research on the prototype

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1137]
Gather user feedback on the experience of the original discovery interface vs. the prototype. 

Goal: to gain insight on which features improve user experience on finding a page to work and transcribing/review.  

Acceptance criteria: 
- Review past survey collected
- Interview 5 volunteers
- Gather and evaluate feedback
- Generate recommendations based on research findings

Timeline: 
- Week 1: Recruit interviewees 
- Week 2: Develop interview guide and testing plan
- Week 3: Interviews
- Week 4: Evaluation and recommendations

**Comment by lalgee** [comment]
Completed Winter 2020:  https://staff.loc.gov/wikis/display/CS/Winter+2020+User+Research
