### ISSUE TITLE
Create a "jump in" urls that aren't campaign-specific

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1145]
**User story/persona**
As a community manager or developer, I want a url that will take users to an available asset and is not campaign-specific, and thus will not need to be updated when a campaign is completed or retired.

**Is your feature request related to a problem? Please describe.**
Currently all "jump in" urls require a campaign to be specified. When those campaigns are completed or retired those links will have to be replaced.  To avoid broken links and technical debt for community managers and devs, we need to create an evergreen urls that will go to an available asset or in review asset for use in areas of the site and program that will be updated infrequently or never. Some examples: welcome emails, external websites (media), instructions.

Can existing Campaign order field be used to prioritize/determine which campaign users are sent to?

**Acceptance Criteria**
- As a community manager, when I insert a "jump in" url somewhere in Concordia or an external site and it will always take users to a "not started" asset that no other user is working on and will never need to be updated. 

- As a community manager, when I insert a "jump in" url somewhere in Concordia or an external site and it will always take users to a "in review" asset that no other user is working on and will never need to be updated.

**Comment by acdha** [comment]
The idea being that we cannot use https://crowd.loc.gov/act/#mode=review or https://crowd.loc.gov/act/#mode=transcribe because that currently requires a login?

**Comment by rstorey** [comment]
Right. We need something better for onboarding.

**Comment by elainekamlley** [comment]
Yup! And general "jump in" link is helpful CM purposes to get users directly into a page for the newsletters, social media, and any other comms tool.
