### ISSUE TITLE
Modify BagIt export to properly export item-level transcriptions

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1146]
**User story/persona**
As a community  manager, I want to export the Clara Barton completed items with item-level transcription text.

**Is your feature request related to a problem? Please describe.**
It was discovered that the item-level transcriptions text for previously exported / P1-available Clara Barton items had added files at the reel level in order to attach item-level text. It would be better if the export straight from concordia had the item-level text instead of reel-level text so that no additional changes are needed to the bag after export.

**Comment by rstorey** [comment]
CC: @VVH

**Comment by rstorey** [comment]
The existing code uses the tile.loc.gov download URL and assumes that the next level directory is the item level. When in fact, at least for the Clara Barton papers, it's the reel level and item level is one level even higher. So we need an alternate way to export item-level transcription text, one that's based on the P1-level definition of what is an item.

**Comment by acdha** [comment]
Does the stored P1 object JSON have any element with the item-level path?

**Comment by rstorey** [comment]
> Does the stored P1 object JSON have any element with the item-level path?

No :( I think the only way to determine the item-level path is to take the whole list of asset download URLs for all the assets in an item and determine the root / what they all have in common.
