### ISSUE TITLE
Enforce hard expiration to release asset reservations

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1150]
**User story/persona**
As a user, if I leave a page open on my browser for 24 hours I see a modal pop up that lets me know that my reservation on that page has expired. 

**Is your feature request related to a problem? Please describe.**
Other volunteers are prevented from working on pages where the reservation is triggered but no work is actively happening 

**Acceptance Criteria**
- user can dismiss the message
- user will remain on the page 
- if no else is on the page, the user can reload and start a new reservation cycle

**Acceptance Test:**
- sit on a page for 24 hours on anonymous
- sit on a page for 24 hours as a logged-in user

**Comment by acdha** [comment]
Can we precisely define the problem: should we set a maximum reservation time, be able to clear all of them, etc.? One of the thoughts I had is that we’d need to tombstone things so the automatic relock doesn’t reclaim it within a minute or two.

**Comment by rstorey** [comment]
There should be a maximum reservation time. In this case the asset has been reserved for over six days by anonymous.

**Comment by acdha** [comment]
I reviewed the code: we'll need to tombstone the expired reservations to prevent the open client from automatically obtaining a new one on the next call.
