### ISSUE TITLE
Update warning banner language

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1154]
Update the words to be reflect the approved language: 

>This computer system is the property and/or operated on behalf of the Library of Congress and may be accessed only by authorized users. Users may access and use the Library's computer system only for official business and in accordance with Library regulations. Any usage of the Library's computer system is subject to monitoring by the Library and inappropriate usage may subject the user to loss or limitation of system access rights, adverse administrative action, and criminal prosecution. By accessing and using the Library's computer system, users are consenting to monitoring of their activities and communications on the system.

**Comment by rstorey** [comment]
Closed by #1155
