### ISSUE TITLE
Use Centrify / Cognito for Kibana and admin sections of the site

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1159]
- [ ] Switch from IAM to ACM managed certificates for dev, stage and prod (test is already ACM)
For admin and Kibana site paths:
- [ ] Configure the application load balancer to force Cognito authentication 
- [ ] Set up SAML to Centrify as Cognito provider

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-47](https://staff.loc.gov/tasks/browse/CONCD-47)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
