### ISSUE TITLE
Be able to load newer campaigns in the activity UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1166]
**User story/persona**
As a user, I want to quickly load pages from newer campaigns in the activity UI. Currently it takes a very, very long time to get newly imported pages in the activity UI.

**Comment by acdha** [comment]
This is basically hitting the challenge of most of our existing sort metrics being based on criteria which favor some of the big older projects, right? There might be some room for optimizing the queries — the current approach uses pages and it might be worth changing it to do something cursor-like where we could optimize the SQL query with a `.filter(pk__gt=last_pk)` — but I was also wondering whether we might want to reconsider some of our ordering choices to allow doing something like, say, fetching the top n from each project early and passing the active campaign filter back to get those assets immediately if someone picks a particular campaign.
