### ISSUE TITLE
Confirm whether the admin really wants to reopen or redownload

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1175]
**User story/persona**
As a community manager, I want to reopen assets or redownload images so that I can correct data problems on the public site.

**Is your feature request related to a problem? Please describe.**
When reopening assets in the assets list view, there is no confirm step before assets are reopened. It's possible it could be done accidentally.

The redownload images task also needs an extra confirm step. After reading in the spreadsheet, it would be good to confirm "This will affect N transcriptions. Continue?" before proceeding.

Stems from #1174

**Comment by elainekamlley** [comment]
The reopening feature has been in use for about a year and no issues on reopening an asset has occurred. Closing ticket.
