### ISSUE TITLE
Completing the CAPTCHA does not clear the “Unauthorized” message

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1178]
**What behavior did you observe? Please describe the bug**
After an anonymous user hits save and enters correct captcha, an error is raised “unable to save”. The text will be saved after you hit save again. 

**How can we reproduce the bug?**

1. Go to a transcribable asset
2. Transcribe a few works and Click save
3. Enter correct captcha 
4. See error above viewer

**What do you expect**
After a user enters text hits save and enters a correct captcha, the entered text saves.

**Comment by acdha** [comment]
The text is being saved but it wasn't clearing the initial “Unauthorized” error which triggered the CAPTCHA display. Hitting Save a second time will clear it, so all that appears to be needed is having the successful CAPTCHA + resubmit stage trigger the same message clearing.
