### ISSUE TITLE
Remove description text from SPLEDOX items

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1180]
Descriptions are appearing under the item title. This comes from the P1 description field. Remove this field from all items in the Spanish legal docs campaign. 
<img width="1206" alt="Screen Shot 2020-01-23 at 10 32 51 AM" src="https://user-images.githubusercontent.com/7362915/72998395-c0c4cd80-3dcb-11ea-918d-fc307f2de26d.png">

**Comment by rstorey** [comment]
@elainekamlley This is ready for testing in dev and test. To test, import the spledox campaign content and then check the item page and verify the descriptions don't show up. Optionally, you can enable the feature flag (documented in the admin guide) and then verify that items that have descriptions do display them.
