### ISSUE TITLE
Automate routine cleanup tasks

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1182]
Stems from #1160 

- [ ] Keep the last 30 days' database dumps plus the first dump per quarter in S3 (this is in addition to built in RDS snapshots) - develop a process for cleaning out old database dumps (S3 lifecycle policy)

- [x] Develop an automated process for cleaning out old ECR docker images

**Comment by acdha** [comment]
One thing which might be a good side-car for the second point is flipping the ECR flag to make tags immutable so we could have a policy like “We keep the last n versions following semver and purge the rest”.

**Comment by jkueloc** [comment]
For the second point - first step - I've added a lifecycle policy concordia, concordia/celerybeat, and concordia/importer repositories to remove untagged images older than 90 days.

**Comment by jkueloc** [comment]
For ECR - Updated lifecycle policy on concordia, concordia/celerybeat, and concordia/importer repositories to include additional rules  to maintain a count of 1 of each tagged release and latest, remove untagged images older than 90 days and remove prefix 0. images older than 360 days (not great but it's something for now).

**Comment by jkueloc** [comment]
This ticket implemented a lifecycle policy for ECR.
The database dmp file clean up process was moved to #1549.
