### ISSUE TITLE
Add status filtering to item dashboard in Concordia admin

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1187]
**User story/persona**
As a Community Manager, I need to be able to know which items are completed (meaning every asset that makes up the item has been completed).  This is particularly important for getting an accurate count of exported items/assets for loc.gov transcription ingest. 

**Is your feature request related to a problem? Please describe.**
Currently there is no way for community managers to know which items are completed (outside of clicking through the public interface) or get a count of total completed items.

**Additional context**
This request was escalated following a meeting about loc.gov transcription counting on Jan. 30, 2020.  This is how status filtering appears on the asset dashboard:
![image2020-1-30_14-12-7](https://user-images.githubusercontent.com/20258744/73483460-74e6cb00-436d-11ea-9158-8045bb67f8f2.png)

**Acceptance Criteria**
As a Community Manager, I can filter the admin item dashboard to only see completed items and see a count of them.

**Comment by elainekamlley** [comment]
There are now counting processes in place - this feature is not needed.
