### ISSUE TITLE
Create pages for Spanish instructions

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1194]
Create new pages for Spanish language instructions. 

- [x] Create URLs
- [x] Transcribe 
- [x] Review
- [x] Tag
- [x] Welcome guide (?)

**Comment by acdha** [comment]
Is it sufficient to create instructions or do we also need to start using the Django [localization framework](https://docs.djangoproject.com/en/3.0/topics/i18n/) to support other languages in the actual UI as well?
