### ISSUE TITLE
Make confirmation of transcription data during asset reopening process smoother

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1195]
**User story/persona**
As a community manager user, I want to 
- be able to reopen an asset from the individual asset’s page 
- be able to see a preview of the first line of linked transcriptions on the individual asset page (like what you see in the transcriptions dashboard).  
- see the first line of the most recent transcription in the asset dashboard page?  Some unused fields like year and metadata could be removed from this view to make some space.

**Is your feature request related to a problem? Please describe.**
Having reopen functionality only at the asset dashboard means that CM's search for the asset in the asset dashboard, then have to click several levels down to confirm that is the correct asset (via looking at the transcriptions), and then go back up to the asset dashboard to actually reopen.

**Comment by elainekamlley** [comment]
This process has been in place for a few months and does not need further development.
