### ISSUE TITLE
504 errors for next transcribable/reviewable asset links; admin backend; and user login

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1212]
**What behavior did you observe? Please describe the bug**
Users and community managers are reporting 504 links when:

- Clicking links using the "next transcribable asset" or "next reviewable asset" 
- Trying to save a simple page update in Concordia backend.
- Trying to log in to Concordia backend (as public user or admin)

**How can we reproduce the bug?**
Click suffrage "let's go" button in homepage carousel.

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

-   Windows 10, Firefox and Chrome

**Comment by acdha** [comment]
Has this been an issue since https://github.com/LibraryOfCongress/concordia/releases/tag/v0.6.5?

**Comment by lalgee** [comment]
No.  Resolved.
