### ISSUE TITLE
Enable re-download images feature

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1221]
**User story/persona**
As a community manager, I want to use the re-download images feature so that I can replace corrupted images that were already published in a campaign.

**Additional context**
Because of the `@update_task_status` decorator, we need to create a data model to back the redownload images feature jobs. The only other way to use the feature is to rebuild the application without the decorator - in which case, import job status won't be saved in the database.

**Acceptance Criteria**
* Be able to use the importer with saved status in the database for import item asset jobs
* Be able to use the redownload images feature with saved status in the database for asynchronous jobs

**Comment by lalgee** [comment]
Community managers can now replace individual asset images using https://github.com/LibraryOfCongress/concordia/issues/1575
or replace in bulk via AWS
