### ISSUE TITLE
Fix the automated database dump process

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#1226]
The automatic database dump process is broken. Perhaps the database has finally exceeded the resource limitations of Lambda. If we can't increase the memory or disk size of the Lambda functions, we need to figure out an alternate way to dump the production database automatically on a nightly basis.

**Comment by acdha** [comment]
Do we know what's limiting it? Lambda scales CPU count with RAM so it might be necessary to over-allocate RAM to get an extra vCPU.

**Comment by jkueloc** [comment]
@elainekamlley @rabiloc... In an attempt to get this moving in the short term I added memory to the production dump process to match that of the restore processes which I believe were run in December. I also re-enabled the cloudwatch trigger for the daily run. We'll see how it goes. I'm hoping the memory increase will be enough for now. If not- I'll take a look at the logs and see if it's a memory or timeout issue and go from there.

**Comment by jkueloc** [comment]
@elainekamlley @rabiloc.. just to followup here.  Increasing memory didn't resolve the failure as the disk space error is the Lambda ephemeral limit of 512 MB (/tmp directory storage).

**Comment by elainekamlley** [comment]
Kibana is down, is that related to this ticket as well?

**Comment by jkueloc** [comment]
No

**Comment by acdha** [comment]
> @elainekamlley @rabiloc.. just to followup here. Increasing memory didn't resolve the failure as the disk space error is the Lambda ephemeral limit of 512 MB (/tmp directory storage).

Compression might buy some time but I’d either rewrite this to stream to S3 or to run in ECS (10GB scratch) as a scheduled task. You could also setup EFS but that’s a lot of infrastructure for a temporary file.

**Comment by jkueloc** [comment]
@acdha Thanks! Rosie had started down the ECS path as a scheduled task. I'm working toward completing that work.

**Comment by acdha** [comment]
ECS makes more sense since it also avoids the total runtime limit and it's consistent with the rest of the application.

**Comment by jkueloc** [comment]
Just a quick update - the crowd-db-dump, and crowd-db-restore containers are working. The ESC Tasks (crowd-<env>-db-restore - dev, test, stage and  dump - ) have been defined and the dev and test db restores are now scheduled tasks. I still need to test the prod db dump through the ECS task and once that's successful I'll create an ECS scheduled task for the prod dump.
