### ISSUE TITLE
As a community manager I want to move projects to different campaign

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1227]
Currently when a CM moves projects to a new campaign in the admin dashboard an additional step to move the projects in s3 needs to be made. There needs to be a signal to S3 to move projects/items/assets when those changes are made in the admin dashboard.

**Comment by rabiloc** [comment]
@elainekamlley Hey Elaine, can you please give me a quick overview of how you currently do this? Maybe a meeting next week. Thanks.
