### ISSUE TITLE
List projects in multiple Topics

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#1232]
**User story/persona**
As a Community Manager, I want to be able to list Campaign Projects in multiple Topics so that I can thematically group materials in BTP to help users explore content in a variety of ways

**Is your feature request related to a problem? Please describe.**
Community Managers had assumed it would be possible to list projects in multiple places, so for example Lincoln in Civil War and the new Presidential Papers Topic.

**Acceptance Criteria**

- Ability to list Projects in multiple Topics

**Acceptance Test:**

- Assign a project, ie "1864: Civil War" in Letters to Lincoln to both Civil War and Presidential Papers.
--

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-45](https://staff.loc.gov/tasks/browse/CONCD-45)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
