### ISSUE TITLE
Asset status was not updated from “needs review” when a transcription was accepted

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#1235]
There is one page remaining in the Lincoln Campaign. The filters all mark it as "needs review" but when you drill down to the asset it appears "complete"

**How can we reproduce the bug?**

1. Go to https://crowd.loc.gov/campaigns/letters-to-lincoln/?
2. Click on Needs Review (https://crowd.loc.gov/campaigns/letters-to-lincoln/?transcription_status=submitted)
3. Click through to https://crowd.loc.gov/campaigns/letters-to-lincoln/1864-civil-war-and-re-election/mal2947200/mal2947200-3/
4. Go into Concordia Admin space and navigate to asset in asset list. Try to unpublish and republish to change status. When I tried this on 7/13/20 there was no status change.

**What is the expected behavior?**
The page should no longer appear "in review"

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/6482891/87345902-c9969080-c51e-11ea-8f04-ca892adbf5fd.png)

![image](https://user-images.githubusercontent.com/6482891/87345992-ed59d680-c51e-11ea-9ae5-38ef18eba2ae.png)

![image](https://user-images.githubusercontent.com/6482891/87345957-e0d57e00-c51e-11ea-8e3a-c511603cf943.png)

**Desktop (please complete the following information):**

-   Windows
-   Chrome and Firefox, regular mode and privacy modes

**Comment by acdha** [comment]
Normally when a transcription is saved the asset status will be updated to reflect the latest progress using this code:

https://github.com/LibraryOfCongress/concordia/blob/e8892e19d5b82f2a2b303d036a5ef838d7a7ecaa/concordia/signals/handlers.py#L88-L103

It's not clear why the standard save handler isn't being executed — normally saving the transcription again would trigger it but that didn't cause an update:

https://crowd.loc.gov/admin/concordia/transcription/312417/change/?_changelist_filters=asset__id__exact%3D53822

Perhaps @biswasrk can see if there are any errors in the ECS task output which might indicate why that wasn't running.

**Comment by rabiloc** [comment]
Sounds good, Rosie and I will have a look at it and see what we find.

**Comment by rabiloc** [comment]
I don't see it in, "in review" any longer.

**Comment by elainekamlley** [comment]
Lets close this. Looks like the status just took a bit to update.
