### ISSUE TITLE
Compare byte count or hashes to verify images are bit wise identical

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1237]
**User story/persona**
As a community manager, I want to see a report comparing byte count or hashes of images during ingesting a new campaign so that I can know if the assets are correct.

**Is your feature request related to a problem? Please describe.**
Specifically in the Herencia campaign some images only downloaded half way causing images to be cut off. Community managers have now fixed them as users come across them by downloading the full image from loc.gov and uploading that image directly into the S3 bucket. 

**Acceptance Criteria**
Add a list items this new feature needs to meet. Ex: The user would not be able to submit a form if all the mandatory fields are not entered.

**Acceptance Test:**
Add a list of steps to test for a user to check if functionality satisfies the acceptance criteria.

**Comment by acdha** [comment]
The downloader only saves files which completely transfer without an error so we might want to figure out where a trustworthy source of hashes / byte counts would come from in the case where the source is not reliable.

https://github.com/LibraryOfCongress/concordia/blob/295629d522ecfbe9ce8276d5d9f36a1a71ea11f7/importer/tasks.py#L510-L530

**Comment by elainekamlley** [comment]
Byte count is size at this level of the loc.gov json: https://www.loc.gov/item/mss3413201014/?fo=json&at=resources
