### ISSUE TITLE
Unable to manually create projects

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1239]
**What behavior did you observe? Please describe the bug**
When an Admin tries to create a project manually in stage, user gets a 500 error. This blocks the ability to create a new project for manual import.

**How can we reproduce the bug?**
1. Go to Projects sub-dashboard.
2. Click Add Project.
3. In the Campaigns dropdown, select a campaign.
4. Fill in the Project title and slug fields and click Submit. 
5. See error page.

**What is the expected behavior?**
Expect that a new project should be created, linked to the chosen Campaign.

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome and Firefox

**Additional context**
This is a blocker for creating new campaigns via manual import, which is useful for extremely small campaigns.  However, bulk import for project creation is a viable workaround and is already the preferred project creation method in the majority of cases.

**Comment by acdha** [comment]
https://github.com/LibraryOfCongress/concordia/commit/4a262c371da41e1a425fc9ee70a4b2924352e62d (see #1236) needs to handle the case where the project has not yet been saved (i.e. `obj.pk is None`)

**Comment by rabiloc** [comment]
Sounds good, let me look into it

**Comment by rabiloc** [comment]
I'll remove the save_model code for now, and test it some more in dev environment
