### ISSUE TITLE
As a community manager I can export text 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#124]
- [ ] by various formats `.csv`, `.json`
- [ ] that is connected to the item ID and image
- [ ] by collection ID, project ID, Folder view (consecutive images related to each other) 
- [ ] by clicking an export button and it gives me options

**Comment by rstorey** [comment]
We have campaign level export in CSV and BagIt formats. If there are additional needs beyond what we have currently implemented, let's ticket them when they arise.
