### ISSUE TITLE
Reorder status list in filter display

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1244]
**User story/persona**
As a user I expect the order of the statuses listed in the filter to match the order of the sequence of volunteer actions – transcribe, edit, review, complete.

**Is your feature request related to a problem? Please describe.**
Currently users are confused by the order of the statuses in the filter that appears on the campaign, project, item, and asset landing pages.  It would be improved by reversing the order of the list to match the sequence of volunteer actions.  

**Additional context**
This friction was identified in Winter 2020 user testing.

Current view of the status filtering:
![image](https://user-images.githubusercontent.com/20258744/90827680-a4a9f000-e30a-11ea-8964-b7dca58f532c.png)

**Acceptance Criteria**
The order of status in the filter throughout the site should be:
- Not started
- In progress
- Needs review
- Completed

**Comment by jkueloc** [comment]
@lalgee this is dev now if you'd like to take a look.

**Comment by lalgee** [comment]
@jkueloc looks great in stage!  let's move it to production!
