### ISSUE TITLE
Update filter to take volunteers directly to assets/activity

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1245]
**User story/persona**
As a user, if I click on a filter on the Campaign or Project page, I expect to go to a page that has all the assets in that Campaign (Project) that need review, not a page with items (folders) that I then have to navigate through. This is especially confusing because the item thumbnails are not always a good indication of type of content within.

**Is your feature request related to a problem? Please describe.**
Currently when a user clicks on a filter such as on Needs Review on a Campaign or Project page, they are only taken to the next level down (Project or Item) that they then have to navigate through. This is additionally a problem because the item thumbnails are not always a good indication of type of content within so a user may have to navigate through the hierarchy repeatedly before finding something they want to work on.

**Additional context**
This need was identified by user research in Winter 2020

**Comment by lalgee** [comment]
This is related the larger issue of navigation and the desire to somehow collapse or abbreviate the Campaign/Project/Item/Asset hierarchy.

**Comment by elainekamlley** [comment]
This would require a large lift to change the navigation structure. Close due to limited capacity.
