### ISSUE TITLE
Remember a users' recent and preferred activities

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1248]
**User story/persona**
As a registered user, I automatically want Concordia to remember what I worked on and my preferred activity, -- including if my preferred action is transcribe or review, campaigns or projects  I'm interested in, and which asstets I recently worked on.

**Is your feature request related to a problem? Please describe.**
Currently if volunteers want to resume activity they were previously engaged in they have to remember what that was and how to get back to them. It can be difficult and tedious (or even impossible) to find and navigate back to pages deep within a campaign.

**Additional context**
This issue was identified during winter 2020 user research.

**Acceptance Criteria**
When a registered user is signed in, they can easily navigate back to areas of campaigns they have previously worked on or that are available fork in their preferred campaigns or activities.

**Comment by elainekamlley** [comment]
This is a good idea but is challenging to implement. Closing as a won't fix.
