### ISSUE TITLE
Make transcription box able to be moved beneath page viewer

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1249]
**User story/persona**
As {a user}, I want to be able to choose if on a transcription page the image viewer and transcription box are side-by-side windows or stacked on top of each other.

**Is your feature request related to a problem? Please describe.**
Depending on their device, sightedness, or visual preferences, some users would prefer to transcribe by looking at an image viewer that fills the width of the browser window with the transcription box right below it. The width of the viewer/transcription box is already somewhat adjustable so users expect that they could also be able to widen the viewer further and arrange the page in this way.

**Additional context**
The NARA catalog transcription feature is oriented horizontally: 
![image](https://user-images.githubusercontent.com/20258744/91194471-2d87a980-e6c6-11ea-89c2-0af999656089.png)

**Acceptance Criteria**
Volunteers can choose for the viewer and transcription to be arranged side-by-side horizontally or stacked vertically.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-44](https://staff.loc.gov/tasks/browse/CONCD-44)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
