### ISSUE TITLE
Multi-volume item hierarchy is lost during import

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1254]
**What behavior did you observe? Please describe the bug**
When multi-volume items are imported from loc.gov they include an additional layer of hierarchy between items and resources. Concordia item.  Concordia import only expects the structure of items with a single layer of resources. The hierarchical layer of resources above the images are lost.

**How can we reproduce the bug?**
Look at "Seers, Spiritualists, and the Spirit World: The experiments of Frederick Hockley" campaign in stage  [here](https://crowd-stage.loc.gov/campaigns/hockley/). This is the first collection we have imported into By the People to have multiple layers of resources underneath the items in the collection’s loc.gov hierarchy.  

I imported an additional multivolume item into "Test Campaign" on stage and it shows the same issue.

**What is the expected behavior?**
Usually a the structure of a By the people campaign is: campaign/project/item/assets, in which the BTP items = p1 items and the BTP assets = p1 page images.  The volumes of Hockley are an additional layer unexpected by the BTP importer code, so we were uncertain how it would bring in the 11 volumes and their 4,000+ collective pages. 

When imported into stage, the intermediary layer of the 11 individual volumes were merged into a single concordia item. Note: All but 9 assets were deleted for testing export. 

The original Hockley loc.gov structure is: 
-	item (multivolume set “the crystal”)
-	resources (volumes)
-	resources (volume pages)

The Hockley Concordia imported structure is: 
-	item (multivolume set “the crystal”)
-	assets (volume pages)

**Additional context**
We are planning to launch the Hockley campaign at the end of October 2020.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-43](https://staff.loc.gov/tasks/browse/CONCD-43)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
