### ISSUE TITLE
Multivolume items export is not compatible with loc.gov ETL

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1256]
**What behavior did you observe? Please describe the bug**
The BagIt export of multivolume items doesn't name the text files by the image number and introduces additional directory nesting which do not match up to the loc.gov ETL process.

**How can we reproduce the bug?**
Do a BagIt export of the completed items from  "Seers, Spiritualists, and the Spirit World: The experiments of Frederick Hockley" or "Test Campaign" in stage.

Example of the nesting and naming from Hockley: 
\data\https\tile.loc.gov\image-services\iiif\service\rbc\rbc0001\2018\2018houd14646v4\0002\full\pct\100\0\default.jpg.txt is the transcription filepath as exported from Concordia for the image at /public/service/rbc/rbc0001/2018/2018houd14646v4/0002.jpg.

The issues you'll see:
1.	Hockley is from Rare Book and the Test Campaign item is from G&M. One has jpgs in presentation storage, so it’s pulling the jpg from storage; the other does not, so it’s using iiif. This explains why the content is broken into image-services directory and storage-service directory upon export. Hockley also pulls in images using iiif. This distinction is not appear to be causing the issue, though.
2.	In both cases the bag is exporting the content based on the URL from the tile server (a subdirectory is created on the slash in the URL) and not structured based on how the images are structured in presentation. The difference is more obvious when looking at the image-service directory example.
3.	There is still the same issue that files are being named by the name of the jpg in the file path (ex: default.jpg.txt and 001v.jpg.txt). The text file needs to be named the same as the image. 

**Additional context**
This issue is most pressing for the Hockley materials which are expected to launch at the end of October 2020. Multivolume structure is being used more and more frequently for loc.gov presentation so it's likely we will also encounter this issue in other future campaigns but no other planned multivolume campaigns are currently in the queue.

Related issues:  #1254 and https://github.com/LibraryOfCongress/concordia/issues/1255

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-42](https://staff.loc.gov/tasks/browse/CONCD-42)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
