### ISSUE TITLE
Remove or update help text from Contact Us form

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1258]
**User story/persona**
As a user I want to know what information I should include in the different fields of the [Contact Us](https://crowd.loc.gov/contact/) form.

**Is your feature request related to a problem? Please describe.**
The help text intended to assist users in filling out the Contact Us form duplicates the questions.  This is unhelpful and confusing (particularly in the case of the page url field which says "Have a specific page you need help with? Add the link below:"
![image](https://user-images.githubusercontent.com/20258744/93385083-b3b18e80-f833-11ea-99c8-38f3d4c53ba7.png)

This text should be updated to be different from the questions it is supposed to be assisting with OR it can just be removed.

**Comment by acdha** [comment]
The default behaviour can be changed by setting the setting `set_placeholder` to false (see https://github.com/zostera/django-bootstrap4/blob/main/docs/settings.rst) to prevent the label from being used when a specific placeholder value has not been defined.

**Comment by jkueloc** [comment]
@lalgee this is ready for testing

**Comment by lalgee** [comment]
The help text is gone. Thumbs up!  

@elainekamlley I believe the 3rd field text is not bolded to indicate that's it's optional, but that's not clear at all. While Jen is working on this page, can we add "(optional)" after it?

**Comment by jkueloc** [comment]
@lalgee & @elainekamlley - Could rephrase to: " Optionally, if you have a specific page you need help with, add the link below:"
It does appear that the required=True bolds the label text. This particular field is required=False.

**Comment by elainekamlley** [comment]
Update content to read: `Have a specific page you need help with? Add the link below (optional):`

**Comment by elainekamlley** [comment]
Looks good!
