### ISSUE TITLE
Use symbolic names for colors in CSS file

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#126]
(from @acdha ) Rather than having some comments indicating the hex counterparts for a particular rgb() / rgba() declaration, which will have to be diligently updated, I would prefer to see symbolic names indicating why those color values exist.

I don't know what our browser support strategy is (perhaps @rstorey can help?) but while the old-school approach would just be a text comment (“primary text color”, “highlighted element title color”, etc.), a more recent approach would be to use something like SCSS with a preprocessor (which I would support), and since it's 2018 we could go straight to using native CSS variables if we don't support IE11:

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
https://caniuse.com/#feat=css-variables

(from @rstorey) I think we'll have to support whatever browsers the public loc.gov website supports. I'm not sure what their strategy is but it would be easiest to stay in sync with that.

Stems from #102

**Comment by elainekamlley** [comment]
This is done as well?

**Comment by rstorey** [comment]
Yes done
