### ISSUE TITLE
Filter in admin dashboard: Nesting Projects under Title Campaign

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1264]
**User story/persona**
As an admin when I click on campaign I want to be see only the projects associated with the campaign so that I can filter by just those projects

**Is your feature request related to a problem? Please describe.**
As the program matures there are more campaigns/projects that need to be managed in the application. This has resulted in very long project lists, often having similar project names (ie Diaries or Miscellany) and is becoming harder to filter by the project we want.  

**This feature is applicable to the following pages in the dashboard:**
https://crowd.loc.gov/admin/concordia/asset/
https://crowd.loc.gov/admin/concordia/item/
https://crowd.loc.gov/admin/concordia/transcription/
https://crowd.loc.gov/admin/importer/importitemasset/
https://crowd.loc.gov/admin/importer/importitem/
https://crowd.loc.gov/admin/importer/importjob/

**Additional context**
Import jobs only have a long list of projects. There is no way to filter by campaign first and then projects
Here is the item page: 
![screencapture-crowd-loc-gov-admin-concordia-item-2020-11-24-09_50_24](https://user-images.githubusercontent.com/7362915/100111102-bcc66980-2e3b-11eb-9323-909ea06339d5.png)

**Acceptance Criteria**
GIVEN I am an admin/Community Manager
WHEN I filter by campaign 
THEN I can see a smaller list of all associate project to that campaign

**Acceptance Test:**
Add a list of steps to test for a user to check if functionality satisfies the acceptance criteria.

**Comment by jkueloc** [comment]
@elainekamlley the filters are in dev and ready to be tested.

**Comment by lalgee** [comment]
Looks great in dev @jkueloc! I checked all of the areas where the feature is applied. Thumbs up!
