### ISSUE TITLE
Add labels for campaign short and long description fields in Admin Campaign editor

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1266]
**User story/persona**
As an Community Manager, I need to know which Campaign description field I am editing when making changes via the Admin Campaign page.

**Is your feature request related to a problem? Please describe.**
Campaigns have 2 description fields which are editable via text boxes in the Concordia Admin but these fields are not labeled so it is unclear to which field you are editing. The long description field is currently ordered first and the short description field is below.

**Additional context**
As showin in the screenshot below, text box 1 is the campaign long description and box 2 is the short description.
![image](https://user-images.githubusercontent.com/20258744/94602108-70f3ab80-0262-11eb-9693-73bbdf32f86a.png)

**Acceptance Test:**
Both text boxes are labeled to indicate which description field they contain. As an Admin, I can easily see the field names and understand what text I am editing.

**Comment by jkueloc** [comment]
@lalgee this is ready for testing

**Comment by lalgee** [comment]
Looks good!
