### ISSUE TITLE
Unable to publish larger items using "Published" checkbox

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1271]
**What behavior did you observe? Please describe the bug**
Recieved a "Bad Request (400)" error message when trying to publish individual items using the "Published" checkbox.  I was able to successfully publish two items with less than 20 assets using this method.  But was not able to publish larger items.

**How can we reproduce the bug?**

1. Go to Items
2. Search for an unpublished item (try mss1288001139, it has 725 assets)
3. Click on the item to go to its individual item page.
4. Click the "Published" checkbox, you should see a blue check mark.
5. Click "Save" at the bottom of the page.
6. Error message loads.

**What is the expected behavior?**
The page should save and reload with the box checked and the item should then be published on the By the People frontend.

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/20258744/95618560-4ad8c300-0a3b-11eb-8fb1-655a95d3e227.png)

**Desktop (please complete the following information):**
-   OS: Windows
-   Browser: Chrome

**Additional context**
Generally we publish and unpublish items using the "Publish selected item and assets" function on the item search page. However, in this instance I need to publish items but have some of their assets remain unpublished, so I can't use that feature. Community managers have rarely, if ever, utilized the "Published" checkbox for items in the past.

**Comment by acdha** [comment]
This is another instance of needing to increase the maximum upload size limit, as with the bulk deletes: 

https://errorlogging.loc.gov/share/issue/e484efbcc927478691b2e97283c00db7/

**Comment by rabiloc** [comment]
@acdha I'm guessing this is the DATA_UPLOAD_MAX_MEMORY_SIZE property, I don't see it in the application, do I need to add this to the setup.py file? or another file.

**Comment by acdha** [comment]
It's a Django setting: 

https://docs.djangoproject.com/en/3.1/ref/settings/#data-upload-max-memory-size

**Comment by rabiloc** [comment]
Should I set this value to None, or should this be an integer number?

**Comment by acdha** [comment]
The purpose of that setting is to block attacks or mistakes which send huge amounts of POST data. It's not an enormous issue since we have automatic fault recovery if something crashes due to running out of memory but I generally like to leave those capacity limits greater than normal usage but still enabled to catch gross errors.

**Comment by acdha** [comment]
Yes, but I'd write that as `10 * 1024 * 1024` to make the comment less necessary
