### ISSUE TITLE
Remove x within tags for anonymous user

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1275]
**What behavior did you observe? Please describe the bug**
As a user that signed out or anonymous, I can removing a tag that looks like I am deleting. This can be very confusing for the user and may cause the user to think that they removed a tag without meaning to.

**How can we reproduce the bug?**

1. Go to https://crowd.loc.gov/campaigns/branch-rickey-changing-the-game/scouting-reports/mss37820008/mss37820008-2/
2. Click on x next to a tag
3. The tag will be removed 

**What is the expected behavior?**
No x should appear on the tag. A anonymous user should only be able to see the tag and not interact with it. 

**Got screenshots? This helps us identify the issue**
![Screen Shot 2020-10-19 at 3 27 28 PM](https://user-images.githubusercontent.com/7362915/96503044-a9165a80-1220-11eb-9e78-05e5e253b595.png)

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-41](https://staff.loc.gov/tasks/browse/CONCD-41)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
