### ISSUE TITLE
Ask users if they want to save before exiting a transcription page

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1278]
**User story/persona**
As a volunteer, I don't want to lose my work when I move to another page without clicking save. I want a reminder to click "Save" anytime I click a link to move away from a transcription page when my work has not been saved or submitted.

**Is your feature request related to a problem? Please describe.**
Many users are accustomed to applications that autosave their work so they may not save frequently or before leaving a page. Additionally, they may not expect that clicking on certain links will take them away from the transcription page.

**Additional context**
From a user email:

> "I can't say how many times I've had to re-transcribe some material because I had to jump to the help page or other reason, only to return to the transcription page to find my work had vanished because I didn't save it. Is it not possible to have an autosave function, where the transcriber's work is saved every few minutes automatically? Or to have the page saved automatically when the user leaves the page? Or have links on the transcription page (esp. Help) pop up on a new tab/window? Yes, it's user error. I admit that. But having been involved in website design years ago, briefly in my career, I can say it's also a fault in the user interface, one that can annoy and frustrate volunteers (like me). Please keep us happy!" 

**Acceptance Criteria**
When a user on a transcription page has not saved their work and clicks a link to navigate to a new page they are not taken away from their current page but instead see a reminder to click "Save" or "Submit" before leaving and then have the opportunity to do so. The user should then be able to stay on the page and continue working OR can choose to leave the page anyway.

**Acceptance Test:**

1. Type some text into the transcription page for a "Not started" or "In Progress" asset
2. Click the "Campaigns" link in the navigation bar.
3. A popup appears asking if you really want to leave

3a. You say no and the pop up closes, leaving you on the transcription page
4a. You are able to save your work or continue working.

3b. You say yes and navigate to the new page when you 
4b. Go back to the page you just left and see that your work has not been saved.

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
