### ISSUE TITLE
Update login screen text to indicate ability to log in with email

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1284]
**User story/persona**
As a user, I want to know that I can log in with my email address in case I forget my username.

**Is your feature request related to a problem? Please describe.**
The login page indicates that you need to enter your username to log in.  However, the field also accepts email address. Users who have forgotten their username will email community managers for help because they do not realize they could log in with just their email address.

**Additional context**
If users forget their username they will still almost certainly remember their email address and could still log in that way without having to contact community managers for support. 

Add "or email address" to the text identifying the first login field as "Username"
![image](https://user-images.githubusercontent.com/20258744/98592173-55d37d00-229f-11eb-8f03-ae682d5451c6.png)

**Comment by jkueloc** [comment]
@lalgee and @elainekamlley  - this update is in dev and ready to be tested/viewed/QA'd.
Thank you!

**Comment by elainekamlley** [comment]
@jkueloc looks good to me! Let's let @lalgee sign off first before closing.

**Comment by lalgee** [comment]
Looks good @jkueloc!
