### ISSUE TITLE
Renew PKI Certificate

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1285]
Submit a service now ticket to renew the certificate in dev/test/stage

**Comment by jkueloc** [comment]
Working with John Foley and Chris Adams on the expired certificates for dev and staging - which were issued by LoC. Chris created a certificate for each environment - dev and stage in AWS CA.  At some point the certs will need to be installed or imported...

**Comment by jkueloc** [comment]
This has been completed with the heavy lifting being done by @acdha.

**Comment by elainekamlley** [comment]
Looks good!
