### ISSUE TITLE
SVG logo for 'By the People'

### ISSUE THREAD

**Issue by klee72** [LibraryOfCongress/concordia#1300]
**User story/persona**
As a ui developer, I want to replace the current 'By the People' logo in text with svg.

**Is your feature request related to a problem? Please describe.**
'By the People' logo in the header is currently created with text and it should be replaced with a svg to be consistent with Library branding.

**Acceptance Criteria**
Please attach the logo in svg file to this ticket.

**Acceptance Test:**
n/a

**Comment by jbresner** [comment]
[logo-by-the-people.svg.zip](https://github.com/LibraryOfCongress/concordia/files/5735837/logo-by-the-people.svg.zip)

@klee72 - Here's the "By the People" portion of the logo in SVG format. Let me know if you need any other portion of the header graphic that makes up the logo.
