### ISSUE TITLE
docker-compose up results in an infinite loop

### ISSUE THREAD

**Issue by bkalish** [LibraryOfCongress/concordia#1302]
**What behavior did you observe? Please describe the bug**

I ran the commands 
```
git clone https://github.com/LibraryOfCongress/concordia.git
cd concordia
docker-compose up
```
according to the [instructions For Developers](https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md)

The `docker-compose up`  command never stops running and seems to loop through errors repeated as containers start and restart.

The output of `docker-compose up` begins with the warning `WARNING: The POSTGRESQL_PW variable is not set. Defaulting to a blank string.`

A number of other warnings appear, but the first exception is `CRITICAL/MainProcess] beat raised exception <class 'django.db.utils.OperationalError'>: OperationalError('fe_sendauth: no password supplied\n')`

From then on the logs appear to loop with a near repetition every several hundred lines or so.

**Desktop (please complete the following information):**

-   OS: MacOS 10.13.6
-   Docker Desktop 2.5.0.1

**Additional notes**
I tried, in my desperation, replacing `${POSTGRESQL_PW}` with `password` in `docker-compose.yml`. Not surprisingly, given my ignorance of the inner workings, this didn't work either, and also resulted in numerous errors, but it the loop was much shorter and repeated exactly. In the perhaps vain hope that it may still provide useful information, here is the repeating portion:
```
app_1            | Running makemigrations
app_1            | No conflicts detected to merge.
app_1            | Running migrations
app_1            | Operations to perform:
app_1            |   Apply all migrations: admin, auth, captcha, concordia, contenttypes, django_celery_beat, flags, importer, robots, sessions, sites
app_1            | Running migrations:
app_1            |   No migrations to apply.
app_1            |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
app_1            |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
app_1            | Ensuring our base configuration is present in the database
app_1            | Running collectstatic
app_1            | Traceback (most recent call last):
app_1            |   File "./manage.py", line 13, in <module>
app_1            |     execute_from_command_line(sys.argv)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
app_1            |     utility.execute()
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
app_1            |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
app_1            |     self.execute(*args, **cmd_options)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
app_1            |     output = self.handle(*args, **options)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
app_1            |     collected = self.collect()
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
app_1            |     for path, storage in finder.list(self.ignore_patterns):
app_1            |   File "/usr/local/lib/python3.8/site-packages/npm/finders.py", line 93, in list
app_1            |     self.cached_list = list(self._make_list_generator(ignore_patterns))
app_1            |   File "/usr/local/lib/python3.8/site-packages/npm/finders.py", line 100, in _make_list_generator
app_1            |     for path in get_files(storage, self.match_patterns, ignore_patterns):
app_1            |   File "/usr/local/lib/python3.8/site-packages/npm/finders.py", line 49, in get_files
app_1            |     directories, files = storage.listdir(location)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 315, in listdir
app_1            |     for entry in os.scandir(path):
app_1            | FileNotFoundError: [Errno 2] No such file or directory: '/app/node_modules'
concordia_app_1 exited with code 1
```

**Comment by acdha** [comment]
Can you try adding that value to a `.env` file in the concordia directory? What you're seeing sounds like it's failing to start due to the password and so it's just looping restarting a container which will always fail.

```bash
$ python3 -c "import secrets; print(f'POSTGRESQL_PW={secrets.token_hex(16)}')" >> .env
…
```

docker-compose will automatically load that file so you shouldn't need to do anything other than a full stop/start cycle.

**Comment by bkalish** [comment]
Thanks. I populated the .env file as you suggested. I still, however, get repeating errors I listed under "Additional notes".

**Comment by acdha** [comment]
It looks like `docker-compose` might need to confirm that the `npm install` step has been run at least once. The production Dockerfile does this but https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md#install-front-end implies this is just for front-end development but it has to be done to run the app meaningfully (otherwise I'd modify the static asset serving code to tolerate `node_modules` not existing)

**Comment by acdha** [comment]
Also the `npx gulp build` process is now mandatory, too.

**Comment by bkalish** [comment]
I tried `npm install` on my local machine in the `concordia` directory and it ran and populated `node_modules` but it did run into errors after awhile.  I'm not sure if these were important or not. `npx gulp` immediately fails with `Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (79)`. Should I have been running these commands in one of the containers? If so, which one?

**Comment by acdha** [comment]
It arguably should be running in the container — and since the container's Dockerfile hast this line, I'm not sure why it isn't:

```
RUN npm install --silent --global npm@latest && /usr/local/bin/npm install --silent && npx gulp build
```

Regarding running it locally, I'm using node 15.5.0, which is the current version in Homebrew. Normally I run it outside of the container when I'm working on CSS/JS where having Gulp auto-building every time you edit the file saves a lot of time.

**Comment by rabiloc** [comment]
@bkalish what is your pwd, when you run docker, i'm usually in the concordia folder, also, i'm in the shell(pipenv shell) when I run docker-compose up

**Comment by bkalish** [comment]
Thanks, @rabiloc.

It's been a while since I've run docker-compose, but I'm quite sure it has never asked me for a password.

I did at one time try adjusting some of the values in docker-compose.yml, including, if I recall correctly, some passwords. I was flailing in the dark there, though. The [Instructions for Developers](https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md) didn't indicate that such edits were necessary but I was feeling desperate.

Because there have been many changes to Concordia since I created this ticket and because I had made local customizations I tried a fresh install with a new clone back in March, though I wasn't successful in that attempt either: https://github.com/LibraryOfCongress/concordia/issues/1350

It does seem likely that some crucial information is missing from the [Instructions for Developers](https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md). I could easily imagine this is linked to passwords or environment variables, but I'm not a Python developer and I had never heard of Docker before encountering this project, so I'm afraid sorting it out on my own is beyond me.

**Comment by bkalish** [comment]
Solved! Many thanks to Ranjan for helping me track this down. The database password had not being set or was being set incorrectly. We were able to fix this by

1. entering the `concordia_db_1` container using `docker exec` (you can do this from the Docker dashboard without having to mess with container IDs)
2. launching the database frontend with `psql concordia concordia`
3. connecting to the concordia database `\c concordia`
4. changing the password with `ALTER ROLE concordia WITH PASSWORD 'concordia123';`

The semicolon in the last command is essential.

It would be lovely if the this were to scripted happen automatically or, at the least, if the documentation were updated to let folks know this step was necessary.

**Comment by bkalish** [comment]
I'm closing this ticket since it now amounts to a duplicate of #1350.

**Comment by acdha** [comment]
Having the password set in the `.env` file will cause this to happen but _only_ the first time the database container is created. I wonder whether we could make it fail outright if that file doesn't set `POSTGRESQL_PW`.

**Comment by bkalish** [comment]
That is good to know. We had assumed that deleting and recreating the Docker containers would be sufficient.

Having a clear failure in this instance does seem like it would be helpful. In addition, it seems to me that:

- It would be very helpful to have a script to clean the install, allowing folks to start fresh.
- The [For Developers](https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md) doc should be updated, since it instructs folks to run `docker-compose up` before setting any environment variables (via the `.env` file or otherwise).

I'll create issues for each of these.
