### ISSUE TITLE
Show date of activity in profile page contributions table

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1304]
**User story/persona**
As a user I want to know the actual date and time that I contributed to a page, rather than amount of time from contribution.

**Is your feature request related to a problem? Please describe.**
Currently the profile page contribution table "time" field lists the amount of time that has passed since an action happened. It should list the day and time of the action so that users do not have to calculate when the activity occurred. The column should also be relabeled "date".

**Additional context**
![image](https://user-images.githubusercontent.com/20258744/103031511-f8804c00-452b-11eb-8fc6-8a5f3f277104.png)

**Comment by acdha** [comment]
Currently that information is displayed as a tooltip over the date — this should probably have at least some responsive behaviour on large screens where there's plenty of room to display both.

**Comment by abshelton** [comment]
@rabiloc this looks great! Moving over to Done column.
