### ISSUE TITLE
Change default sort of profile page contributions to be by date

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1305]
**User story/persona**
As a volunteer, I want to use my profile page to visit assets I have recently worked on.

**Is your feature request related to a problem? Please describe.**
Because volunteers are most often using the contribution table to visit things they have recently worked on, the default sort of the contributions should be by date with the most recent activity appearing first, rather than by campaign, and then date, as is the current default.

**Additional context**
Screenshot:
![image](https://user-images.githubusercontent.com/20258744/103031967-e7840a80-452c-11eb-8614-e679979d2e02.png)

Because contributions are currently listed in campaign order, if they are listed instead by date it would be helpful to also add a way to navigate by campaign.

**Comment by abshelton** [comment]
@rabiloc, this looks great! Thanks.
