### ISSUE TITLE
Add ability to navigate profile page contributions by campaign

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1310]
**User story/persona**
As {a user}, I want to be able to find my contributions by campaign on my [profile page](https://crowd.loc.gov/account/profile/). I want to select the name of a campaign in the "My Contributions" table and have the contributions list filter to show only contributions to that campaign.

**Is your feature request related to a problem? Please describe.**
Currently only about a dozen contributions will fit on the profile page before it begins paginating.  Contributions are organized by campaign, but there is no way to know where to find contributions beyond the first page aside from clicking through the pages, which will grow quickly for regularly contributing users.

The contributions list by campaign at the top of the profile page includes a hyperlinked list of all campaigns a user has contributed. Those hyperlinks go to the campaign landing page. This is confusion. Most users intuit that clicking the name of the campaign will take you to their contributions from that campaign. 

To meet these user expectations the campaign name links should be changed to instead filter the contributions list. This can be accomplished with a checkbox next to each campaign, allowing users to select one or more campaign which will filter the list to show only actions associated with the selected campaigns. A select/deselect all box should also be included.

**Screenshot**
![image](https://user-images.githubusercontent.com/20258744/107815522-8107b580-6d41-11eb-9f4b-e0ba8e26b252.png)

**Testing Plan** 
As a registered volunteer on my profile page
WHEN I check a box next to a campaign under My Contributions
THEN I only see my contributions I made to that campaign

**Comment by lalgee** [comment]
Checkboxes -- woohoo!  @biswasrk It looks like when I use the checkboxes for filtering, it is only filtering the page of results that I'm on.  So if I uncheck some of the boxes, I no longer see any data, but there are still 107 pages of contributions.  If i navigate to one of those pages, all the boxes are checked again and I have to refilter.  What we'd like is for the filtering to update what is paginated so I'm still always seeing data on the first page but the number of pages goes down as there's less data to show based on filtering.
Additionally, we'd discussed a select/deselect all box.  Perhaps this could appear in the top row next to the "Campaign" column label.

**Comment by rabiloc** [comment]
@lalgee Good catch Lauren, I only had a few cases, guess I'll have to add some more transcriptions, so it pages and then figure out how to fix it :)

**Comment by elainekamlley** [comment]
Let's review the count action vs action column in pages worked on table. We should be make it clear to the users that the actions are saves and submits where as the table shows all the pages you worked on, not the count of actions performed on that page.

**Comment by lalgee** [comment]
@rabiloc Here are the changes we hope will make the difference between the table and list clearer for users:

- Change table column titles from "Transcribed" to "Saves & Submits" and "Reviewed" to "Reviews"
- Add a subheading above the list titled "Pages worked on"
- In the list headings change "Actions" to "Your Contributions"
- Move Actions/Your Contributions column to be between "Page number" and "Current Status"

**Comment by rabiloc** [comment]
@lalgee Sounds good I'll make those updates

**Comment by lalgee** [comment]
One other edit -- In the text under My Contributions change "actions" to "pages".

It also looks like the "Saves & Submits" column is now wider than the others.

**Comment by Igor-Ino** [comment]
@lalgee In order to test this ticket – I am puzzled by task of getting to My Contribution part, because I do not have any contributions yet. Is there any workaround? If there is one, please let me know. Thank you!

**Comment by lalgee** [comment]
@Igor-Ino emailing you info on how to log in as our test user accounts

**Comment by Igor-Ino** [comment]
@lalgee It looks like Acceptance Criteria, AKA Testing Plan have changed a little bit, because there are no more checkboxes and selected Campaign does not dismiss the other Campaigns, but rather gets gently bolded and open "Pages worked on" below the list of Campaigns. Also, the other requested changes in comments are looking good. 
The page looks great to me, though it is little bit different from the Testing Plan, which may be updated.
