### ISSUE TITLE
Users can only type one letter when an In Progress page is saved as "nothing to transcribe"

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1316]
**What behavior did you observe? Please describe the bug**
We occasionally recieve reports from users that they are on a page where they are only able to type one letter in the transcription box.  Upon investigation, this is because a page has been saved as "Nothing to transcribe" but not submitted. This should be changed to 1. Make it more obvious that the Nothing to transcribe box is checked (one good option would be changing the "Go ahead start typing" help text in the transcription box) and 2. Make it impossible to type in the transcription box at all.

**How can we reproduce the bug?**

1. Go to an unstarted asset.
2. Click "nothing to transcribe' and then 'Save'
3. Reload the page.
4. Try to type in the transcription box

**What is the expected behavior?**
If the "Nothing to transcribe" box is checked a user should not be able to type anything in the transcription box.

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/20258744/104631508-57883b00-566a-11eb-97b4-4372a34cb238.png)

**Desktop (please complete the following information):**
-   OS: Windows
-   Browser: Chrome and Firefox

**Additional context**
Additional changes to help make it more obvious that "Nothing to transcribe" is checked could include
- making the text or box more eye-catching when checked
- a pop up that alerts you that the box is checked if you try to type in the transcription box

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-39][(https://staff.loc.gov/tasks/browse/CONCD-39)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
