### ISSUE TITLE
AWS Cert renewal 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1325]
Research how to do DNS validation so that AWS renews automatically. May require ServiceNow ticket to validate all crowd environments.

**Comment by acdha** [comment]
I reissued it. We should update the deployment to get certificates for the appropriate tier using DNS validation so they'll automatically renew.

**Comment by jkueloc** [comment]
Submitted Service Now request - REQ0235027/RITM0238617

**Comment by jkueloc** [comment]
Update: The SN request above was approved and assigned to a person as a task on 2021-04-01

**Comment by jkueloc** [comment]
Update: Network Engineers are working with Chris to finalize this.  It should be added to CloudFlare and wrapped up soon.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-38](https://staff.loc.gov/tasks/browse/CONCD-38)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
