### ISSUE TITLE
Add service letter generator to profile page

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1334]
**User story/persona**
As a volunteer,, I want to be able to download a letter on LC letterhead confirming my contributions so that I can get school or other community service credit.

**Is your feature request related to a problem? Please describe.**
Currently Community Managers generate these letters manually using a Word document template. The requests for these have grown to a dozen or more a week. Sometime volunteers need these more than once throughout their semester or service period. It would make the process much more efficient to make these letters self-serve by populating and allowing users to download the letter via their profile page.

**Additional context**
Screenshot of the letter template (file also attached):
![image](https://user-images.githubusercontent.com/20258744/108727842-fa986400-74f6-11eb-9460-01394e0548cc.png)
[ServiceTrackingLetter_ConcordiaTemplate.docx](https://github.com/LibraryOfCongress/concordia/files/6022892/ServiceTrackingLetter_ConcordiaTemplate.docx)

**Acceptance Criteria**
A volunteer is able to visit their profile page and download or save a PDF letter autofilled with current information on their registration date, username, and transcription and review counts.

**Testing plan**
As a registered volunteer on my profile page
WHEN I click a hyperlink that says "Generate service letter" 
THEN a PDF downloads that include copy from the letter on loc letterhead, with my registration date, my user name and transcriptions and review counts

**Comment by lalgee** [comment]
The download is working perfectly @rabiloc ! So exciting!  

Tweaks listed below. Some updates are needed to the profile page to make it clear to users what it is and a edits to the letter itself. The biggest issue though is that the transcription and review counts in the letter are not matching those on the profile page.

**Text edits:**
- Italicize By the People (In 1st and 2nd to last sentence)
- Remove comma after Library of Congress in 1st sentence.
- Need apostrophe in “Library’s main website” (sentence 3)
- Add comma after “digital research” (sentence 3)
- Replace username with user's email address (we realized some volunteers might have usernames they don't want to share with their school or others)
- Add crowd@loc.gov on a line below Lauren Algee on signature

**Technical issues:**
- The transcription and review counts in the letter don’t match those in the contributions table.

**Profile page:**
- Add a header –Service Letter
- Using By the People to fulfill service requirements? Download a letter verifying your volunteer contributions. [Contact us with questions](link to contact page).
- Add “Download Letter” button in the style of change password button

**Comment by rabiloc** [comment]
@lalgee Changes have been made and applied to the test environment.

**Comment by rabiloc** [comment]
@lalgee Changes have been made and are ready to view in the test environment. I removed the inconsistencies in the space, let me know if you see any others.

**Comment by rabiloc** [comment]
@lalgee Changes applied to the test environment.

**Comment by Igor-Ino** [comment]
The Letter looks good in test and I am assuming the in the last paragraph after "as" should be name/email address of participant. 
However, I have a couple notes out this ticket's scope:
1. Testing Plan from Acceptance criteria still uses "Generate service letter" instead of Download Letter (it is fixed in comments)
2. The Letter is not optimized for printing, and needs shrinking to fit to the Letter Size, but not all printers have this option.
    It could be more convenient to have proper margins done before it is generated.
3. The PDF file does not pass the Accessibility test (multiple issues)

**Comment by lalgee** [comment]
Thanks @Igor-Ino!  The test accounts do not have emails assigned to them, so you're right that's what should appear in the letter.  Unfortunately we are unable to change this. Can you create new issues for the printing and accessibility issues?

Otherwise closing this ticket as completed.
