### ISSUE TITLE
Display review and transcription overall and campaign contribution totals on profile page

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1335]
**User story/persona**
As a volunteer, I want to know the total number of pages I have reviewed and transcribed.

**Is your feature request related to a problem? Please describe.**
The profile page currently displays information on individual actions as well as totals of actions by campaign.  It should also show a total number of actions. This count could display at the top of the list of actions by campaign.  It should also break down those campaign totals by reviews and transcriptions.

**Additional context**
![image](https://user-images.githubusercontent.com/20258744/108729582-b0b07d80-74f8-11eb-9c00-383b955bb0f9.png)

**Acceptance Criteria**
As a volunteer, when I visit my profile page, I see a count of my total actions and to know how many reviews and transcriptions I have contributed to each campaign.

**Comment by rabiloc** [comment]
Sounds good, I'll make those changes and push them in, in the next iteration.

**Comment by abshelton** [comment]
@rabiloc I probably wasn't super clear in my explanation above-sorry about that! I've attached an image of what I was thinking-so from what you have-we just want to move the TOTALS row below the "Campaign" header and then include the totals from the transcription and review columns in that row. (tried to draw that below!) 
![IMG_0297](https://user-images.githubusercontent.com/79859582/110694054-26ce0900-81b6-11eb-824e-ba46396e910f.jpg)

On the 1310 features, @lalgee can confirm-I think it's looking great but I think we would like to have a select/deselect all box at the top as well.

**Comment by rabiloc** [comment]
@abshelton Thanks for the clarification, Love the sketch :) Ok I will fix this ticket accordingly. The uncheck/check all button might be  a little trickier than I expected, but will give it a shot in the other ticket.

**Comment by rabiloc** [comment]
@abshelton Ok code updated and placed in testing. Let me know if the totals look good The uncheck/check button will be addressed in the other ticket. Thanks

**Comment by abshelton** [comment]
@rabiloc I'm glad you enjoyed my sketch...I try:) Two more minor tweaks and then I think we should be good.
1. Rename "TOTALS" to "All Campaigns." 
2. Convert all values in the "All Campaigns" row to bold text.

**Comment by rabiloc** [comment]
Ok updated the code.

**Comment by abshelton** [comment]
@rabiloc this looks great! thanks for going back and forth with us on this ticket:)
