### ISSUE TITLE
Rename contributor label on progress bars

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1336]
**User story/persona**
As a volunteer I need to accurately understand how other volunteers are contributing to campaigns.

**Is your feature request related to a problem? Please describe.**
This "contributors" count on campaign, topic, and project landing pages does not include anonymous contributors and should be edited to more accurately reflect how users are contributing by adding the word "registered" before "contributors"

**Additional context**
Screenshot of current contributor display:
![image](https://user-images.githubusercontent.com/20258744/108753518-da769e00-7512-11eb-80a0-d1b10e72f632.png)

**Acceptance Criteria**
Correct inaccurate language by changing contributor label above progress bar (on Campaign, Project, and Item pages) from "contributors" to "registered contributors".

**Comment by jkueloc** [comment]
@elainekamlley @lalgee this change is now in the dev and test environments if you'd like to take a look there.

**Comment by lalgee** [comment]
Looks good @jkueloc !  Thanks.
