### ISSUE TITLE
Research changing fields in transcription table export

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1343]
**User story/persona**
As a community manger, I need more useful fields in the transcription data export so that I can better understand and explore volunteer transcription and review activity.

**Is your feature request related to a problem? Please describe.**
Currently transcriptions csv/excel exports include several database identifiers rather than the fields that are used by the community managers.  This makes it difficult to utilize the data to look for patterns of user activity or to connect it to other sources of information. The export should be changed to include the username for the transcriber and reviewer rather than the database user id.  The export should also be changed to include the item id, sequence number, and url of the asset, in addition to the database asset identifier.

**Additional context**
Example current transcription export:
![image](https://user-images.githubusercontent.com/20258744/109046040-4f2c1280-76a2-11eb-9c46-0f263d942658.png)

**Comment by elainekamlley** [comment]
@jkueloc will do research on the data sources for both Asset and user. Users were anonymized due to the Kibana Report instance being public. 

Questions for technical evaluation: 
- Can we use the usernames for the export and anonymized for Kibana? 
-  If not, does the priority of putting Kibana behind centrify raise higher?

**Comment by jkueloc** [comment]
@elainekamlley The transcriptions csv/excel export is a direct export of the transcription table.  The requested data elements reside in the auth_user and concordia_asset tables.  At this point - based on the current norms in Concordia would this be more of a report vs. table export?  Or some sort of a hybrid extract/export with in the admin module.

**Comment by jkueloc** [comment]
SELECT "concordia_transcription"."id",
       "concordia_transcription"."asset_id",
       "concordia_transcription"."user_id",    --username
       "concordia_transcription"."created_on",
       "concordia_transcription"."updated_on",
       "concordia_transcription"."supersedes_id",
       "concordia_transcription"."submitted",
       "concordia_transcription"."accepted",
       "concordia_transcription"."rejected",
       "concordia_transcription"."reviewed_by_id",   --reviewer username
       "concordia_transcription"."text",
       "concordia_asset"."item_id",
       "concordia_asset"."sequence",
       "concordia_asset"."resource_url",
       "concordia_asset"."download_url",
       "auth_user"."username"
  FROM "concordia_transcription"
 INNER JOIN "concordia_asset"
    ON ("concordia_transcription"."asset_id" = "concordia_asset"."id")
 INNER JOIN "auth_user"
    ON ("concordia_transcription"."user_id" = "auth_user"."id")
 WHERE "concordia_transcription"."id" = 6140
