### ISSUE TITLE
Create view into review activity in Django admin

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1344]
**User story/persona**
As community manager, I want to be able to see and explore review activity.

**Is your feature request related to a problem? Please describe.**
Currently the Django admin does not provide any way to see review or explore review activity (accepts/rejects of transcriptions).  The closest thing is the transcriptions subdashboard, which can be filtered by "accepted" or "rejected". However, it does not display the username of the last accepter/rejector. Additionally, you can see all the transcriptions created by a user by clicking "transcriptions from that user's info page. However, there is no way to see their review activity.  Creating a review page and connections from users/campaigns would allow community managers to be able to explore and understand review activity.

Suggested changes:

- Create a Django page for review that is transcriptions filtered to those that have been accepted or rejected and can be filtered by campaigns and projects 
- On the review page, display the username of the person who rejected or accepted rather than the creator of the transcription
- Create a link from a user to the review page that will filter to just their accepts/rejects

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-37](https://staff.loc.gov/tasks/browse/CONCD-37)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
