### ISSUE TITLE
Research embedding information in exported campaign txt files metadata

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1359]
**User story/persona**
As a community manager, I want to know if it would be possible to embed the volunteer credit text in metadata fields of the .txt files within the bagit export of campaign transcriptions. 

**Is your feature request related to a problem? Please describe.**
Currently, the volunteer credit is added to the content of each transcription's .txt file as Concordia creates the bagit export. Community managers would like to switch to embedding this information in the file's metadata if possible to improve how the information is served to end users of the data in loc.gov.

**Additional context**
The export bagit function is accessed on an individual campaign's page in the Django admin interface. Screenshot below.
![image](https://user-images.githubusercontent.com/20258744/111514784-71a4cf00-8728-11eb-8ad6-3995e265e28c.png)

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-35](https://staff.loc.gov/tasks/browse/CONCD-35)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
