### ISSUE TITLE
Change volunteer credit text in exported .txt files to "contributors"

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1360]
**User story/persona**
The volunteer credit that is added in to the text of export .txt files during Bagit Export needs to be updated to swap "contributors" for "volunteers"

**Is your feature request related to a problem? Please describe.**
This change needs to be made to encompass all of the transcriptions being created in By the People, which are now made by staff as well as volunteers. This is particularly to meet the need of exporting the completed Patton diaries which were a campaign for teleworking staff launched during the 2020 pandemic.

**Additional context**
An example of the current credit in the screenshot below of an exported asset from the Rosa Parks Papers.  The file of this asset is also attached.
![image](https://user-images.githubusercontent.com/20258744/111627285-46bc8880-87c5-11eb-86de-c4b1c2190a01.png)
[0002.txt](https://github.com/LibraryOfCongress/concordia/files/6164092/0002.txt)

**Acceptance Criteria**
When I export a campaign as a BagIt file, each of the .txt files within have the credit "Transcribed and reviewed by contributors participating in the By The People project at crowd.loc.gov." appended to the end of the transcription in the file.

**Acceptance Test:**
1. Go to Campaigns page in Django admin - https://crowd.loc.gov/admin/concordia/campaign/
2. Filter to only published campaigns
3. Click on a campaign title
4. Select Export BagIt from the grey buttons at the top of the screen
5. Zip file should download
6. Unzip file
7. Open the mss folder and then drill down to the deepest directory which will contain a series of numbered .txt files
8. Open one of the text files and check that the text at the end of the file reads: Transcribed and reviewed by contributors participating in the By The People project at crowd.loc.gov.

.

**Comment by jkueloc** [comment]
@elainekamlley @lalgee this change is now in dev and test if you would like to take a look there.

**Comment by jkueloc** [comment]
@lalgee My apologies. I misspoke about test ... it should be there now.  Please take another look at test. Thank you!

**Comment by lalgee** [comment]
Looks good in test now too - thanks!
