### ISSUE TITLE
Investigate and fix errors when editing Item Name

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1376]
Errors when updating Copyright description campaigns either times out or raises 400 error. 

Error raised: `Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE`. Community managers to add list of items to investigate. Try and replicate the issue.

**Comment by abshelton** [comment]
List of Items from Early Copyright campaign
[EarlyCopyright_ProblemItems.xlsx](https://github.com/LibraryOfCongress/concordia/files/6259606/EarlyCopyright_ProblemItems.xlsx)

**Comment by rabiloc** [comment]
@lalgee @abshelton What are the list of title text that you want updated for the items in the excel sheet. I can write a script to update those via the database

**Comment by abshelton** [comment]
@rabiloc here is the list w/the correct titles listed in the "New Titles" column. Let me know if you need any other info! 

[EarlyCopyright_ItemsTitles.xlsx](https://github.com/LibraryOfCongress/concordia/files/6772598/EarlyCopyright_ItemsTitles.xlsx)

**Comment by lalgee** [comment]
@rabiloc Something I forgot to mention yesterday, is that we're still waiting on the Division to approve the staging site, so we haven't moved the content to production yet. That should happen before the end of the month, so it should be ready for you to make the change there in early August.

**Comment by rabiloc** [comment]
@lalgee Sounds good, we will just run the scripts on the staging environment now, and we will get to production in August then.

**Comment by abshelton** [comment]
@rabiloc-here is the original import spreadsheet. The only title information that we determine in the bulk import process is the campaign and project titles. The item titles come from the loc.gov URLs. [titlepagestageimport.xlsx](https://github.com/LibraryOfCongress/concordia/files/6778901/titlepagestageimport.xlsx)

**Comment by rabiloc** [comment]
@abshelton Ok Jen updated the database with the excel texts, can you please check if it looks good in staging?

**Comment by abshelton** [comment]
@rabiloc looks good in stage!

**Comment by abshelton** [comment]
Early Copyright Title Pages is now in production-can we change all of the items titles per the process done in stage? And updated spreadsheet with all of the item URLs and titles is below. Thanks! 

[titlepage_ItemTitles.xlsx](https://github.com/LibraryOfCongress/concordia/files/6878216/titlepage_ItemTitles.xlsx)

**Comment by rabiloc** [comment]
@jkueloc Can you please update the prod database using the bastion host, we followed the excel sheet values.

**Comment by jkueloc** [comment]
@rabiloc @abshelton @lalgee @elainekamlley 
Done!

**Comment by abshelton** [comment]
@jkueloc it looks like only a few of the item titles updated instead of all per the new spreadsheet? I think I forgot to clarify this yesterday but in prod we'll need to change all of the item titles for Early Copyright (using the same method as in stage) rather than just a handful. Do you mind updating them all? Thanks!

[titlepage_ItemTitles.xlsx](https://github.com/LibraryOfCongress/concordia/files/6885210/titlepage_ItemTitles.xlsx)

**Comment by jkueloc** [comment]
@abshelton Hi Abby - please take a look at the second update I made to production and let me know if it's ok.

**Comment by abshelton** [comment]
@jkueloc looks great now! Thanks for making the update. I'll close out the ticket.
