### ISSUE TITLE
Review and clean up gardening & coding standard tickets

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1398]
There are tickets created a year or two ago for application clean up and maintenance. Take a look at tickets labeled gardening/coding standard and delete or clean up tickets that are outdated. 

Link to issues in backlog: https://github.com/LibraryOfCongress/concordia/issues?q=is%3Aopen+is%3Aissue+label%3Agardening

**Comment by jkueloc** [comment]
1. Automate routine cleanup tasks #1182  - is still valid.
2. Consider doing direct-to-cloudwatch login event logging #1118 - ?  Would doing the first box duplicate anything that info sec intends to capture with splunk log forwarding against the database? They other two boxes are still waiting for weigh in from Elaine and Lauren
3. Improve test coverage for site report task gardening #1109 - ?
4. Dedupe code in site_report task coding_standard gardening #1108 - ...
