### ISSUE TITLE
Banner on homepage encouraging users to fill out June user survey

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1407]
**User story/persona**
Community managers want to encourage users on the site to participate in a user survey, expected to launch at in July 2021. A banner on the BTP homepage needs to communicate brief info about the survey and link to the survey.

**Additional context**
Banners have previously been used on the site to encourage users to try the Activity Prototype (in summer 2019) and code can possibly be reused - https://github.com/LibraryOfCongress/concordia/issues/1205

**Acceptance Criteria**
1. Banner needs to appear at top of homepage.
2. Banner needs to contain filler copy (see below). Eventually we will provide a live link to a Survey Monkey module which should also go in the banner.
3. Copy: Let us know what motivates you! Take a short survey to help us improve our program: INSERT LINK

**Acceptance Test:**
1. Visit By the People homepage. 
2. Ensure that banner appears in the proper position on page. 
3. Verify that copy within banner is accurate. 
4. Click on link and verify that link leads to SurveyMonkey survey.

**Comment by rabiloc** [comment]
@lalgee What is the url of the link?

**Comment by abshelton** [comment]
@rabiloc this isn't the final link but we can use it for testing: https://www.research.net/r/btp-volunteer-survey

**Comment by rabiloc** [comment]
@abshelton Thanks.

**Comment by abshelton** [comment]
@rabiloc and just to confirm, we don't anticipate releasing the banner on the prod site until July. I think it will likely be the second week of the month.

**Comment by rabiloc** [comment]
@abshelton I'll just put the changes to the dev/test environment when complete, and update it later with the actual banner link

**Comment by rabiloc** [comment]
Changes are in place, just need to update code with the final survey URL.

**Comment by lalgee** [comment]
BTP team just waiting on final approval to know if we need to change out URL - should know this week.

**Comment by abshelton** [comment]
@rabiloc We plan to use the same URL but would like to make a little tweak to the language. New copy: "Let us know what motivates you to volunteer! Take a short survey to help us improve our program: https://www.research.net/r/btp-volunteer-survey" 

Once we make that change, we can deploy the banner to production tomorrow in the "off" position. I want to make sure we have the chance to send the survey out via email before it goes live on the site-but CMs should be able to turn it "on" in prod once the functionality is there, right?

**Comment by rabiloc** [comment]
Sounds good @abshelton I'll make those changes and have it ready tomorrow in the test environment. If it looks good, we can push to production shortly.

**Comment by rabiloc** [comment]
@abshelton Ok changes made, can you please see if it looks good in test and staging?

**Comment by abshelton** [comment]
@rabiloc it looks great in test and staging! you're free to deploy to production in the "off" state. we'll turn it on later this afternoon. thanks!

**Comment by rabiloc** [comment]
@abshelton Done! Moved it to production and set flag to false.
