### ISSUE TITLE
Comply with LOC security directives

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#141]
- [x] Lock out user account for 15 minutes after 3 unsuccessful login attempts - #217 
- [x] Display standard warning banner at login (for SSH access to machines) - AC‌-08
- [x] Write rationale for allowing anonymous users to transcribe - AC‌-14
- [x] All contractors must take security training
- [x] Incorrect logins do not reveal specific cause of auth failure - IA‌-06
- [x] Information system inventory list - CM‌-08
- [ ] Admins need to sign a hard copy form - PL‌-04

**Comment by rstorey** [comment]
As of #573 these are all done except the hard copy form for admins.

**Comment by acdha** [comment]
I've already signed one of those. Let's ping Barry tomorrow about getting one for you.

**Comment by rstorey** [comment]
I chatted with Barry about this and the form is being developed. I propose we close this because we have no control over when I'll be able to get the new form and get it signed.

**Comment by elainekamlley** [comment]
Lets do it! Want to do the honors @rstorey?
