### ISSUE TITLE
Research and Upgrade AWS Elastic Search version from 6.7 to 6.8

### ISSUE THREAD

**Issue by jkueloc** [LibraryOfCongress/concordia#1412]
Research steps to Upgrade AWS Elastic Search version from 6.7 to 6.8
Upgrade AWS Elastic Search version from 6.7 to 6.8

- dev
- test
- stage
- prod

**Comment by jkueloc** [comment]
@elainekamlley @rabiloc Please weigh in on the matter below.

A 6.7 to 6.8 upgrade doesn't present any inherent issues per the release notes https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html. 

Generally, for an upgrade, there is a recommendation for for taking a manual snapshot in the event something goes wrong and you want to restore it yourself. Otherwise, AWS automatically take a pre-upgrade snapshot and should you need to restore (issues with upgrade) you would simply contact AWS Support for help with that.

Currently, the infrastructure for manually taking an AWS ElasticSearch snapshot is not configured for Concordia/Crowd. Requires S3 bucket, IAM permissions and roles, registering a repository, etc. Dev time and AWS costs would be incurred.

The risk for an upgrade from 6.x to 6.x seems low enough that depending on AWS support would be enough of an insurance policy.

**Comment by rabiloc** [comment]
@jkueloc Is there any other environments that you plan to upgrade first, like test or stage? Doesn't seem like any issues from 6.x to 6.x

**Comment by lalgee** [comment]
@Igor-Ino can you do the frontend regression testing for this?  I'll look for a time in our schedules where we can go through backend regression testing together.

**Comment by Igor-Ino** [comment]
Regression testing of front end is complete, looks good.

**Comment by jkueloc** [comment]
@lalgee Elastic Search in stage has been upgraded to 6.8.   
Please let me know when it's ok to upgrade production. 
Since it's internal facing, I just need 30 - 60 minutes when no one has a pressing need to use it.

**Comment by lalgee** [comment]
Admin Functionality

- [ ] Manage users
- [ ] Search for a user and use filter criteria
- [ ] Activate a user's account
- [ ] Manage assets
- [ ] Search for an asset and use filter critera
- [ ] Reopen a completed asset
- [ ] Look at an asset's detail page
- [ ] Navigate to an asset's transcriptions
- [ ] Unpublish an asset
- [ ] Manage transcriptions
- [ ] Filter transcriptions by campaign and by project
- [ ] Export a selection transcriptions to CSV
- [ ] Site reports
- [ ] Export a CSV of report for the last 100 days (filter by created on date and select all on the page)
- [ ] Confirm that the report contains data for all campaigns and topics
- [ ] Simple pages
- [ ] Make a text edit to the About page
- [ ] Carousel
- [ ] Edit and publish a carousel slide
- [ ] Import
- [ ] Import test item using bulk importer CSV upload
- [ ] RegTestImport_Lincoln - Bulk import test spreadsheet (2 Knox College Lincoln items not in BTP production database) 
- [ ] Check the import status using Import Progress
- [ ] Check that import is successful by finding the new unpublished item and assets

**Comment by Igor-Ino** [comment]
Tested front end in stage, no issues found.
Will do back end in test later on.

**Comment by Igor-Ino** [comment]
@lalgee I tested everything except last 4 items (and they look good.) 
I need to go through them with you once again.

**Comment by Igor-Ino** [comment]
Backend testing is complete, no issues found.

**Comment by jkueloc** [comment]
@lalgee There is actually still a read timeout issue on the periodic process that causes the process to abend (stop, not complete) that I need to resolve before I can upgrade the production environment version. Since some or one oversight folk is looking at the data in production - I want to solve this problem first so the data fully loads nightly once the version is updated in production.

**Comment by lalgee** [comment]
That makes sense @jkueloc . Not a problem to wait.

**Comment by jkueloc** [comment]
Production was upgraded from 6.7 to 6.8 this morning

**Comment by jkueloc** [comment]
The read timeout and occasional abends have NOT been occurring in production.
