### ISSUE TITLE
In admin dashboard searching transcriptions times out

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1413]
Due to the quantity of transcriptions in the application when a community manager searches keywords or names, it takes a long time for search results to return, often timing out. Need a solution to handle searching in admin as the amount of data increases. 

How to replicate
1. In the search field enter a keyword or name and hit return. Takes a long time for search results often timing out. 
2. Filtering down by campaign/project help but there is a use case for searching across all campaigns and projects.

**Comment by acdha** [comment]
This might be a good time to enable Postgres's full-text search, which Django has full support for. That should be faster for these types of queries and would also provide natural language processing (e.g. searching for "trilogy" would also match documents with "trilogies").

**Comment by jkueloc** [comment]
https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/search/

**Comment by jkueloc** [comment]
Moved to Jira: [https://staff.loc.gov/tasks/browse/CONCD-34](https://staff.loc.gov/tasks/browse/[CONCD-34](https://staff.loc.gov/tasks/browse/CONCD-34))

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
