### ISSUE TITLE
Asset appears as both In Progress and Completed

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1433]
**What behavior did you observe? Please describe the bug**
Asset [mss119730261-87](https://crowd.loc.gov/campaigns/clara-barton-angel-of-the-battlefield/general-correspondence/mss119730261/mss119730261-87/) appears on the public website as Completed but in the backend and database is "In Progress"

**How can we reproduce the bug?**

To see the item presented as Complete to the public
1. Go to https://crowd.loc.gov/campaigns/clara-barton-angel-of-the-battlefield/general-correspondence/mss119730261/mss119730261-87/

To see the item as In Progress
1. Log in with an Admin account
2. Go to https://crowd.loc.gov/admin/concordia/asset/?q=mss119730261-87

**What is the expected behavior?**
An asset's status should be the same no matter where it is being viewed.

**Got screenshots? This helps us identify the issue**
![image](https://user-images.githubusercontent.com/20258744/117682150-c5f48a00-b180-11eb-9083-b3b31f7ba419.png)

![image](https://user-images.githubusercontent.com/20258744/117682229-d86ec380-b180-11eb-8d7f-31fca435d2dc.png)

**Additional context**
The asset's transcription history looks normal.  Community managers have tried "reopening" the asset and tombstoning existing asset transcription reservations with no results.

A campaign cannot be exported until all assets are complete.  This is not currently an issue as there are not current plans to export the Barton campaign, but will be eventually if this problem is not addressed.

If no other resolution can be found, we can always delete and reimport the item.

**Comment by rabiloc** [comment]
@lalgee I may have found a fix to this issue, we will run the script in the test environment, if test looks good, we can run it in the prod environment later on. The idea is to set the accepted value to NULL for this asset, it was set to accepted at some point, and the system thinks its completed, although it was rejected later on.

**Comment by Igor-Ino** [comment]
Tested, looks good. BTW it looks good in prod as well.
