### ISSUE TITLE
Design image placement and styling for How-to pages. 

### ISSUE THREAD

**Issue by abshelton** [LibraryOfCongress/concordia#1446]
**User story/persona**
As a volunteer, I want to see images in the "How-to" guides so that I can better understand the instructions for transcription and review. 

**Is your feature request related to a problem? Please describe.**
Our volunteers have long requested that we improve the How-to pages to help with the onboarding process. This is one way that we can demonstrate how to transcribe certain types of materials in a way that will appeal to different types of learners. 

The instruction pages are "simple pages", styled with basic html via the Django admin. Community managers now have AWS access to upload image files, but need to know how to insert them in the html in a way that meets LC design and accessibility standards.

**Additional context**
This ticket relates to the design of these images and how they will fit on the page. Images we have selected are included below with suggested captions, alt text, and page placement instructions. 

NOTE: These images may need to be updated or additional images added later. It's hoped that design recommendations would potentially also apply to other By the People simple pages if we determine those need illustration down the road.

On the "How to Transcribe page (https://crowd.loc.gov/help-center/how-to-transcribe/): 
1. In "Text Order" section: remove hyperlink in third paragraph ("written text in two directions") and insert this image near that paragraph, with the caption: An example of cross-writing from "The Blackwells: An Extraordinary Family" Campaign. Alt text: A close-up of a a transcription window featuring a handwritten letter on the left side and transcription box on the right side. 
![CrosswritingExample](https://user-images.githubusercontent.com/79859582/118841688-84f22900-b896-11eb-8611-9af6f9a5f252.png)

2. In "Insertions" section: add the following image and caption: Transcribe inserted text as you would read it-seen here in an example from the Anna Dickinson papers. Alt text: A cropped detail of a few lines in a handwritten letter on the leftside and the transcription on the right side. 
![Insertion_example](https://user-images.githubusercontent.com/79859582/118842495-427d1c00-b897-11eb-93bf-c6d09175cd73.jpg)

3. In "Deletions" section: add image and caption: A close-up of some deleted text in one of Walt Whitman's notebooks with the appropriate transcription. Alt text: A cropped detail of a line of handwritten text on the leftside and the transcription on the right side. 
![Deletions_example](https://user-images.githubusercontent.com/79859582/118843516-229a2800-b898-11eb-8897-485a782a80f7.jpg)

4. In "Marginalia" section: add image and caption: Marginalia found in the Abraham Lincoln papers. Alt text: On the left side of the image a printed page from a book with notes handwritten in pencil in the margin and on the right side of the image, the transcription for the page. 
![Marginalia_example](https://user-images.githubusercontent.com/79859582/118843976-90deea80-b898-11eb-84dc-bbda82e1a528.jpg)

5. In "Long s/funny f" section: add image and caption: This page from the Herencia Campaign features many "long s" characters! Alt text: A close up of a printed page in Spanish on the leftside of the image and a transcription box on the right side. 
![LongS_example](https://user-images.githubusercontent.com/79859582/118855494-cfc66d80-b8a3-11eb-9c8f-cf4f2958a578.jpg)

On the Review page (https://crowd.loc.gov/help-center/how-to-review/)

1. In "Find a page to review" section: add this image and caption: A Campaign page showing where to find the filters to access pages that need review. Alt text: A screenshot of a Campaign page with a large orange box around the filtering feature. 

![Review_example](https://user-images.githubusercontent.com/79859582/118844403-ee733700-b898-11eb-82fe-3e0e1436712a.jpg)

 
**Acceptance Criteria**
Any needed changes to the code to accommodate images has been made and community managers have recommendations for best practice to insert and style images from the admin module.

**Acceptance Test:**
1. Community Managers approve design.
2. Design meets accessibility standards.

**Comment by lalgee** [comment]
@klee72 pulling this into next sprint if you have time for it.  Happy to provide additional context as needed.

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
