### ISSUE TITLE
Fix CSS validation errors

### ISSUE THREAD

**Issue by klee72** [LibraryOfCongress/concordia#1456]
**What behavior did you observe? Please describe the bug**
Fix CSS validation errors reported by https://travis-ci.org/github/LibraryOfCongress/concordia/jobs/772524448

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-30](https://staff.loc.gov/tasks/browse/CONCD-30)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
