### ISSUE TITLE
Research Project-level BagIt Export

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1462]
**User story/persona**
As a community manager, I want to be able to export BagIts of transcriptions for all completed items from specific projects, rather than all completed items in a campaign, so that data can be processed for publication on loc.gov.

**Is your feature request related to a problem? Please describe.**
Project-level exports would allow us to export substantial, logically cohesive groups of items as campaigns progress, rather than having to wait for entire campaigns to complete.

**Additional context**
Admin module needs:
- Assuming that like the current BagIt export, it would only export completed items (just only from specific projects), so it would be up to CMs to confirm all items in a project are complete before we export.
- Ability to select multiple projects within a campaign and export just those (whether complete or not). Could be use the project dashboard as the interface with an export Action in the dropdown. Would behave similarly to existing functions that execute based on checkbox selection and dropdown. We could filter the project list by campaign, then just select the projects we want to export from the full list, and from the drop down select “Export BagIt”.
(screenshot of project dashboard below)
![image](https://user-images.githubusercontent.com/20258744/120660332-36778980-c455-11eb-9702-6f6ebf302cb6.png)

Bag-It requirements:
- Need to export multiple projects in one bag rather than having to export a bag for each project, as we would then have to manually merge those to have a structure that mimics that structure of the images for ETL.  
- The BagIt structure should remain the same as the campaign export.
- Do not write project name(s) anywhere into the BagIt text files because these are deleted before receiving/copying to storage. Because DCM is creating the concatenated text files, this reprocessing breaks the BagIt and a new BagIt is created when the copied is received to CTS and copied to long term storage. 
- Do not include project name in a nested directory structure in the exported bag because then it would not match the image naming structure.
- Like the existing BagIt export, completed blank assets (where Nothing to transcribe was selected) should not be exported.

More details available on Confluence:  https://staff.loc.gov/wikis/display/CS/Project-level+export

**Acceptance Criteria**
Investigate the technical difficulty and options for exporting selected projects in the BagIt format and how the UI for the feature could work in the Django admin.

**Acceptance Test:**
- [ ] Investigate technical difficulty of pulling only specific project data into BagIt
- [ ] Determine if project dashboard can serve as UI (if not, what are alternatives)
- [ ] Ticket and assign to sprint

**Comment by laurenseroka** [comment]
Tested the change in test, and content is now exporting as expected

**Comment by rabiloc** [comment]
Provide users the ability to check multiple projects in a campaign, once selected, allow users to submit their picks to export BagIt Structure to their machine. On submission, the code will create a similar folder structure as before, however, only the items that are related to the projects checked will be downloaded. If a project contains items with assets that are complete, it will be downloaded, if not, it will skip.

**Comment by laurenseroka** [comment]
Confirmed with Lauren A. that Concordia can till export a project even if some items may not be complete (vs. only being able to export when a project is entirely complete)

**Comment by rabiloc** [comment]
@laurenseroka Thanks for confirming. I think we should be all good with the research on this ticket.

**Comment by lalgee** [comment]
@rabiloc to ticket the solution

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-29](https://staff.loc.gov/tasks/browse/CONCD-29)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
