### ISSUE TITLE
For Developers Doc leaves out environment variables until too late

### ISSUE THREAD

**Issue by bkalish** [LibraryOfCongress/concordia#1471]
The [For Developers](https://github.com/LibraryOfCongress/concordia/blob/master/docs/for-developers.md) document instructs folks to run `docker-compose up` before setting any environment variables, but `POSTGRESQL_PW` must be set before the first run to prevent a failed build. The instructions should introduce all required environment variables and provide instructions for setting them *before* they are needed.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-28](https://staff.loc.gov/tasks/browse/CONCD-28)

**Comment by jkueloc** [comment]
Closed with [Release v0.6.29](https://github.com/LibraryOfCongress/concordia/releases/tag/v0.6.29)
