### ISSUE TITLE
Provide a "clean" script

### ISSUE THREAD

**Issue by bkalish** [LibraryOfCongress/concordia#1472]
**User story/persona**
As a someone installing Concordia, I want to be able to clean my system so that I can do a fresh install if anything goes wrong

**Is your feature request related to a problem? Please describe.**
If `docker-compose up` is run before  setting the appropriate environment variables you end up with a broken installation. Destroying the Docker containers, setting the variables, and running `docker-compose up` again is *not* sufficient to get a working install. Since whatever is necessary to start fresh is not obvious, it would be helpful to have a script for this purpose.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-27](https://staff.loc.gov/tasks/browse/CONCD-27)

**Comment by jkueloc** [comment]
Documentation was updated via [CONCD-28](https://staff.loc.gov/tasks/browse/CONCD-28)
