### ISSUE TITLE
Last part of breadcrumbs shows low contrast

### ISSUE THREAD

**Issue by Igor-Ino** [LibraryOfCongress/concordia#1473]
**What behavior did you observe? Please describe the bug**
When I am testing pages, the last item in breadcrumbs shows low contrast
**How can we reproduce the bug?**

1. Go to 'https://crowd.loc.gov'
2. Click on 'jump into a transcription'
3. See page; https://crowd.loc.gov/campaigns/walt-whitman/notebooks-and-diaries/mss1863001198/mss1863001198-3/
4. See error: last part of the breadcrumb **/mss1863001198-3** is in grey, which is very low contrast

**What is the expected behavior?**
Last part of breadcrumb is normal or high contrast

<img width="691" alt="Screen Shot 2021-06-08 at 15 56 29" src="https://user-images.githubusercontent.com/80710853/121249064-29520480-c872-11eb-9a9c-c8406889019e.png">

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by klee72** [comment]
@Igor-Ino: I updated the active text color. Please take a look in dev/test.

**Comment by Igor-Ino** [comment]
@klee72 No change in stage or prod, but works well in test. 

However, red highlight color (it was changed?) if left side menu is very low contrast:
<a class="nav-link active" href="/help-center/how-to-transcribe/" style="color: rgb(240, 81, 41); background-color: rgb(255, 255, 255);">
How to transcribe
</a>
<img width="587" alt="Screen Shot 2021-09-29 at 15 17 30" src="https://user-images.githubusercontent.com/80710853/135334312-56c377af-e235-4a5b-9d2b-ef451736d422.png">

Would you like me to open a new ticket for this?

**Comment by klee72** [comment]
@Igor-Ino Yes please open a new ticket for help pages and I'll take care of it. Thanks!

**Comment by Igor-Ino** [comment]
This ticket looks good.
For help pages opened ticket 
Accessibility issue with help pages. #1551
