### ISSUE TITLE
docker-compose up should fail if POSTGRESQL_PW is not set

### ISSUE THREAD

**Issue by bkalish** [LibraryOfCongress/concordia#1474]
**What behavior did you observe? Please describe the bug**
If you run `docker-compose up` without first setting the `POSTGRESQL_PW` environment variable you get a failed install. Ideally `docker-compose up` would fail immediately in this case with a clear error message without creating any containers.

**How can we reproduce the bug?**
Download Concordia from GitHub.
Run `docker-compose up` in an environment where `POSTGRESQL_PW` has not been set.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-26](https://staff.loc.gov/tasks/browse/CONCD-26)
