### ISSUE TITLE
Public status pages and health checks

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#149]
When the site goes down, whether intentionally or unintentionally, there should be a static page hosted in an S3 bucket that indicates the site is down.

There should also be a public status page so the community knows whether everything is functioning as expected or whether there are known issues.

~~In order to create a public status page, we need to create application health check(s).~~

~~The current maintenance mode feature needs to be refactored to use S3 or RDS or some central service (other than local file storage) that will scale horizontally in an ECS cluster. See #227.~~

~~Add links in the Django admin to enable / disable maintenance mode and display the maintenance mode state in the admin site.~~

~~The ECS launch configuration should be reviewed for capacity and health check endpoints added.~~

**Comment by rstorey** [comment]
Some info that we could show on public status page:
* Items in the queue
* Items processed
* Number of task instances
* load average
* Status of RDS via CloudWatch API

**Comment by acdha** [comment]
The release of django-maintenance-mode 0.12 last month adds pluggable backend support: https://github.com/fabiocaccamo/django-maintenance-mode#configuration-optional

That should make it easy to add a backend using the Django cache framework. There's also support now for ignoring the admin site which would make the thought about adding links in there to the existing enable / disable API endpoints usable as admin actions.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-67](https://staff.loc.gov/tasks/browse/CONCD-67)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
