### ISSUE TITLE
rename default Concordia branch to "main"

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1490]
**User story/persona**
As a product lead, I want to ensure we are welcoming to our team, LC collaborators, and potential external adopters by removing outdated and offensive language from our repo. To that end we should rename the default branch from "master" to "main"

**Additional context**
Github guidance is here: https://github.com/github/renaming
There are lots of other detailed guides online as well from other sources.

**Acceptance Criteria**
The default branch of the Concordia github repo is renamed to "main"

**Acceptance Test:**
1. Go to the Concordia repo homepage - https://github.com/LibraryOfCongress/concordia
2. Look at the branch dropdown menu
3. Confirm that the default branch is now listed as "main"

**Comment by jkueloc** [comment]
@elainekamlley @lalgee @rabiloc 
Done, with pleasure.

Please note the steps below to update your local clone:

![Screen Shot 2021-08-30 at 7 08 29 AM](https://user-images.githubusercontent.com/72825410/131330528-8d60d613-1681-4300-b6a7-a03297122a76.png)

**Comment by jkueloc** [comment]
@elainekamlley @lalgee  @rabiloc I updated the Jenkins dev build job to look for main vs. master this morning.
