### ISSUE TITLE
Concatenate transcriptions for every asset in an item in BagIt export

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1494]
**User story/persona**
As the DCM By the People liason, I need a transcription TXT file for each item which concatenates together all of the individual asset transcriptions in each item in a TXT file that is included in the campaign BagIt export and is named and structured according to the needs of the loc.gov publishing process.

**Is your feature request related to a problem? Please describe.**
Item-level concatenated TXT files are part of the By the People data published on loc.gov

Item-level TXT files are not currently included in the campaign BagIt export, to prepare a campaign for loc.gov, the DCM liason currently has to unBag the transcriptions after export, run a script to create the item-level concatenation, and then reBag all of the content. It would make this work much more efficient if the BagIt Export already included the item-level transcription. 

When we select Export BagIt in Concordia's Django admin module, a concatenated file for each item exports in the same BagIt alongside the individual, asset-level text files. 

**Additional context**
Example of an item-level transcription in the correct BagIt structure from Rosa Parks is highlighted below: 
![image](https://user-images.githubusercontent.com/20258744/124315144-7fe4f280-db41-11eb-90f4-648ea341fa0d.png)

Example from Rosa Parks highlighted -- Notice that there are multiple concatenated, item-level files in this directory. This is because the images were scanned from microfilm and are stored in a structure that matches the original microfilm. There are sometimes many items within 1 reel of microfilm. Sometimes an item will cross multiple microfilm reels, such as the example highlighted in yellow. Place the concatenated file in the reel directory where the first page is located.
![image](https://user-images.githubusercontent.com/20258744/124315355-d18d7d00-db41-11eb-81f5-f4cd3dd82b7b.png)

**Acceptance Criteria**
- A concatenated, item-level text file is created for each item included in the BagIt export.
- The attribution text is added at the bottom of each item-level text file.
- Name the concatenated, item-level text file the item's resource_id
- Place the concatenated, item-level text file in the same directory as the first individual, asset-level text file for an item
- NOTE:  Sometimes the original images were scanned from microfilm and the scans are stored in a structure that matches the original microfilm. If this is the case, there can be more than 1 item in a directory. 
- NOTE:  Sometimes an item might span more than 1 reel, so all of the individual text files for an item might not be in the same directory. 

**Acceptance Test:**
1. Go to a the campaign Susan B. Anthony Papers
2. Click Export BagIt 
3. Confirm .zip downloads
4. Unzip file
5. Check directory structure to make sure: 
- A concatenated, item-level text file is created for each item included in the BagIt export.
- The attribution text is added at the bottom of each item-level text file.
- Each concatenated, item-level text file is named according to that item's resource_id
- The concatenated, item-level text file is in the same directory as the first individual, asset-level text file for an item.

**Comment by elainekamlley** [comment]
@rabiloc could you document some of the root causes of this? How would could we best understand the scope of all the timeout issue? It seems that these are becoming more frequent and would like to plan on how to address this.

**Comment by rabiloc** [comment]
@elainekamlley This isn't in production, I have only deployed it to my local machine. For this task, there is a lot of processing that will time out for bigger campaigns if we deploy it.
