### ISSUE TITLE
Make overlay banner editable through Django admin

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1498]
**User story/persona**
As a community manager, I want to be able to change the text and/or link of the homepage announcement banner via the Django admin.

**Is your feature request related to a problem? Please describe.**
Several times, there has been a need to publish a banner on the homepage to link to a external site, such as the activity prototype or a user survey. Community managers would like to continue to use the banner functionality more often and without requiring developer assistance.

The same code has been used and the banner can be turned on/off using the flag state "ADVERTISE_ACTIVITY_UI". However, community managers cannot change the message of the banner. A developer must go into the code to change the text and link, submit as a pull request, test, and then wait for a release for it to go live. 

Making the banner editable by community managers in the Django backend would free up developer time for more appropriate work.  Additionally, it would allow CM's to deploy the banner more quickly and more often, for example to let users know about bugs or planned outages.

**Additional context**
In addition to creating edit functionality in Django, if the banner becomes a real Concordia feature, some design work may be needed and the flag state should likely be renamed. These would be additional tickets.

**Acceptance Criteria**
Community managers can edit the homepage banner text and link(s) in the Django admin interface.

**Acceptance Test:**
1. Log in to the Concordia admin interface
2. Change the message and hyperlink in the banner
3. Publish the banner by changing ADVERTISE_ACTIVITY_UI expected value to TRUE
4. Go to the homepage
5. Confirm that text has changed
6. Confirm that hyperlink works correctly
7. Unpublish the banner by changing the expected value to FALSE
8. Go to the homepage
9. Confirm that banner is no longer displayed

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-23](https://staff.loc.gov/tasks/browse/CONCD-23)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
