### ISSUE TITLE
db ops containers - S3 sync - 24 objects - An error occurred (AccessDenied) when calling the GetObjectTagging operation: Access Denied

### ISSUE THREAD

**Issue by jkueloc** [LibraryOfCongress/concordia#1510]
Beginning with the Monday 7/26/2021 dev and test restore processes the S3 content sync started failing on 24 specific s3 objects from the early copyright campaign import.  

The campaign was still being imported when the sync process was kicked off.
The import took place over several days ending on Monday 7/26/2021, had issues being imported as it was so large, and ultimately was broken up into to 2 spreadsheets.

Example Error msg:
`copy failed: s3://crowd-content/early-copyright/copyright-title-pages-1849/2019713436/1087.jpg to s3://crowd-dev-content/early-copyright/copyright-title-pages-1849/2019713436/1087.jpg An error occurred (AccessDenied) when calling the GetObjectTagging operation: Access Denied`

[titlepagePRODimport_oversize.xlsx](https://github.com/LibraryOfCongress/concordia/files/6962394/titlepagePRODimport_oversize.xlsx)
[titlepagePRODimport.xlsx](https://github.com/LibraryOfCongress/concordia/files/6962398/titlepagePRODimport.xlsx)
[Error msg excerpt from log-events-viewer-result.csv](https://github.com/LibraryOfCongress/concordia/files/6962399/Error.msg.excerpt.from.log-events-viewer-result.csv)

**Comment by jkueloc** [comment]
I was able to successfully S3 copy over the individual files (aws cli) and then rerun run the ECS task without running into the error mentioned above.
So it may be a through put issue or constraint (?) and the campaign was too large and caused a misleading error message when something deeper in started to halt the requests....?

**Comment by acdha** [comment]
Was that error what the ECS task itself logged? It looks like what the `aws s3` command will log when told to copy tags as well as the file contents. I have no reason not to grant that permission but it won't help if that's not what the ECS task encountered.

**Comment by jkueloc** [comment]
Yes. It's what the ECS scheduled task RestoreDevDatabaseSyncS3Content logged while running the s3 sync step from crowd-content to crown-dev-content.  Same result on the test env task. It wouldn't complete stop - it would sync for a bit longer then stop syncing without further error messages.  Then the next time the task was schedule to run (6am monday weekly) it would go again - throw the same 24 errors with access denied but then sync more data.

The objects are large and there was a large number of large objects (MB) and smaller objects (KB). Originally it took the Crowd team several days to load it.

Thoughts I had was some kind of limit on the data import (size or time) maybe causing some kind of false error message because it wasn't handled gracefully and/or that metadata somewhere in the process was corrupted when the initial load to the crowd-content bucket failed causing the access denied error...?

It's a containerized process - I'm not quite sure where else to look for meaningful messages.
The logs for the process are in Cloudwatch  /aws/batch/job
crowd-test-db-sync/default/abe7886ff2c14508910bdc7547fa5271
crowd-dev-db-sync/default/ee567087f773487699f923dc4d79e327
