### ISSUE TITLE
Update registration page language

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1521]
We have gotten new registration page language approved by WGB and OGC that will allow us to better communicate with users who do not sign up for the newsletter.  

**Replace the existing first paragraph on the page with the text below:**
Register for an account to track your work, add tags, and review transcriptions. To sign up, please provide a username, email address, and a strong password. Once you click register, we will send you an email to confirm your address. We may use this email address to communicate with you about account activity, website updates, and, occasionally, to ask for your feedback.

Change the FAQ link in the second paragraph to: https://crowd.loc.gov/about/. Keep the rest of that paragraph as is. 

**Additional context**
Current registration page text:
![image](https://user-images.githubusercontent.com/20258744/130793132-a4a36400-5dc4-4c5e-abd4-320ca275d30f.png)

**Acceptance Criteria**
Issue is complete when registration page text has been updated with the text above.

**Acceptance Test:**

1. Go to registration page
2. Confirm that text matches the text in this ticket.

**Comment by jkueloc** [comment]
Good morning @lalgee. This is ready to be tested in the Development environment.

**Comment by lalgee** [comment]
Hi @jkueloc - thanks for making the changes!  It looks good, but we have one tweak to make it a little more readable. Please add an additional paragraph break before "To sign up".  So it should look like:

Register for an account to track your work, add tags and review transcriptions. 

To sign up, please provide a username, email address and a strong password. Once you click register, we will send you an email to confirm your address. We may use this email address to communicate with you about account activity, website updates, and, occasionally, to ask for your feedback.

Learn more about why we ask you to register in the FAQ

**Comment by jkueloc** [comment]
@lalgee Welcome!  Ok. I made the change and it's in development for you to review.

**Comment by lalgee** [comment]
Still needs the period after FAQ -- otherwise we're good to go!

**Comment by jkueloc** [comment]
@lalgee Oops. Sorry about the missing .  Please review the update in development.

**Comment by lalgee** [comment]
Looks great!  Closing the ticket.
