### ISSUE TITLE
Investigate sporadic 502 errors and reservation errors loading frontend pages

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1529]
**What behavior did you observe? Please describe the bug**
Volunteers and the community managers have observed a recent rise in 502-Bad Gateway errors and reservation errorswhen loading site pages.  This has been seen on transcription pages as well as campaign landing pages and the About page. 

After the 502 error on a transcription page, if the page finally loads it generally has a red band at the top showing a reservation or saving error. Sometimes the reservation error also occurs without the 502 but presents the "already reserved page message".  Here's a frustrated user's recent description:

"I was transcribing page 4 of 4 of a very long speech when all of a sudden (about 3/4 of the way through page 4) I received a message that said that someone else was transcribing this page and I should look for a new page. I had saved page 4 numerous times while working. What did I do wrong? How can I prevent this from happening again? I was so disappointed."

![image](https://user-images.githubusercontent.com/20258744/132898115-56483b4b-891e-4757-a6f4-0f393d220468.png)

**Comment by jkueloc** [comment]
Moved to Jira [CONCD-19](https://staff.loc.gov/tasks/browse/CONCD-19)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
