### ISSUE TITLE
Create a new database table storing history state changes & users

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#153]
This is backbone information that will act as a log of activity. 

User stories:
- As a community manager, we will be able to see a history of where and where users are flapping between states
- As a registered user, I will be able to see what action I took on a transcription and what state a transcription is currently in.

Acceptance criteria:
- [ ] A database that can capture what actions were taken by a user

**Comment by elainekamlley** [comment]
Data model and relationship is captured in #209

**Comment by acdha** [comment]
The database changes in #358 should allow this display
