### ISSUE TITLE
Document Concordia relational database

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1530]
**User story/persona**
As a community manager, onboarding developer, or other Concordia stakeholder, I want to understand the table structure of the Concordia database so that I can better articulate or plan data-related development or queries. A diagram of the existing database will serve this need.

**Additional context**
This will be particularly useful for sunset planning, as well as research the By the People team would like to undertake to better understands patterns of user contribution.

This may be helpful: https://medium.com/@yathomasi1/1-using-django-extensions-to-visualize-the-database-diagram-in-django-application-c5fa7e710e16

**Acceptance Criteria**
A diagram of the relational database has been created.
The process for creating the diagram has been documented to make it easy to update in the future.

**Comment by jkueloc** [comment]
@lalgee  I generated the attached file in my local version of concordia - our Django version doesn't support using the current version of pygraphviz actually being part of the application (as a dev package) maybe an earlier version.... 

Maybe we should chart upgrading Django after bulk deletion....sunsetting). The django-extensions is already part of concordia.

![graph_image](https://user-images.githubusercontent.com/72825410/140989788-952f60cd-6a02-43d9-9703-60dd9669db0e.jpg)

So, the tool used in the past from the docs, Graphviz, which I've actually used to better understand the database tables relationships, creates the output format svg. Currently, github doesn't support svg file type so I'll pass that file to you through another channel. 

Please let me know your thoughts.

**Comment by lalgee** [comment]
@elainekamlley @jkueloc I can get these into the BTP/concordia admin confluence.  Is there a good place to put these within github?

**Comment by jkueloc** [comment]
@lalgee Good question.  Maybe docs.... but it maybe more appropriate for Confluence.  It's not something that would be regenerated after each release to show changes.

**Comment by lalgee** [comment]
I added the images to an Appendix of the Concordia Admin Guide in the BTP Confluence

**Comment by jkueloc** [comment]
I added a link to the github doc that discuss Data Model Graph tools which now includes additional resource links. I added #8 in Confluence under Developer Onboarding referencing the same and the Admin Guide Appendix.

**Comment by jkueloc** [comment]
I added Chris's link to the github doc that discuss Data Model Graph tools to the Appendix. 
I also added in Confluence under Developer Onboarding #8 referencing the same and the Admin Guide Appendix.
