### ISSUE TITLE
Prep and deploy v 0.6.23 to production on 9/29

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1532]
Prep v 0.6.22 to include: 
- recent export fixes: 
- #1508 
- #1501 
- registration page language #1521

**Comment by elainekamlley** [comment]
Hey @rabiloc was this deployed to production before 9/29?

**Comment by rabiloc** [comment]
@elainekamlley Just one fix was deployed, the one with the front page links not working, the rest are in dev and test and will be deployed on 9/29
