### ISSUE TITLE
next-reviewable-asset  and next-transcribable-asset query links producing 504 gateway timeout errors

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1537]
**What behavior did you observe? Please describe the bug**
The urls https://crowd.loc.gov/next-transcribable-asset and https://crowd.loc.gov/next-reviewable-asset are timing out to 504 gateway errors. Both of these are used on the By the People homepage below the carousel to take volunteers directly into activity.

**How can we reproduce the bug?**
1. Go to https://crowd.loc.gov/
2. Scroll down to "Suprise me" section
3. Click on "Jump into a transcription"

**What is the expected behavior?**
The next-transcribable-asset url should take a user to the next unreserved "Not Started" asset.  The next-reviewable-asset url should take a user to the next unreserved "Needs review" asset.

**Got screenshots? This helps us identify the issue**
![image](https://user-images.githubusercontent.com/20258744/133481016-c2dd1b8b-3b09-45dd-918e-ddb451b0fb0f.png)

**Additional context**
The link is a dynamic query.  Notably, it still works to do next-transcribable-asset or next-reviewable-asset within a campaign, like https://crowd.loc.gov/campaigns/herencia-centuries-of-spanish-legal-documents/next-reviewable-asset

The bug could be a performance issue related to the recent import of the Early Copyright campaign to production, which added 97,000 new assets to the database.

If the bug can't be easily resolved, we may want to remove the Surprise me section of the homepage until after sunsetting is implemented.

**Comment by lalgee** [comment]
Since the campaign-specific queries are still working, for the time being we can just trade out the URLs for ones we know will have plenty to do for the forseeable future.  So please change the links to the following:

- Jump into a transcription - https://crowd.loc.gov/campaigns/rough-rider-bull-moose-theodore-roosevelt/next-transcribable-asset
- Jump into a review - https://crowd.loc.gov/campaigns/organizing-for-womens-suffrage-the-nawsa-records/next-reviewable-asset

**Comment by lalgee** [comment]
The url update looks good in dev and can be pushed to production.  Thanks for jumping on this quickly!

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-18](https://staff.loc.gov/tasks/browse/CONCD-18)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
