### ISSUE TITLE
Registered users unable to delete others' tags

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1541]
**What behavior did you observe? Please describe the bug**
As a registered volunteer, when I click on the X next to a tag, it appears I have deleted it, but when I reload the page it has not actually been removed. 

**How can we reproduce the bug?**

1. Find an asset with tags (ex: https://crowd.loc.gov/campaigns/clara-barton-angel-of-the-battlefield/general-correspondence/mss119730423/mss119730423-54/)
2. Click on the X of any tag (that you did not create)
3. See the tag disappear
3. Click "Save tags"
4. Reload the page
3. See the tag reappear.

**What is the expected behavior?**
As a volunteer, when I click the X of a tag and it disappears, I expect that I have deleted it.  This is how the site was intended to to work.

**Additional context**
Rather than attempting to fix the functionality, we could make it so that users only see an X on a tag they have created.  This matches their expectations to the existing functionality, in which they can only delete their own tags.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-16](https://staff.loc.gov/tasks/browse/CONCD-16)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
