### ISSUE TITLE
Alphabetize campaign title list in Django admin filtering

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1542]
**User story/persona**
As a community manager, when I am working in the Django admin, I want to find the campaign title I'm looking for in the campaign filters that are on the asset, item, project, and transcription modules.

**Is your feature request related to a problem? Please describe.**
As the list of campaigns continues to grow, community managers and others using the admin interface need to be able to find the campaign title they are looking for in the admin interface filters. Alphabetizing the titles would allow Admins to more easily find the titles.

**Acceptance Criteria**
The "Campaigns" filter on the asset, item, project, and transcription dashboards are sorted alphabetically.

**Acceptance Test:**
1. Go to the asset dashboard
2. Look at the Campaign filter on the right side of the dashboard
3. Confirm that all campaigns are listed and in alphabetical order:
- American Creativity: Early Copyright Title Pages
- James A. Garfield Diary: "His Confidential Friend"
- Historical Legal Reports from the Law Library of Congress
- Mary Church Terrell: Advocate for African Americans and Women
- Down to Raisins: the Remaining Letters to Lincoln
- Letters to Lincoln
- By Design: Frederick Law Olmsted & Olmsted Associates
- American Creativity: Early Copyright Title Pages
- Anna E. Dickinson Papers
- At the Library and in the Field: John and Alan Lomax Papers
- Branch Rickey: Changing the Game
- By Design: Frederick Law Olmsted & Olmsted Associates
- Carrie Chapman Catt Papers
- Civil War Soldiers: "Disabled but not disheartened"
- Clara Barton: "Angel of the Battlefield"
- Down to Raisins: the Remaining Letters to Lincoln
- Elizabeth Cady Stanton Papers
- Herencia: Centuries of Spanish Legal Documents
- Historical Legal Reports from the Law Library of Congress
- James A. Garfield Diary: "His Confidential Friend"
- Letters to Lincoln
- Mary Church Terrell: Advocate for African Americans and Women
- My great mass of papers: Correspondence of Theodore Roosevelt
- Ordinary Lives in George Washington's Papers: The Revolutionary War
- Organizing for Women's Suffrage: The NAWSA Records
- Rosa Parks: In Her Own Words
- Rough Rider to Bull Moose: Letters to Theodore Roosevelt
- Seers, Spiritualists, and the Spirit World: The experiments of Frederick Hockley
- Susan B. Anthony Papers
- The Blackwells: An Extraordinary Family
- The Man Who Recorded the World: On the Road with Alan Lomax
- Theater for the People: Federal Theatre Project playbills
- This Hell-upon-earth of a Prison: Samuel J. Gibson's Andersonville Diary
- Walt Whitman
- War Diaries of George S. Patton

Repeat for the item, project, and transcription dashboards

**Comment by mderbyatloc** [comment]
> **User story/persona** As a community manager, when I am working in the Django admin, I want to find the campaign title I'm looking for in the campaign filters that are on the asset, item, project, and transcription modules.
> 
> **Is your feature request related to a problem? Please describe.** As the list of campaigns continues to grow, community managers and others using the admin interface need to be able to find the campaign title they are looking for in the admin interface filters. Alphabetizing the titles would allow Admins to more easily find the titles.
> 
> **Acceptance Criteria** The "Campaigns" filter on the asset, item, project, and transcription dashboards are sorted alphabetically.
> 
> **Acceptance Test:**
> 
> 1. Go to the asset dashboard
> 2. Look at the Campaign filter on the right side of the dashboard
> 3. Confirm that all campaigns are listed and in alphabetical order:
> 
> * American Creativity: Early Copyright Title Pages
> * James A. Garfield Diary: "His Confidential Friend"
> * Historical Legal Reports from the Law Library of Congress
> * Mary Church Terrell: Advocate for African Americans and Women
> * Down to Raisins: the Remaining Letters to Lincoln
> * Letters to Lincoln
> * By Design: Frederick Law Olmsted & Olmsted Associates
> * American Creativity: Early Copyright Title Pages
> * Anna E. Dickinson Papers
> * At the Library and in the Field: John and Alan Lomax Papers
> * Branch Rickey: Changing the Game
> * By Design: Frederick Law Olmsted & Olmsted Associates
> * Carrie Chapman Catt Papers
> * Civil War Soldiers: "Disabled but not disheartened"
> * Clara Barton: "Angel of the Battlefield"
> * Down to Raisins: the Remaining Letters to Lincoln
> * Elizabeth Cady Stanton Papers
> * Herencia: Centuries of Spanish Legal Documents
> * Historical Legal Reports from the Law Library of Congress
> * James A. Garfield Diary: "His Confidential Friend"
> * Letters to Lincoln
> * Mary Church Terrell: Advocate for African Americans and Women
> * My great mass of papers�: Correspondence of Theodore Roosevelt
> * Ordinary Lives in George Washington's Papers: The Revolutionary War
> * Organizing for Women's Suffrage: The NAWSA Records
> * Rosa Parks: In Her Own Words
> * Rough Rider to Bull Moose: Letters to Theodore Roosevelt
> * Seers, Spiritualists, and the Spirit World: The experiments of Frederick Hockley
> * Susan B. Anthony Papers
> * The Blackwells: An Extraordinary Family
> * The Man Who Recorded the World: On the Road with Alan Lomax
> * Theater for the People: Federal Theatre Project playbills
> * This Hell-upon-earth of a Prison: Samuel J. Gibson's Andersonville Diary
> * Walt Whitman
> * War Diaries of George S. Patton
> 
> Repeat for the item, project, and transcription dashboards

Hello - this is a test
