### ISSUE TITLE
Display tag count in Tags area header

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1548]
**User story/persona**
As a user, I want to be able to tell if the page I'm viewing has tags (and if so, how many) before expanding the Tags area.

**Is your feature request related to a problem? Please describe.**
https://github.com/LibraryOfCongress/concordia/issues/1339 made the Tag area collapsed by default so the transcription box can be larger on small screens. 
 However, there is not yet a way for users to know if a page has tags until they expand the tag area. 

**Additional context**
very rough idea of where/how the tag count could be used to show a page has tags
![image](https://user-images.githubusercontent.com/20258744/134964556-11bb02c5-b62f-4c68-aedb-f5fae37a03cd.png)

**Acceptance Criteria**
When I visit a page, I can tell if there are tags because a count is shown next to the Tags header.  When I expand the Tags area, the number of tags matches the count.

**Acceptance Test:**
1. Go to a page with Tags (https://crowd-dev.loc.gov/campaigns/lomax-library-field/personal/afc1933001_ms258/afc1933001_ms258-2/)
2. See the Tags area header
3. Check that a count is displayed next to the Tags area header
4. Expand the Tags area
5. Check that the count matches the number of tags on the page
6. Add a new tag
7. Save tags
8. Reload the page
9. Check that the count has updated
10. Delete a tag
11. Check that the count has updated

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-15](https://staff.loc.gov/tasks/browse/CONCD-15)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
