### ISSUE TITLE
Empty screen in Safari

### ISSUE THREAD

**Issue by Igor-Ino** [LibraryOfCongress/concordia#1552]
**What behavior did you observe? Please describe the bug**
When I am using macOS 11.4 and attempt to toggle full screen, the screen is empty.

**How can we reproduce the bug?**

1. For example, go to 'https://crowd-test.loc.gov/campaigns/blackwells-extraordinary-family/henry-browne-blackwell-family-correspondence/mss1288001343/mss1288001343-2/.'
2. Click on 'Toggle full screen'
3. See empty screen

**What is the expected behavior?**
Expected image detail window to open full-screen

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.
Screenshot: 
<img width="1000" alt="Screen Shot 2021-09-29 at 21 34 37" src="https://user-images.githubusercontent.com/80710853/135484032-4184a411-c942-4a22-94b0-4fa89b07ca40.png">

**Desktop (please complete the following information):**

-   OS: [macOS 11.4]
-   Browser [Safari 14.1.1]

**Additional context**

**Comment by acdha** [comment]
This doesn't reproduce in Safari 15. Is that the version you're using?

Can you open the JavaScript console (⌥⌘C) and report any errors?

**Comment by Igor-Ino** [comment]
Safari 14.1.1
error from console is attached:

<img width="611" alt="Screen Shot 2021-09-30 at 11 32 05" src="https://user-images.githubusercontent.com/80710853/135486127-85b6ec5b-3653-4318-8da0-8e2b84d48f35.png">

**Comment by Igor-Ino** [comment]
More details:
<img width="609" alt="Screen Shot 2021-09-30 at 16 12 51" src="https://user-images.githubusercontent.com/80710853/135524518-270a96e7-5419-4b85-a15b-d4f853467ee3.png">

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-13](https://staff.loc.gov/tasks/browse/CONCD-13)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
