### ISSUE TITLE
Lets Go! button goes to a page that needs to be worked on

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#157]
User story: 
- [ ] As a user, I can click on the Get started button and be brought to a single page that needs transcribing and the instructions on how to get started is visible

Acceptance criteria: 
- [ ] The asset that appears when Get started is clicked is an asset that no one is on and has not been worked on yet.

**Comment by acdha** [comment]
This looks like it’s now moot?

**Comment by rstorey** [comment]
This is done
