### ISSUE TITLE
Admin S3 Object Deletion - Build out - add Asset Image File field....

### ISSUE THREAD

**Issue by jkueloc** [LibraryOfCongress/concordia#1575]
Admin S3 Object Deletion - Build out - add Asset Image File field
Research/discussions ticket #1573 
Solution Decision ticket #1574 (should be more than one ticket/issue to be granular about the path of individual choices and results that lead to the 'whole' solution...?)

**Comment by jkueloc** [comment]
Update: Image Field

- Added Image Field to Asset model - 
- [ ] Makemigrations and migrate don't populate and associate field to existing s3 objects.  I know how to make that happen. The question ion my mind is should this added to app logic... 'If exists'... or just a one time implementation/install/release script? 
- Successfully tested delete of asset with related S3 object deleted. 
- Successfully tested adding a local file thru admin asset change form and uploading to S3 with correct object key in db
- [ ] How does this impact the Import process?

**Comment by lalgee** [comment]
@jkueloc I tested the small import using test Lincoln items and the storage image field successfully populated. Image replacement also worked successfully.  But deletion failed for 1 or more items -- recieved a 500 error.

**Comment by lalgee** [comment]
Testing was also successful with an import of 9,000+ images.  I did not see a noticeable delay in import time.  I also tested asset replacement and deletion with this group.  Replacement worked well and I was able to delete many assets at a time, successfully removing the Concordia record and the AWS files/directories.

In fact, I was able to delete up to 7 items including 657 assets, much higher than we were previously able to do.

So I also tried a much larger deletion of 133 items including 8,189 assets.  As I expected, the task appeared to fail showing me a 500 error, but when I checked Concordia and AWS it did successfully delete all of the Concordia records and all of the AWS files and directories!

**Comment by jkueloc** [comment]
@lalgee That's great!  Thank you for testing!

The 500 is that response time thing between the UI and the backend. Which was a topic of a possible solution in the [chuck or celery task conversation on the research ticket #1573](https://github.com/LibraryOfCongress/concordia/issues/1573#:~:text=commented-,22%20days%20ago,-Is%20there%20any), as well as prefetching of an older delete ticket #1090.

Building that out will be part of the batch|bulk delete | campaign/project retire ticket(s) that I haven't created / broken out into new tickets yet. I'd like to talk about that in the meeting tomorrow.

I still need to build out the production worthy solution to populate the existing asset storage image fields - but that should inform (for me at least) the coming new tickets.

**Comment by elainekamlley** [comment]
This ticket will close once set permissions in AWS are applied to test, stage, and prod

**Comment by jkueloc** [comment]
The permissions in AWS have been applied to test, stage, prod.
