### ISSUE TITLE
Improve CAPTCHA quality

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1582]
Related to ticket #1580: 

Currently CAPTCHA is used for anonymous submissions. The CAPTCHA window is small and often hard to read. Improving this experience can lead to a more effortless submission process. 

Additionally, we have been seeing an uptake in bot registration submissions and adding CAPTCHA can help with blocking this type of activity. This ticket is to improve the experience of CAPTCHA. A separate ticket will be created to implementing to the registration page. 

Acceptance Criteria: 

- Larger CAPTCHA window so that a user can read the text
- As a user, I would like to refresh the CAPTCHA text if I can't read it 
- As a user, I would like have an option to hear the CAPTCHA text - separate ticket https://github.com/LibraryOfCongress/concordia/issues/1661

**Comment by lalgee** [comment]
Refresh button text should be "Show me another image"

**Comment by jkueloc** [comment]
https://github.com/LibraryOfCongress/concordia/releases/tag/v0.6.28
