### ISSUE TITLE
 Mary Church Terrell BagIt export fails

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1584]
**What behavior did you observe? Please describe the bug**
The Mary Church Terrell export times out in production as well as test.  A 504 error eventually loads. The bag does not download and a new bag is not created in AWS.

**How can we reproduce the bug?**

1. Go to Django Admin
2. Go to Campaigns 
2. Click on Mary Church Terrell
3. Click EXPORT BAGIT

**What is the expected behavior?**
After clicking the EXPORT BAGIT button a .zip file containing all campaign transcription TXTs and metadata should download.

**Comment by jkueloc** [comment]
This export has been completed using the known local dev env workaround with a fresh dmp from production. The zip can be found in the S3 bucket crowd dev export.
