### ISSUE TITLE
Improve Concordia page load times by indexing tables

### ISSUE THREAD

**Issue by rabiloc** [LibraryOfCongress/concordia#1600]
**User story/persona**
As a user I want concordia pages to load up faster

**Is your feature request related to a problem? Please describe.**
Pages taking longer to load

**Additional context**
Improve the indexing of tables to determine if performance improvements can be made

**Acceptance Criteria**
Pages load up quicker

**Acceptance Test:**
Click on the various pages to see load times

Tied to Issue #1450

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
