### ISSUE TITLE
Alphabetize campaign filter in site report dashboard

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1602]
**User story/persona**
As community manager generating a site report, I need to be able to locate the title of the campaign i want to filter by quickly and easily.

**Additional context**
Other Django filters were alphabetized in https://github.com/LibraryOfCongress/concordia/issues/1542 - can likely reuse this code.

**Acceptance Test:**
1. Go to the[ site reports](https://crowd.loc.gov/admin/concordia/sitereport/) dashboard
2. Look at the Campaign filter on the right side of the dashboard
3. Confirm that all campaigns are listed and in alphabetical order:

**Comment by jkueloc** [comment]
@lalgee The "All" option within the Filter 'By Sorted Campaign' list is still available.  What I saw results wise with the '-' was a subset listing of Site Reports that have a null value for Campaign and Topic values.  However, if you select "All" in Filter By Sorted Campaign you use the Column name button sort feature/functionality to reverse sort which puts the results with a null Campaign or Topic value at the top of the list.

**Comment by jkueloc** [comment]
Initital release of By Sorted Campaign with Campaign and Topic Filters was in [Releases ](https://github.com/LibraryOfCongress/concordia/releases) [v0.6.27](https://github.com/LibraryOfCongress/concordia/releases/tag/v0.6.27) on April 4, 2022

**Comment by lalgee** [comment]
The site report "By Without Campaign" filter is a great solution BUT for some reason when i filter "By Without Campaign" and the Topic filter to null and export, the export is empty. That's true for both csv and excel downloads.  There is data there when I click through into the report within Django or when I download that "null" data along with all other topics or all other campaigns.

**Comment by jkueloc** [comment]
@lalgee  It was kind of a hack to not give you a whole list of dashes....makes sense that there are unwanted downstream impacts. Surely there is another approach entirely or different approach to suppress the view but not the dataset result.
I'll take another shot at that particular one.
