### ISSUE TITLE
Incorrect resource URLS in item-resource-urls.txt

### ISSUE THREAD

**Issue by madelinegoebel** [LibraryOfCongress/concordia#1603]
**What behavior did you observe? Please describe the bug**
The resource URLs in the item-resource-urls.txt file in the BagIt export are not all correct. 
Correct URL example: http://www.loc.gov/resource/llhsp.llhsp_laws_01-00612-00617/
Incorrect URL example: http://www.loc.gov/resource/llhsp.2018751790/
JSON for above resource: https://www.loc.gov/resource/llhsp.llhsp_laws_04-00220-00224/?fo=json
This is causing problems when running the script to create concatenated text files.

**How can we reproduce the bug?**

1. Export from Concordia. Home > Project Level Export > Herencia > Select Laws & Statutes: Agriculture, Conservation, Hunting and Fishing, Laws & Statutes: Crime and Law Enforcement, Laws & Statutes: Disease and Public Health, Laws & Statutes: Immigration and Foreign Affairs, and Laws & Statutes: Military and National Security > Submit
2. Unzip BagIt export
3. Open item-resource-urls.txt file.

**What is the expected behavior?**
Resource URLs should be in the correct format. The resource URL is correct in Concordia, but it seems that the resource URL included in item-resource-urls.txt is coming from the JSON metadata.

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

-   OS: windows
-   Browser: chrome

**Additional context**
It looks like it's taking https://hdl.loc.gov/loc.law/llhsp.2018751793 from the record and trying to interpret that as a handle resource url instead of using the 856 d/f. This is a hold over in p1 code from old stuff.

I found a work around so I was still able to process the files. That being said, we will be exporting more from Herencia in the future.

**Comment by jkueloc** [comment]
The file contains an entry for each asset whether or not the resource url value already exists in the file. 
The most direct approach since the asset has the correct value would be to create the file by selecting the distinct resource url from the asset records being bagged.

**Comment by madelinegoebel** [comment]
Hi Jen,

Here is a related ticket for your reference: https://staff.loc.gov/tasks/browse/LOCGOV-23186

**Comment by jkueloc** [comment]
Hi Madeline,
So - the resource URL value stored in the Concordia asset record is correct or is NOT correct?

**Comment by madelinegoebel** [comment]
Hi Jen, 

The resource URL value in the Concordia asset record is correct. For the example above of an incorrect URL in the text file ( http://www.loc.gov/resource/llhsp.2018751790/) the resource URL for the asset is https://www.loc.gov/resource/llhsp.llhsp_laws_04-00220-00224/

**Comment by jkueloc** [comment]
@lalgee @madelinegoebel This is now in development
Go ahead and give export bagit at the campaign level I try.  I actually got it to work in development for Walt and Mary Church Terrell for what it's worth. First time a 504 showed up but the app logs showed the process still running so I hit the reload icon in the browser and got slowly got the file save dialog and the file was intact.  Checkout the item_resource.txt file. The duplication should be gone.

**Comment by madelinegoebel** [comment]
thank you @jkueloc! The bagit export for Terrell looks good. I also re-exported the herencia projects and the URLs look good there too. One question: the file with the URLs was previously called item-resource-urls.txt, but now it is asset-resource-urls.txt. Is there a reason for this change? If not, would it be possible to keep naming the file item-resource-urls.txt?

**Comment by jkueloc** [comment]
Welcome! @madelinegoebel. The reason I changed it is that now the data comes from the asset resource_url field rather than attempting to pull it out of the metadata on the item record. However, if it makes more sense to you as an application user I can certainly change it back.

**Comment by madelinegoebel** [comment]
@jkueloc changing it back makes sense to me. thank you for the explanation and for your work on this issue!

**Comment by jkueloc** [comment]
@madelinegoebel  The file renaming is complete.

**Comment by madelinegoebel** [comment]
@jkueloc thank you! I'll go ahead and close this ticket.
