### ISSUE TITLE
Fix campaign creation form

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#162]
1. There’s a bug causing it to return HTTP 400 unauthorized even though I’m logged in as the superuser
2. The form has no feedback about that error 
3. The form doesn’t support the standard keyboard submission because it’s not actually a form – the `<form>` tag is commented out for unknown reasons
4. There are a bunch of errors tossed in the error pages for things like the forum URL patterns which I haven’t looked into yet but which may be related
5. Prior to submitting the form, it hits `/get_task_status/` but that fails because the URL is defined as requiring a task name which isn’t provided
6. jQuery UI is loaded on the page but there's no indication about what it is being used for
7. There's a huge chunk of inline CSS on https://github.com/ArtemisConsulting/concordia/blob/master/concordia/templates/transcriptions/create.html which should be moved into an external resource and remediated to follow our style guide
8. There are some hidden inputs which have no documentation about their purpose, data-types, etc.
9. There are several jQuery AJAX calls which have error paths which do not produce any user-visible output
10. There are a bunch of console.log calls throughout the code which should be removed

**Comment by rstorey** [comment]
The name of the template also needs to be changed to be more descriptive of what it actually is.

**Comment by acdha** [comment]
This is moot now that we've deleted this code & are using Django/jQuery correctly
