### ISSUE TITLE
Remove hard coded session timeout configuration

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#165]
Research

Does this error occur after 10 mins

If yes, where is this ajax setting set up

if it is, put it in a settings file

We need one place to configure session timeout (in Django settings) that will also apply to front-end code. Note that “10 minutes” is hard-coded into the error message here: https://github.com/ArtemisConsulting/concordia/blob/master/concordia/templates/transcriptions/create.html

**Comment by rstorey** [comment]
The code in question is no longer in the codebase.
