### ISSUE TITLE
Newly Transcribed and submitted pages are not reflected on profile "pages worked on"

### ISSUE THREAD

**Issue by jkueloc** [LibraryOfCongress/concordia#1652]
**What behavior did you observe? Please describe the bug**
...just spent a little time with the profile page and it looks like sorting and pagination works! we're still having the problem of transcriptions not showing up properly. for instance, i transcribed a page and submitted it but it didn't appear on my profile. i then reviewed several pages from the same campaign and those pages showed up instantly under "pages worked on." my counts went up in the "contributions" table but the transcribed page never showed up in the "pages work on list."

UPDATE:  Only "Reviewed" pages are showing up in the Pages Worked On list. There are pages with the contribution of "Transcribed". Start at last page and move forward.

**How can we reproduce the bug?**

1. Go to a page to transcribe and transcribe the page.
2. Click on Submit
3. Go to the profile page 
4. Scroll down to 'pages worked on'
5. The newly transcribed page that was submitted does not appear in the pages worked on listing
6. Click through additional pages
7. See that all pages have the contribution of "Reviewed"

**What is the expected behavior?**
On the profile page:
I expected the count to be reflected in the related Campaign Saves & Submits count. 
The transcribed page should be listed in the "Pages worked on" section

**Got screenshots? This helps us identify the issue**
![image](https://user-images.githubusercontent.com/20258744/160432137-47f639f4-71be-429a-ade2-d90c5f117680.png)

**Additional context**
This ticket is broken out from [Profile "pages worked on" is incorrect and pagination is broken when viewing "All Campaigns" #1556](https://github.com/LibraryOfCongress/concordia/issues/1556)

**Comment by lalgee** [comment]
Could this be related to https://github.com/LibraryOfCongress/concordia/issues/1557?

**Comment by jkueloc** [comment]
@lalgee I did the same series of tests in Dev as I did in my local environment had the same result.  I could not recreate the issue.  It must have to do with having a significant amount of contributions of one type or another that is somehow filtering out. I'll keep looking into it.

![Screen Shot 2022-03-28 at 2 23 38 PM](https://user-images.githubusercontent.com/72825410/160462579-34aee361-0f18-4b45-a9c1-d8fd631969ad.png)
![Screen Shot 2022-03-28 at 2 23 54 PM](https://user-images.githubusercontent.com/72825410/160462584-26435bc9-c188-429a-bcab-445d424f0034.png)

**Comment by jkueloc** [comment]
Update: 
This is directly related to [Profile "pages worked on" is incorrect and pagination is broken when viewing "All Campaigns" #1556](https://github.com/LibraryOfCongress/concordia/issues/1556)

We are running into a pagination bug that exists when ordering on a datetime field on the queryset. Based on my research and observations changing code thus far  - the only way to get the ordering you want throughout pagination is ordering at the queryset level. The records are served from the database in the most efficient way for DBMS when you don't specify the ordering (think index, table record ID). Pagination only receives the number of records from the database defined by the paginate_by number, expressed to the database as query LIMIT, so applying a sort at post level only sorts that subset  of records - LIMIT/OFFSET chunk.
