### ISSUE TITLE
ADA testing

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#166]
Prior to launch test for 508 compliance and mediate any actionable issues. 

Acceptance criteria:
- Do a sweep of the site on CodeSniffer or WAVE 
- Test on screen reader
- Create a ticket to address issues

**Comment by elainekamlley** [comment]
Ran crowd.loc.gov through Codesniffer and WAVE. Some items to immediately address: 

- Add alt tags to contribute icons
- Add aria tags to social media icons in the footer

A number of errors came up for contrast ratio. Need to review: 
- related links panel
- Footer and nav
- FAQ list 
Ex. ``` Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.26:1. Recommendation: change background to #d33e00.```

**Comment by rstorey** [comment]
https://developers.google.com/web/tools/lighthouse/
https://github.com/cehfisher/a11y-style-guide
http://khan.github.io/tota11y/#Try-it

**Comment by VVH** [comment]
Yesterday we discussed putting some screen-reader text on the home page to make the purpose of the site more immediately apparent to visitors using screen readers. Here's a stab at some text: 

Welcome to crowd.loc.gov, a crowdsourcing website built by the Library of Congress. Our goal is make machine-readable transcriptions from non-machine readable images of manuscripts and printed materials. This effort is drive by volunteers and supported by a full time staff at the Library. Our dream is to make Library materials more accessible to readers from all around the world.

**Comment by acdha** [comment]
Seems like that might also work as the meta description tag

**Comment by elainekamlley** [comment]
I think this is good to close. You all did some work on this and added ADA testing into our work flow. Nice work.

**Comment by acdha** [comment]
Agreed. #589 is going to be the main real improvement.
