### ISSUE TITLE
Add audio option to CAPTCHA

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#1661]
**User story/persona**
As a user I want the option to hear an audio version of the CAPTCHA.

**Additional context**
Moving this into its own ticket from https://github.com/LibraryOfCongress/concordia/issues/1582

**Acceptance Criteria**
As a user I have a CAPTCHA i can complete that does not require me to see a visual image/text.

**Comment by jkueloc** [comment]
Move to Jira: [CONCD-6](https://staff.loc.gov/tasks/browse/CONCD-6)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
