### ISSUE TITLE
Add 15 min timeout when user tries to log in more than three times

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#167]
When a user enters the wrong password three times, users can't log in for another 15 mins. 

Acceptance criteria: 
- A function that locks a specific user from attempting to log in more than 3 times
- An message telling the user to wait and try again later or they can reset their password.

**Comment by rstorey** [comment]
From @acdha: 

What I was thinking was creating a CloudWatch log group as part of our cloud formation setup, with the ECS user having the ability to push events to it.

Then we’d register signal handlers for the login success/fail signals which basically call https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.put_log_events

 https://github.com/brutasse/django-ratelimit-backend

**Comment by acdha** [comment]
This suggests we’ll want to add an ElastiCache redis cluster for this, #217, #188, etc.

**Comment by rstorey** [comment]
https://django-ratelimit.readthedocs.io/en/latest/usage.html

**Comment by elainekamlley** [comment]
Close as a dupe of #217
