### ISSUE TITLE
Password strength validation

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#168]
As a user registering for an account, I want to know how strong my password is so that I can feel confident that my profile is as safe

https://pwned-passwords-django.readthedocs.io/

https://github.com/dropbox/zxcvbn

Backend validation for password strength. It’ll get things like Password123 which satisfy most algorithmic requirements but are common on widely shared dictionaries

**Comment by acdha** [comment]
pwned-passwords-django uses an outside service which tries to be privacy preserving but may still require approval:

https://pwned-passwords-django.readthedocs.io/en/1.3.1/faq.html#how-can-this-be-secure-it-s-sending-passwords-to-some-random-site

zxcbn will be a huge improvement over our existing validator which accepts very weak common passwords

**Comment by jbresner** [comment]
The current registration page has both recommendations and requirements for a users password:

- Your password can't be too similar to your other personal information.
- Your password must contain at least 8 characters.
- Your password can't be a commonly used password.
- Your password can't be entirely numeric.
- Your password fails to meet our complexity requirements.

Some of these look like requirements (2 and 4) but some feel a lot like recommendations (1, 3, and 5...what are the LOC's complexity requirements?). Do we plan on providing feedback as a user enters a password? Unless we can provide clear guidelines on how to create a password, I'd consider removing the recommendations.

**Comment by acdha** [comment]
The plan is to provide feedback once that bit of JavaScript is cleaned up rather than just telling you rules

**Comment by acdha** [comment]
We do most of what's in this ticket now that #386 has merged. I'm voting that we close this and create a ticket to switch to zxcvbn later.
