### ISSUE TITLE
Add newsletter signup link to about, FAQ, and footer

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#170]
Link to here: https://updates.loc.gov/accounts/USLOC/subscriber/new?topic_id=USLOC_175

**Comment by rstorey** [comment]
Where in the footer do you want this link to go?

**Comment by rstorey** [comment]
There's currently a link to loc.gov/subscribe in the footer - that could be changed to point directly to https://updates.loc.gov/accounts/USLOC/subscriber/new?topic_id=USLOC_175

**Comment by rstorey** [comment]
Also see #265

**Comment by elainekamlley** [comment]
@rstorey I believe that is correct. @lalgee Can you confirm that is our code?

**Comment by lalgee** [comment]
Yes, Rosie's direct link to our GovDelivery is correct.  There is no campaign code to amend since we are linking from a loc.gov website rather than social media traffic, so the source will already be picked up by Adobe Analytics.

**Comment by elainekamlley** [comment]
Closing since this is a dupe
