### ISSUE TITLE
Review front-end error display

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#178]
We have a number of places in the code where AJAX requests have only a `console.log` handler. We need to take Jamie's work on consistent UI messaging to create some convention for displaying these and then review every `console` call to replace it with the appropriate warning/error UI and a clear message indicating what the user can do to resolve the problem.

**Comment by rstorey** [comment]
I didn't find any console.log requests in our code that needed to be changed to on-screen error messages. However I did find that the specific detailed error messages being returned in JsonResponses in views.py aren't coming through to the front end - messages such as "An open transcription already exists" etc.

**Comment by acdha** [comment]
The contribute code uses this function to do that:

https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/js/contribute.js#L15-L24

We should move that into base.js and update the reservation code to use it as well.
