### ISSUE TITLE
Draft browser support policy

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#179]
Rough idea:

* A-grade support for “evergreen” browsers which get updates: Chrome, Edge, Firefox, Safari, etc.
* B-grade support for legacy-but-still-used browsers like IE11, possibly with reduced performance due to e.g. polyfills or reduction of advanced features
* No support for browsers which are not actively supported by their makers

**Comment by elainekamlley** [comment]
To do: 

- [ ] Find out if LOC has one
- [ ] gather examples 
- [ ] draft one @elainekamlley to take the first pass

**Comment by elainekamlley** [comment]
For now we will be moving forward with support for evergreen browsers but will provide support for IE 11 in a future sprint. Browser support info is in the FAQ
