### ISSUE TITLE
Better logging usage

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#183]
We have many cases where `logging` calls force string-interpolation and don't pass additional context for Sentry. We should review each logging call to make sure they delay interpolation and asking whether there is additional context which would be useful.

Instead of:

```python
logger.error("Error while writing the file to disk : %s " % str(e))
```

This should be:
```python
logger.error("Error while writing the file to disk: %s", e)
```

Or, in an `except` block:
```python
logger.error("Error while writing the file to disk: %s", e, exc_info=True, extra={"data": {"something": "interesting"}})
```

**Comment by rstorey** [comment]
I just checked all the logger calls and they are done the correct way - so this is already done.
