### ISSUE TITLE
Review pagination usage

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#185]
There are multiple cases where `paginator.get_page()` is called with a request `GET` / `POST` value which has not been converted to an integer, which causes Django to default to page 1:

https://docs.djangoproject.com/en/2.1/_modules/django/core/paginator/#Paginator.get_page

**Comment by rstorey** [comment]
Looks like this was already done - there's only one case where `paginator.get_page()` is called and the argument is an integer. Can you confirm @acdha ?

**Comment by acdha** [comment]
Yes – I've been chipping away at those and will close this ticket as soon as I get that last one, which I partially remediated with the int conversion but should just move over to using the pagination mixin like everything else so the template variables will follow the same pattern.

**Comment by elainekamlley** [comment]
Closed with #220
