### ISSUE TITLE
Implement actual statistics

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#199]
The numbers in the footer are currently static text

**Comment by acdha** [comment]
@elainekamlley the statistics in the footer were removed in https://github.com/LibraryOfCongress/concordia/commit/871726540fe16941c162a80486896db092619d12. Are we bringing them back as a page? If not, we can close this issue.

**Comment by rstorey** [comment]
I'd like to move this out of Priority 1

**Comment by acdha** [comment]
Agreed: now that it's not *wrong* we can bump it down until we have more content to report on

**Comment by elainekamlley** [comment]
Done. The only numbers and statistics we are lifting at this time are at the item level. Issue #158 

I think we can close this issue. We can redraft another ticket if we identify a specific user case for our general users
