### ISSUE TITLE
Basic Tagging and Transcription UI

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#20]
- [ ] As a user, I may only want to transcribe

- [ ] As a user, I may only want to tag

- [ ] As a user, I may want to move back and forth between transcription and tagging in a customized view

- [ ] As a product owner, I would like options of wireframes for which I can provide feedback and represent the many workflows of transcription and tagging 

- [ ] As a "Citizen Historian" stakeholder, I want to have the opportunity to view the work in progress and give feedback on the UI within the sprint

**Comment by rstorey** [comment]
This is done
