### ISSUE TITLE
Admin UI improvements

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#203]
Low priority items which shouldn't be forgotten:

* [x] Every slug field should be [linked to the source field](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.prepopulated_fields)
* [x] Set list filters on status
* [x] Enable text search
* [x] Consider enabling autocomplete for some related fields such as campaign / project
* [x] Add navigation links to related objects – e.g. jump from a project to its assets
* [x] Truncate large fields in list displays
* [x] Add publish/unpublish admin list actions
* [x] Add active/inactive admin list actions
* [x] In admin page for a user, link to their transcription activity
* [x] In admin transcriptions page be able to search on usernames
* [x] Admins are able to filter users by when their account was created and whether it is activated

**Comment by elainekamlley** [comment]
Moving @lalgee comments from another ticket: 

As a community manager I need to be able to find the assets/transcripts a specific user has worked on.

- Suggested soluntion:  In admin page for a user, link to their actions (like on user profile page) AND be able to search and sort by user in the admin transcriptions page


As a community manager, I want to remove accounts that have not been activated after a certain period of time. I recieve Mailer Daemon email when users have entered their email addresses incorrectly and therefore know that those profiles will never be activated.

- Suggested solution:  Admins are able to filter users by when their account was created and if it is activated so they can be deleted.  Alternately, admins can set up automated deletion of accounts that have not been activated within a certain time window (for example 30 or 60 days)

**Comment by acdha** [comment]
@elainekamlley @lalgee I'm deferring the to-do item for user/item/project counts on the transcription change list until we discuss more what would be useful to display and whether that's the right page for it.

**Comment by VVH** [comment]
This all looks pretty good. Just one little thing now opened as new bug issue #691

**Comment by elainekamlley** [comment]
@VVH You are da 💣 dot com (The kids still stay this right?). @acdha Good work! We can close this issue.
