### ISSUE TITLE
Articulate & document data model

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#209]
Distinguish
- [x]   Entity relationships - campaign-project-item-asset
- [x]     status values

**Comment by colefemeno** [comment]
Distinguish 
- [ ] Entity relationships - campaign-project-item-asset 
- [ ] status values 
- [ ] other filter criteria: recency, active, visible, etc

**Comment by rstorey** [comment]
Go through the UI wireframes. For each wireframe, identify the data elements on the page and where they would come from. Identify which data elements are important for the user interface (things that will be used to sort or filter). Identify which fields would be populated from the loc.gov API (for items) and which fields would be manually populated (by a CM through the Django admin).

**Comment by colefemeno** [comment]
**Campaign**
-  Inactive = UNPUBLISHED
-  Active and Needs Work = PUBLISHED and Open 
-  Active but Completed = Closed
-  _Closed Status determined by the published and completed projects (see projects)_

**Project**
- Inactive = UNPUBLISHED
- Active and Needs Work = PUBLISHED and Open 
- Active but Completed = Closed
- _Closed Status determined by the published and completed items (see items)_

**Item**
-  Inactive = UNPUBLISHED
-  Active and Needs Work = PUBLISHED and Open 
-  Active but Completed = Closed
-  _Closed Status determined by the cumulative status of assets - when completed_ 

**Asset** 
- Bulk status of assets dictated on publish at Item level     
- Inactive = Unpublished
- Active but Unpublished (“Hidden”) = Closed/Complete

- Active but no work so far = Blank (New)
- Active but Needs Work = Edit 
- Active and Ready to Review = Submit
- Active and Ready to Complete = Complete 
- Active but no action can be taken = Read

**Comment by elainekamlley** [comment]
Need to capture Meghan's comment and put it in confluence
