### ISSUE TITLE
Export a large amount of data causes OOM error

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#212]
Steps to reproduce:

1. Load a large campaign with thousands of assets.
2. Provide transcriptions for the assets.
3. Attempt to export as either CSV or BagIt.

Observed behavior:

1. From code review we know that an out of memory error will occur on sufficiently large export in either CSV or BagIt format.

Expected behavior:

1. Be able to export any size campaign / transcription data.

**Comment by acdha** [comment]
Yes – this is expected from the design of the current code. https://github.com/LibraryOfCongress/django-tabular-export streams so it will handle very large CSVs but we need something equivalent for the bags.

**Comment by rstorey** [comment]
I can't reproduce this currently
