### ISSUE TITLE
Validate slug characters

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#214]
Steps to reproduce:
1. Create a campaign and/or a project that has accented non-ASCII characters.
2. Create a campaign and/or a project that has punctuation in it such as parentheses.
3. Browse to those campaigns and projects in the site and check the URLs.

Observed behavior:
1. Unknown

Expected behavior:
1. non-ASCII characters should be fine for URL slugs
2. Punctuation should not be allowed in URL slugs

**Comment by acdha** [comment]
This should just be setting [`allow_unicode=True`](https://docs.djangoproject.com/en/2.0/ref/utils/#django.utils.text.slugify) on our `slugify` calls.
