### ISSUE TITLE
Ensure home page is eligible for caching

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#218]
Steps to reproduce:
1. Set up a website cache for the home page
2. Attempt to use it

Observed behavior:
1. The home page is not cacheable because the top right nav block changes on user login.

Expected behavior:
1. Use javascript front end code to populate the top right nav block so the home page can be cached

**Comment by acdha** [comment]
I think we should merge this with #219

**Comment by rstorey** [comment]
Works for me

**Comment by rstorey** [comment]
Closing as dupe of #219
