### ISSUE TITLE
List of artifacts to document Concordia 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#22]
Below is a list of documentation needed for Concordia:

- [x] One pager: This is a plain language document that explains the platform for various audiences. Can be used on GitHub, in meetings and in presentations.,
- [x] Platform diagram: This maps the entire platform, how data is pulled in, the technical stack and how the platform fits in with the larger library workflows. 

@rstorey @colefemeno

**Comment by colefemeno** [comment]
- [ ] Roadmap 

- [ ] Requirements summary for one pager

**Comment by elainekamlley** [comment]
Good example of repo docs organization: https://github.com/fecgov/FEC

**Comment by elainekamlley** [comment]
Hi folks, in my last job at 18F, code review was documented to create a shared understanding among the developers. Here's an [example]( https://github.com/AlaskaDHSS/EIS-Modernization/blob/master/code-review.md). 

Also, their[ `how-we-work` ](https://github.com/AlaskaDHSS/EIS-Modernization/blob/master/how-we-work.md)page documents the `Definition of Done`,  `Accepting Vendor Work`(18F is the vendor in this case), and `Process`.

**Comment by elainekamlley** [comment]
Most of this is done. Future tickets will be created for additional documentation needs
