### ISSUE TITLE
Pagination code cleanup

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#220]
cleanup task of searching for `request.GET.get("page")` and replacing that view with ListView

**Comment by rstorey** [comment]
From @acdha : If you notice I added a standard pagination include which works with anything which provides template variables matching https://ccbv.co.uk/projects/Django/2.0/django.views.generic.list/MultipleObjectMixin/ so we can use that in ListViews and similar.
ccbv.co.uk

**Comment by rstorey** [comment]
I think this is already done. I couldn't find `request.GET.get("page")` in the code. @acdha can you confirm?

**Comment by acdha** [comment]
I think we can close this as a duplicate of #185
