### ISSUE TITLE
Bulk import

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#226]
Steps to reproduce:
1. Deploy the concordia software with no data in it.
2. Open the spreadsheet that has the initial collections in it.

Observed behavior:
1. It will take you forever to import all of the items into the various campaigns and projects one by one.

Expected behavior:
1. It would be super cool if you could feed the spreadsheet in and get a functional crowdsourcing site out.
2. We also need to capture the original resource ID from the loc.gov API.
3. Sequence numbers for assets should start at 1 instead of 0.
4. Each item needs a representative thumbnail retrieved from the API. This should not be the first image in the item because that is frequently an image of a folder rather than actual content.
5. The importer should save files to S3 instead of local filesystem.

**Comment by elainekamlley** [comment]
Closed with #250
