### ISSUE TITLE
Download transcriptions for a collection from Concordia

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#23]
Acceptance Criteria: 

- [ ]

**Comment by colefemeno** [comment]
As a researcher, I want to download the full text transcription for Clara Barton's Jan-March 1863 diary in csv format from the loc.gov page where I was searching for the journal.

As a student, I want to download an example of what I transcribed during my assignment last week. I only need one page that I transcribed - I want to show my teacher the text for Branch Mickey's report. I don't care if it is JSON or other format, as long as I can print it out.

**Comment by rstorey** [comment]
I believe the preferred approach, at least for now, is to publish completed collection data for download on labs.loc.gov. If this changes, we can reopen the ticket and figure out how we would expose export to end users.
