### ISSUE TITLE
Test page load performance

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#232]
We need a way to measure how long pages on the site take to load for end users, particularly in light of #208 and #160

**Comment by acdha** [comment]
I'd like to get the performance timing data from the user's browser. That might be a question to see if the relevant feature is enabled on our Analytics account.

**Comment by rstorey** [comment]
We've gotten as good as we're going to get with this without a mini project.

**Comment by acdha** [comment]
That project is underway but out of scope for this ticket
