### ISSUE TITLE
Separate container for ElasticSearch indexing

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#234]
We want to feed our data into ElasticSearch, but we want to use a separate task / container for that process so it can run independently of the main app.

**Comment by acdha** [comment]
Any reason why this wouldn’t be a managed ElasticSearch instance with the Kibana option enabled?

**Comment by rstorey** [comment]
It would

**Comment by rstorey** [comment]
I think we still need to run a docker container for this bit, don't we? https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-indexing-programmatic.html

**Comment by acdha** [comment]
We'd need to decide how we're exporting data to it – it could mean a separate container or possibly something like a Celery task.

**Comment by rstorey** [comment]
The first version of this is done
