### ISSUE TITLE
Users can view their own transcription activity

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#24]
Acceptance criteria: 

- [ ]

**Comment by colefemeno** [comment]
I joined as a volunteer in September. It's my 6 month anniversary of transcribing and I want to see how many projects I worked on so I can tweet about it and get my #twitterstorian friends to tag projects with me. 

I'm trying to hit a volunteering requirement for my church. As a volunteer, I need to show my coordinator how many pages I worked on over the last month. It might also be good to see the names of projects and an example image of a page, so they know what kind of work it's been. 

I set myself a new year's resolution to transcribe 100 pages and tag 30 pages each month. I hit my targets for January through April but May got busy. I want to see how many pages I have transcribed and tagged so I can determine what I need to do to reach each goal - and there's only 5 days left in the month!!

As a high school student, my teacher asked us to contribute to 5 pages for each of the 3 tags she created. We were allowed to transcribe or tag but we had to transcribe at least 1 page for each tag. I have to print out a report to give Mr. Thomas on Friday.

As a volunteer, I have great discussions in the forum. I was talking about Abraham Lincoln's correspondence with zippylou (another volunteer) earlier today and want to find the page I worked on a few weeks ago to show them a note in the margin and how I transcribed it. Once I look through what I've done in the past few weeks, I'll share the link for the page in the forum (even though the page is finished now) - I could also share the page from the Library of Congress main website.

I'll admit, as a volunteer, I'm a fairly competitive person and I like to see what I have done in relation to other projects. Looking at the visualization of my work and total contributions in the last month motivates me to do a few more pages this evening.
