### ISSUE TITLE
As a user, if click finish I can not approve a transcription

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#244]
Acceptance criteria: 

- A rule that does not allow a user to mark a transcription as complete if they were the last person to submit it for review

**Comment by rstorey** [comment]
If I submit something for review, I may not mark it complete but I may kick it back into Edit (the button should be Edit).

**Comment by acdha** [comment]
#358 added this — here's what it looks like currently:

1. Anonymous user saves work:

![image](https://user-images.githubusercontent.com/46565/46810116-f7451900-cd3d-11e8-9215-17056fc3692e.png)

2. Anonymous user submits transcription for review:

![image](https://user-images.githubusercontent.com/46565/46810153-0b891600-cd3e-11e8-98aa-a82074bec965.png)

3. A logged in user who is not the user to submit the transcription can accept it or request changes:

![image](https://user-images.githubusercontent.com/46565/46810226-2cea0200-cd3e-11e8-93be-aaffe314d3a5.png)
