### ISSUE TITLE
Button text in transcription page

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#246]
Acceptance Criteria: 

- When a transcription is being edited, the buttons should be Save and Finish.
- When a transcription is being reviewed, the buttons should be Edit and Approve.

**Comment by elainekamlley** [comment]
@jbresner here's the ticket for updating buttons

**Comment by acdha** [comment]
Completed in #358; see the screenshots in https://github.com/LibraryOfCongress/concordia/issues/244#issuecomment-428970936
