### ISSUE TITLE
User registration doesn't work

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#247]
Steps to reproduce:

1. Visit the site and click Register.
2. Fill out the registration form for a new user.
3. Click submit.
4. Log in as the admin user and go to the admin pages.
5. View the list of Users.
6. Log out as admin and try to log in as the user you just created.

Observed behavior:
1. The form reloads and the fields for username and email say that a user already exists with this username / email.
2. The user was created.
3. Cannot log in as the newly created user.

Expected behavior:
1. Users should be able to register.
2. The error messages should not show up unless there really already is a username / email with the same value.

**Comment by elainekamlley** [comment]
Additional observed behavior:, when I try to log in it says `The account is inactive`

**Comment by rstorey** [comment]
This seems to be fixed in the latest build
