### ISSUE TITLE
Modify account confirmation email

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#251]
Steps to reproduce:
1. Visit the site as an unauthenticated user.
2. Complete the registration form and use a valid email address.
3. Wait to receive the email and read it.

Observed behavior:
1. There is HTML source code in the email text.
2. Cannot click any button.

Expected behavior:
1. The account activation email should be plain-text formatted
2. The account activation email should have a link in plain text

**Comment by acdha** [comment]
HTML format is not supported by django-registration — see https://github.com/ubernostrum/django-registration/issues/52 and https://django-registration.readthedocs.io/en/3.0/quickstart.html#django-registration-activation-email-body-txt

In the interests of time, I think we should make that template work as regular text and later come back with a custom send function which will use that as the text alternative and add an HTML version.
