### ISSUE TITLE
Confirm top level navigation

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#253]
Observed behavior: Currently we have: Home, Campaigns, About, FAQ, Account. 

Issue: Challenges and/or a place to access news about the project is not obvious in terms of being a tab. As a user I want to know about the latest features, discoveries and so on from the project team.

Expected/ hoped for behavior: Challenges, Campaigns, About (including FAQ), News, Discuss

Discuss will lead to History Hub **in a new tab**

**Comment by VVH** [comment]
@lalgee should we also add a Teaching Resources tab?

**Comment by lalgee** [comment]
The Ed Outreach folks strongly recommended having a section for teachers that is clearly marked as such.  Maybe "For Teachers" or "For the Classroom"?

**Comment by elainekamlley** [comment]
I think we should keep our top level nav for main user needs and any resource based pages in the footer #265. I like `For the Classroom`. Based on our convo with Ed Outreach, it seems more inclusive of home school and after school programs.

**Comment by colefemeno** [comment]
Confirming Top Level Navigation to be: `About` `Campaigns` `Latest` `Discuss` | `Help`

-  "How To" and "FAQ" roll into `Help`
- `For the Classroom` to the Footer and can be referenced in the FAQ portion of the `Help` Help Center
- `About` is a brief summary of the project - can be referenced in the FAQ portion of the `Help` Help Center
- `Latest` holds Challenge at the top and will include press, release notes, and other updates
