### ISSUE TITLE
Create a "Nothing to transcribe" button within transcription viewer

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#255]
Current: There's no obvious way to register that a page is blank from within the transcription interface.

Expected: 
* As a volunteer I want to be able to to mark a page as blank and swiftly move on to the next task. 
As a community manager I want to see how many pages from a given Campaign have been marked as blank. 
As a user of the data (i.e. a humanities scholar working at scale) I want to be able to strip out all blanks from my dataset.

**Comment by VVH** [comment]
Great design. Thanks @jbresner

**Comment by rstorey** [comment]
I have a number of questions about how this will work. Can we discuss on Monday? Essentially, I'm wondering whether it would be better to use tagging for this and how we would guide the user to tag appropriately in such cases.

**Comment by VVH** [comment]
Based on our sprint grooming talk on October 4th, we've decided to push ahead with this functionality in Sprint 11 or 12 because it makes the coding of some other things easier. Button text should be: "Nothing to transcribe" with a little question mark beside it to bring people to the quick tip tutorial for what we mean by nothing to transcribe.

**Comment by jbresner** [comment]
I left the checkbox in as the UI for a user to mark a page that has nothing to transcribed (vs. using  a button). If it becomes clear that users aren't checking the box needs to enable the "Finished" button then we should consider the additional button OR a modal that appears have the always enabled "Finished" button is clicked asking if the page has nothing to transcribe.

![transcribe-anon-nothingtotranscribe](https://user-images.githubusercontent.com/4275957/46690378-1de54180-cbd0-11e8-86f8-bb1c60ebbf5c.png)
![transcribe-anon-nothingtotranscribe-help](https://user-images.githubusercontent.com/4275957/46690385-23428c00-cbd0-11e8-8795-3666084033f7.png)
![transcribe-anon-nothingtotranscribe-checked](https://user-images.githubusercontent.com/4275957/46690390-250c4f80-cbd0-11e8-98d7-a036b88c5b39.png)

**Comment by acdha** [comment]
This looks good. I'm in the process of updating that view anyway and will roll this into tomorrow's work.

**Comment by colefemeno** [comment]
Looks good - @jbresner @acdha @elainekamlley 
After volunteer checks "nothing to transcribe" box but before they click "Finished," can we have text in the transcription field change to reflect "Nothing to transcribe for this image" or similar (with text still grayed out)?
 
e.g. _As a user, I want to see a visual confirmation of my entry - even when that entry is that there's nothing to transcribe - that I can skim before I select "Finished"_

**Comment by jbresner** [comment]
I was thinking something along those lines. Also, we have to consider what happens if a user enters information into the text field THEN checks the box. We may want to warn the user that their entered text will not be submitted when "Finished" is clicked and give them a chance to uncheck the box.

**Comment by acdha** [comment]
I'm sure someone will check that box by mistake so we'd either want to do a confirmation first or ensure that we display an overlay but don't clear the text field's value.

**Comment by rstorey** [comment]
This is done
