### ISSUE TITLE
AWS deployment environments can't communicate with Sentry

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#259]
Set up VPC peering
Change SentryDSN
Rebuild environments so they use different internal IP ranges

**Comment by elainekamlley** [comment]
This is a security requirement as well. We need to be able to view login attempts from users.

**Comment by rstorey** [comment]
sentry-internal.devops.cloud

**Comment by rstorey** [comment]
I'm not certain but I believe the crowd-test environment should be reporting events successfully to Sentry. Need to test and see. We won't be able to integrate all the environments (we have to pick one for now) until we rebuild them all with different internal IP ranges. I've already prepped the CF templates to do this, but I need to test the templates and then we'll have to update our DNS again. After that, we set up the VPC peering for sentry for all environments.

**Comment by rstorey** [comment]
This is done for now
