### ISSUE TITLE
Revise footer 

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#265]
We have the full scope of the footer - we need to revisit the design and what is communicated in this space. 

A footer provides related navigation and information to other Library of Congress web entities, suggests social media and other places to find information, and communicates up to date information about activity on the site. 

To Do: 

- [x] Reach out to MS to confirm what we absolutely need to keep
- [x] remove links/icons we don't need 
- [x] update links to correct accounts

**Comment by acdha** [comment]
On a more mundane level, many of the links in https://github.com/LibraryOfCongress/concordia/blob/master/concordia/templates/base.html#L94-L134 are broken because they're relative paths intended to link to pages like https://www.loc.gov/connect/. If you want to review these I can fix those at the same time.

**Comment by elainekamlley** [comment]
Reached out to Michelle and we need legal, IG, accessibility & external links disclaimer. We will utilize the other links for navigating on Make Your Mark and going to History Hub. @acdha other than the four identified we can update those links names and links to where they need to go. 

Proposed footer - @colefemeno what do you think?  

Under `follow us`
- Twitter icon that goes to crowd_loc
- Add GitHub??
- Everything else will be removed 

Links: 

- Accessibility
- Legal
- IG
- External link disclaimer
- Contact (goes to MYM contact) 
- Discuss (goes to History Hub)

Fix congress.gov and copyright logos to link

**Comment by jbresner** [comment]
Here are a few footer layouts. I removed the "Follow Us" since it was only ever a requirement on the LOC.gov page (it's actually a separate link). Let me know if you have any thoughts on the mockups.
![footer - v1](https://user-images.githubusercontent.com/4275957/46711941-a4277500-cc1c-11e8-987e-b4e4ba3cc32d.png)
![footer - v2](https://user-images.githubusercontent.com/4275957/46711942-a4277500-cc1c-11e8-9ce3-e26154088247.png)
![footer - v3](https://user-images.githubusercontent.com/4275957/46711943-a4277500-cc1c-11e8-91a9-774575ffe719.png)

**Comment by elainekamlley** [comment]
@jbresner Now that I think of it we may be able to remove congress.gov and copyright. I'll follow up with MS

**Comment by elainekamlley** [comment]
Newsletter link: https://updates.loc.gov/accounts/USLOC/subscriber/new?topic_id=USLOC_175
History hub link: https://historyhub.history.gov/community/make-your-mark/

**Comment by jbresner** [comment]
Cool. If they're not required, I'd recommend also removing them. Here are some additional mockups I did last night without those logos.

![footer - v4](https://user-images.githubusercontent.com/4275957/46741536-39555880-cc73-11e8-8325-f1094803ff8e.png)
![footer - v5](https://user-images.githubusercontent.com/4275957/46741537-39edef00-cc73-11e8-880d-2a9824016201.png)

**Comment by elainekamlley** [comment]
This is the footer we are going with: 

Newsletter link: https://updates.loc.gov/accounts/USLOC/subscriber/new?topic_id=USLOC_175
History hub link: https://historyhub.history.gov/community/make-your-mark/

![image](https://user-images.githubusercontent.com/7362915/46969047-e3bde900-d082-11e8-81c3-f2a4be31457f.png)

**Comment by jbresner** [comment]
I'm not sure Ki has access to this but still placing the files here as a reference...

Here's the mobile mockup of the footer and the icons used as a single sprite.

![footer-mobile](https://user-images.githubusercontent.com/4275957/47038828-71b3d580-d150-11e8-89dc-3e59218998ed.png)
![sprite](https://user-images.githubusercontent.com/4275957/47038829-724c6c00-d150-11e8-9032-9c09198caf3e.png)

**Comment by rstorey** [comment]
![sprite](https://user-images.githubusercontent.com/5270415/47165526-245a7400-d2c8-11e8-8c15-0597a2667e0a.png)

**Comment by rstorey** [comment]
```
<style>
.footer-crowd {
  background-color: #f5f5f5;
  border-top: 1px solid #999;
  padding: 22px 0;
}
@media print {
  .footer-crowd {
    display: none;
  }
}
.footer-crowd-row {
  max-width: 1200px;
  padding: 0 1rem;
  margin: 0 auto;
  box-sizing: border-box;
}
@media (min-width: 769px) {
  .footer-crowd-row {
    display: flex;
    padding: 0 2rem;
  }
}
.footer-crowd-social {
  text-align: center;
}
@media (min-width: 769px) {
  .footer-crowd-social {
    text-align: left;
    padding-right: 20px;
  }
}
@media (min-width: 993px) {
  .footer-crowd-social {
    padding-right: 40px;
  }
}
.footer-crowd-social > h2 {
  font-family: inherit;
  font-weight: 700;
  line-height: 1.2;
  color: #333;
  margin: 0 0 1rem;
  font-size: 1.25rem;
  margin: 0 0 0.75rem;
  font-weight: normal;
}
.footer-crowd-social > h2 small,
.footer-crowd-social > h2 .small {
  font-family: 'Open Sans', Arial, Helvetica, sans-serif;
  font-size: 1rem;
  font-weight: normal;
  line-height: 1;
  color: #333;
}
.footer-crowd-social > h2 small.block,
.footer-crowd-social > h2 .small.block {
  display: block;
  margin-bottom: 2px;
}
a .footer-crowd-social > h2 {
  color: inherit !important;
}
.footer-crowd-social .links-social {
  padding-left: 0;
  list-style: none;
  margin: 0 -6.5px;
  display: inline-block;
  margin-bottom: 0;
}
.footer-crowd-social .links-social > li {
  display: inline-block;
  margin: 0 6.5px;
}
.footer-crowd-links {
  border-top: 1px solid #999;
  border-bottom: 1px solid #999;
  padding: 16px 0;
  margin: 16px 0;
}
@media (min-width: 769px) {
  .footer-crowd-links {
    flex: 1;
    border: none;
    border-left: 1px solid #999;
    padding: 0;
    padding-left: 20px;
    margin: 0;
  }
}
@media (min-width: 993px) {
  .footer-crowd-links {
    padding-left: 40px;
  }
}
.footer-crowd-links > ul {
  padding-left: 0;
  list-style: none;
  font-size: 14px;
  font-weight: bold;
  margin: 0;
}
.footer-crowd-links > ul > li {
  margin-bottom: 5px;
  text-align: center;
}
@media (min-width: 769px) {
  .footer-crowd-links > ul > li {
    text-align: left;
  }
}
@media (min-width: 769px) {
  .footer-crowd-links-aside {
    border-left: 1px solid #999;
    padding-left: 20px;
    padding-top: 20px;
  }
}
@media (min-width: 993px) {
  .footer-crowd-links-aside {
    padding-left: 40px;
  }
}
.footer-crowd-links-aside .links-aside {
  padding-left: 0;
  list-style: none;
  text-align: center;
  margin-bottom: 15px;
}
@media (min-width: 769px) {
  .footer-crowd-links-aside .links-aside {
    text-align: left;
  }
}
.footer-crowd-links-aside .links-aside > li {
  display: inline-block;
  font-size: 13px;
  line-height: 1.1;
}
.footer-crowd-links-aside .links-aside > li:not(:last-child) {
  border-right: 1px solid #999;
  padding-right: 8px;
  margin-right: 5px;
}
.footer-crowd-links-aside .links-intersites {
  padding-left: 0;
  list-style: none;
  margin: 0 -1rem;
}
.footer-crowd-links-aside .links-intersites > li {
  display: inline-block;
  margin: 0 1rem;
}
.footer-crowd-links-aside .links-intersites > li > a {
  display: block;
}
.footer-crowd-links-aside .links-intersites > li > a span {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
@media (max-width: 992px) {
  .footer-crowd-links-aside .links-intersites > li > a {
    margin: 5px 0;
  }
}
.footer-crowd-links-aside .links-intersites > li.intersites-link-congress > a {
  width: 125px;
  height: 30px;
  background-size: 125px 30px;
  background: url(congress-gov.svg) no-repeat;
}
.footer-crowd-links-aside .links-intersites > li.intersites-link-copyright > a {
  width: 175px;
  height: 30px;
  background-size: 175px 30px;
  background: url(copyright-gov.svg) no-repeat;
}
@media (max-width: 768px) {
  .footer-crowd-links-aside .links-intersites {
    text-align: center;
  }
}
.bitmap-icon {
  display: inline-block;
  width: 24px;
  height: 24px;
  vertical-align: text-top;
  background-image: url(sprite.png);
  background-position: -200px 0;
  background-repeat: no-repeat;
}
.bitmap-icon.github {
  background-position: 0 0;
}
.bitmap-icon.twitter {
  background-position: -40px 0;
}
.bitmap-icon.email {
  background-position: -80px 0;
}
</style>
<footer class="footer-crowd">
    <div class="footer-crowd-row">
        <div class="footer-crowd-social">
            <h2>Follow US</h2>
            <ul class="links-social">
                <li class="link-github">
                    <a href="https://github.com/LibraryOfCongress/concordia" title="GitHub">
                        <i class="bitmap-icon github"></i>
                    </a>
                </li>
                <li class="link-twitter">
                    <a href="https://www.twitter.com/Crowd_LOC" title="Twitter">
                        <i class="bitmap-icon twitter"></i>
                    </a>
                </li>
                <li class="link-email">
                    <a href="https://updates.loc.gov/accounts/USLOC/subscriber/new?topic_id=USLOC_175" title="Email">
                        <i class="bitmap-icon email"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="footer-crowd-links">
            <ul class="">
                <li><a href="/contact/">Contact Us</a></li>
                <li><a href="https://historyhub.history.gov/community/make-your-mark/">Discuss</a></li>
                <li><a href="/for-educators/">For Educators</a></li>
                <li><a href="/help-center/">Help</a></li>
            </ul>
        </div>
        <div class="footer-crowd-links-aside">
            <ul class="links-aside">
                <li><a href="https://www.loc.gov/accessibility/">Accessibility</a></li>
                <li><a href="https://www.loc.gov/legal/">Legal</a></li>
                <li><a href="https://www.loc.gov/about/office-of-the-inspector-general/">Inspector General</a></li>
                <li><a href="https://www.loc.gov/legal/standard-disclaimer-for-external-links/">External Link Disclaimer</a></li>
            </ul>
            
            <ul class="links-intersites">
                <li class="intersites-link-congress"><a href="//www.congress.gov/"><span>Congress.gov</span></a></li>
                <li class="intersites-link-copyright"><a href="http://copyright.gov"><span>United States Copyright Office</span></a></li>
            </ul>
        </div>
    </div>
</footer>
```

**Comment by rstorey** [comment]
@acdha mind taking a look at this footer from Ki and see if we want to integrate that now or wait until we review the whole site for responsiveness?

**Comment by acdha** [comment]
There’s definitely a lot to clean up and it needs to be accessible, too. I’m wondering how much we should care about making it consistent with the rest of the site as well.

I can take a pass after lunch.
