### ISSUE TITLE
Develop scenarios for open house user testing

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#269]
Oct. 8th host user testing in the reading room 

- [x] Draft scenarios

**Comment by colefemeno** [comment]
Draft attached - feedback needed! @jbresner do you see any issues in this proposed plan?
[Main Reading Room User Testing Protocol - 04Oct18.docx](https://github.com/LibraryOfCongress/concordia/files/2448285/Main.Reading.Room.User.Testing.Protocol.-.04Oct18.docx)

**Comment by colefemeno** [comment]
To do

- [ ] Evaluation sheet
- [ ] Wireframes capture 
- [ ] Deck & PDF creation 
- [ ] Test devices

**Comment by elainekamlley** [comment]
Summarize user testing result from 10/08
