### ISSUE TITLE
Finalize content for soft launch

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#270]
Refine content and scope down:

- [x] homepage
- [x] about
- [x] faq
- [x] campaigns descriptions 
- [x] quick tips
- [x] notifications/messages
- [x] register for account
- [x] user account page
- [x] contact us
- [x] latest (to include letters to lincoln challenge)
- [x] For educators page

**Comment by elainekamlley** [comment]
@VVH working on a updated spreadsheet based on #346

**Comment by elainekamlley** [comment]
By weds update content for comms meeting

**Comment by VVH** [comment]
Pages created in Confluence/Jira with drafts of Campaign Descriptions (including links etc) and 'Latest' page. New Quick Tips content generated as well.

**Comment by elainekamlley** [comment]
This is done
