### ISSUE TITLE
Prefix S3 storage areas

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#272]
**What behavior did you observe? Please describe the bug**
If we allow Community Managers to upload thumbnails for various entities in the same S3 bucket where the importer puts collection images, clobber could occur.

**What is the expected behavior?**
Use prefixes for everything saved in the S3 bucket(s) for the different areas of the site to prevent overlap. Another option would be to use different S3 buckets.

**Comment by rstorey** [comment]
From @acdha: I’m thinking we either bite the bullet and setup separate storage backend declarations (i.e. adding S3Boto3Storage instances in concordia/storage.py with different bucket names) *or* simply start prefixing things with paths so e.g. everything that the importer saves would be prefixed with “collection-media” or something like that so there’d be no conflict with things like these uploads.
Let’s ticket for that since if you add a file field right now Django will automatically upload it to the `default_storage` so it’ll go on S3 automatically if the site is deployed that way.

**Comment by acdha** [comment]
This will impact our ability to directly serve media through the CDN: CloudFlare doesn't have general-purpose URL rewriting, only hostname changes, so we either need to make the URL paths match exactly (e.g. `/campaign-thumbnails/`, `/project-thumbnails/`, park everything under `/media/` (bad for performance on S3 with lots of files), etc.) or we need to have rewriting occur somewhere else.

**Comment by acdha** [comment]
Since https://crowd-media.loc.gov/ works as a drop-in MEDIA_URL replacement now, I'm inclined to do that initially while we discuss the larger media management strategy

**Comment by rstorey** [comment]
I think we're good on this one since we have separate buckets for exported and imported / uploaded content. Can close this issue?
