### ISSUE TITLE
Asset view raises 500 error

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#274]
**What behavior did you observe? Please describe the bug**
When I click on assets in the item, I get a gateway timed out error or 500 error

**What is the expected behavior?**
When I click the thumbnail that it  brings up a transcribing page with the image to the left. I can begin transcribing

**Comment by acdha** [comment]
@rstorey has hot-fixed the immediate problems. I'm working on a larger refactor in https://github.com/LibraryOfCongress/concordia/tree/refactor-asset-view which will also include the UI improvements we need.

**Comment by rstorey** [comment]
This is fixed now in the dev site.
