### ISSUE TITLE
Connecting Users to Discussion via History Hub

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#284]
**Is your feature request related to a problem? Please describe.**
This is a refined issue for connecting Concordia to History Hub and supporting discussion and information seeking in a forum. Replaces #50 

**Describe the solution you'd like**
As a volunteer, I want to discuss something I've transcribed or reviewed. 
As a volunteer, I want to ask a general question about Make Your Make so that I can better understand what I'm working on.
As a volunteer, I want to communicate with other volunteers and the Community Managers. 

**Describe alternatives you've considered**
Discussion occurs in public facing social media spaces. 
Discussion is 1-to-1 via email with Community Managers.
Discussion is possible in History Hub but not connected to Concordia 

**Additional context**
Desired:
- [x] I should be able to access History Hub from the navigation, footer, transcription page, About/FAQ page, and Contact Us form.
- [ ] I should be able to categorize my question in the Contact Us form to be prompted to discuss in Hisotry Hub.
- [ ] I should be able to tell what kind of response I will get based on the way I am seeking to discuss what I have encountered.

**Comment by elainekamlley** [comment]
Here's the link! https://historyhub.history.gov/community/make-your-mark/

**Comment by lalgee** [comment]
I've emailed Kelly to set a time for backend/customization walkthrough.  Shortly after that I propose we have a spike to determine 1) where and how we want to link between HH and MYM and 2) workflow/management to propose for community managers and coordination w/MSS and AskALibrarian. Maybe Thurs/Fri once @colefemeno is available.

**Comment by rstorey** [comment]
I think this is done?

**Comment by elainekamlley** [comment]
yup! #389 is the last thing but we can close it
