### ISSUE TITLE
Refine Contact Us page

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#285]
**What behavior did you observe? Please describe the bug**
- The language is very direct. Need to make it more user friendly. 
- Add content to get to History Hub
- Begin with options to self-service in Help Center or History Hub

**What is the expected behavior?**
As a user, I want to contact a community manager with a pressing question via the Contact Us form so that I can get a swift reply. It should also include: 
- Friendlier language for the different fields
- Contact Us form would autopopulate my email and tell CM what page they are referring to
- I should be able to categorize my question in the Contact Us form to best route the question.
- Some information telling me about History Hub

**Got screenshots? This helps us identify the issue**

![contact](https://user-images.githubusercontent.com/7362915/46110939-4114f780-c1b3-11e8-9504-3e9358f6cfcb.PNG)

**Additional context**

**Comment by acdha** [comment]
@elainekamlley you can send a pull request against https://github.com/LibraryOfCongress/concordia/blob/21bc9c11817cd95683f818e38cae7c6bac646b56/concordia/forms.py#L94-L130 with label changes.
