### ISSUE TITLE
Email notification reminders to inactive users

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#29]
Roughly 10% of registered users have not activated their accounts. Prompt and provide users another opportunity to activate. 

Acceptance criteria: 

- An email with a message reminding they registered that includes a fresh activation link after 48 hours of initial sign up

**Comment by rstorey** [comment]
Can't we use GovDelivery for this?

**Comment by acdha** [comment]
Wouldn't we need a way to select the inactive user list to send that email?

**Comment by rstorey** [comment]
That's possible currently through the Django admin.

**Comment by elainekamlley** [comment]
closing for dupe #662
