### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#292]
We need a robots.txt file for the site.

**Comment by acdha** [comment]
We can either use static files or something like `django-robots` if we want the ability to update it through the admin:

https://django-robots.readthedocs.io/en/latest/#installation

If we went the latter path it might be worth seeing how hard it'd be to serve a default `Disallow: /` which only production would override to opt-in for indexing. On WDL, I used a slightly more complicated version of this approach:

```python
def robots_txt(request):
    """Serve static responses for robots.txt based on the hostname"""

    if request.get_host() == 'www.wdl.org':
        with open(os.path.join(settings.STATIC_ROOT, 'robots.txt')) as f:
            txt = f.read()
    else:
        txt = 'User-agent: *\nDisallow: /\n'

    return HttpResponse(txt, content_type='text/plain')
```
