### ISSUE TITLE
Create the relationship of statuses between assets/item/project

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#293]
Acceptance criteria: 
- [ ] Logic that establishes the relationship of project being done. Example: 
- If all assets in an item are approved (completed) then the item is done. 
- If all items in a project are done, then the project is done.

**Comment by acdha** [comment]
With #358 this is technically satisfied but this ticket seems like it's missing the tie-in to the UI where we actually display these statuses – e.g. on the campaign list, are we filtering the completed projects into a separate section?

**Comment by acdha** [comment]
See #222
