### ISSUE TITLE
Revise projects page mocks to include resource panel

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#294]
As a user I want to know more information about this collection so that I can understand the subject I am transcribing. 

As a user I find this subject facinating and want to know more like a timeline of events so that I can put into context the items I am transcribing. 

Acceptance criteria: 
- [ ] In the projects page of a campaign - a resource section or side panel that include curated links back to loc.gov 
- [ ] Community managers to confirm what goes in this section. Example: bio, timeline, about this collection, etc.

**Comment by VVH** [comment]
To give some examples of links @jbresner. 

Barton:

- Learn more: [https://www.loc.gov/collections/clara-barton-papers/about-this-collection/]
- Timeline: [(https://www.loc.gov/collections/clara-barton-papers/articles-and-essays/timeline/)]
- Blog:  [https://blogs.loc.gov/teachers/2015/02/clara-bartons-papers-at-the-library-of-congress-personalizing-womens-history-month/]
- Publications: [https://catalog.hathitrust.org/Record/001132212]

Lincoln: 
- Learn more: [http://hdl.loc.gov/loc.mss/collmss.ms000005]; 
- Timeline: [https://www.loc.gov/collections/abraham-lincoln-papers/articles-and-essays/abraham-lincoln-and-emancipation/timeline/] 
- Blog [https://blogs.loc.gov/loc/2017/11/new-online-abraham-lincoln-papers/]

Parks: 

- Learn more: [https://www.loc.gov/collections/rosa-parks-papers/about-this-collection/]
- Timeline: [https://www.loc.gov/collections/rosa-parks-papers/articles-and-essays/timeline/] 
- Essay: "Beyond the Bus" [https://www.loc.gov/collections/rosa-parks-papers/articles-and-essays/beyond-the-bus/]
Video: [https://www.loc.gov/collections/rosa-parks-papers/articles-and-essays/collection-video/]

Rickey: 

- Learn more: https://www.loc.gov/collections/branch-rickey-papers/about-this-collection/
- Timeline: https://www.loc.gov/collections/branch-rickey-papers/articles-and-essays/timeline/
- Blog: https://blogs.loc.gov/loc/2017/04/play-ball/ 

Terrell: 

-  Learn more: https://www.loc.gov/collections/mary-church-terrell-papers/about-this-collection/; 
-  Timeline: [https://www.loc.gov/teachers/classroommaterials/presentationsandactivities/presentations/civil-rights/)]
- Related resources: https://www.loc.gov/collections/mary-church-terrell-papers/about-this-collection/related-resources/

William Oland Bourne:

- Learn more: https://www.loc.gov/collections/wm-oland-bourne-papers/about-this-collection/
- Timeline: https://www.loc.gov/collections/wm-oland-bourne-papers/articles-and-essays/timeline/
-  Essay: https://www.loc.gov/collections/wm-oland-bourne-papers/articles-and-essays/soldiers-friend-and-left-handed-penmanship-contests/
