### ISSUE TITLE
Community managers and Product owner training on reporting function

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#297]
**Is your feature request related to a problem? Please describe.**
Training for community managers and product owners on reporting function. 

As community manager, I would like to know how to log in to the reporting function so that I can generate reports for our stakeholders

**Describe the solution you'd like**
Be able to go to a dashboard through a URL. I can go to and login to the reporting side of Make Your Mark

**Additional context**
We have a list of reports CM need to generate. We can list them here to make sure they are covered.

**Comment by elainekamlley** [comment]
Kibana docs: https://www.elastic.co/guide/en/kibana/current/tutorial-sample-data.html

**Comment by rstorey** [comment]
There's a new confluence page which has a link to the Kibana dashboard. I upgraded it to the latest version and loaded the sample flight data so we can go through the tutorials hands-on. I ticketed #900  for remaining issues, including adding the link in the Django admin (currently the link is available on the confluence page). Please reopen this ticket if there are still outstanding things to handle, or add them to #900.
