### ISSUE TITLE
Cant delete campaign/project/item

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#303]
**What behavior did you observe? Please describe the bug**
When I try to delete a campaign, a 502 bad gateway error message 

**What is the expected behavior?**
When I pick a campaign/project/item to delete and click go or the delete button, I get a "Are you sure you want to delete" message and when click yes, it gets deleted.

**Comment by elainekamlley** [comment]
A lot. I picked all campaigns to clear them out and that raised 502. So then I tried to delete all of Barton and that also raised 502. I didn't try deleting a single item.

**Comment by acdha** [comment]
Okay, that's probably it.

**Comment by acdha** [comment]
Which cluster was this?

**Comment by elainekamlley** [comment]
Cluster? Where was I testing this? I was doing these actions on crowd-stage

**Comment by acdha** [comment]
This should be fixed when @rstorey deploys the updated ECS config with larger memory allocations

**Comment by rstorey** [comment]
Please retest @elainekamlley and let me know if it still doesn't work.

**Comment by rstorey** [comment]
Fixed
