### ISSUE TITLE
Truncate/read more functionality for Campaign Descriptions

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#314]
Although the campaign descriptions and call to action should be short and pithy, we're already receiving long descriptions from curator-colleagues. 

**Proposed solution**
Only show first 3-4 lines of a Campaign Description, but provide a read more arrow/drop down to give more information for users so they don't necessarily have to leave MYM to learn more.

**Alternatives considered**
Dramatically cut down CDs, but lose context and make it so more people leave to go to P1 or elsewhere.

**Additional context**
In the truncated view show the related links i.e. 'About', 'Timeline' etc.

**Comment by elainekamlley** [comment]
The team discussed and have revised scope. Closing ticket.
