### ISSUE TITLE
Make transcriptions useful for machine learning and automated text recognition

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#316]
**User story**
Xi works in a fast-paced research Lab at Gogglesoftappleface and wants to train their algorithms to recongize 19th century era handwriting. They need transcriptions and the Make Your Mark material is a perfect fit. They also need the positional data of each line of text on the page in order to train their algorithms most efficiently and accurately. (see real example with Shakespeare's World data which sadly missed out the fact that there is positional data...https://collation.folger.edu/2018/09/computer-aided-transcription/) 

**Change to current MYM instructions (content):**

Volunteers should be asked to mimic the line breaks in the original material they are transcribing as much as possible, but not getting hung up on edge cases like insertions over the line. 

**Change to tool (functionality of transcription interface and export)**

Capture line breaks (people hitting enter) and don't scrub that from the export data in csv or whatever else.

**Comment by VVH** [comment]
Thoughts @colefemeno? I realized yesterday that without positional data our transcriptions will be less useful to the automated text recognition community.

**Comment by colefemeno** [comment]
Sounds like a great way to start! Let's develop some strategies for: 
- evaluating adoption by volunteers (i.e. how do they respond to and implement the ask)  
- dialogue on effectiveness for HTR
- what, if any, impact on returning data for asset image level view in loc.gov 

@vvh can we put time on the calendar either just before or post-launch for plan to evaluate and test outcome?

**Comment by acdha** [comment]
I share the concern that position information will reduce the value of this data. One of the challenges will also be that we don't have a way to handle separate text blocks on the same line(s) — we don't have the deluge of newspapers which NDNP has but since humans can write anywhere on a piece of paper the odds are certain that at some point they did something really hard to represent.

**Comment by VVH** [comment]
Just checking @acdha you are in favor of us trying to capture positional information but concerned the above proposal doesn't go far enough? I think that it's hard to catch the edge cases, so as a first pass, let's get the low-hanging, but abundant fruit of main body text. We can talk soon about ways of capture the weird (common) edge cases ie marginalia.

**Comment by acdha** [comment]
I'm wondering about the status of this issue — it's definitely something we want to cover but it's not really at the stage where development can start. Maybe we should move this into the planning discussions so we can start fleshing out concrete tickets?

**Comment by VVH** [comment]
I think this ship has sailed at least in terms of getting positional data. Next best thing would be for people to take the transcriptions, rework them for the ground truth for their own experiments or training data, and leave it at that.
