### ISSUE TITLE
Review & document UI wireframes for import & editing

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#319]
_Originally posted by @rstorey in https://github.com/LibraryOfCongress/concordia/issues/209#issuecomment-422990852_

For each wireframe, document:

- [ ] identify the data elements on the page and where they would come from
- [ ] identify which data elements are important for the user interface (things that will be used to sort or filter)
- [ ] identify which fields would be populated from the loc.gov API (for items)
- [ ] which fields would be manually populated (by a CM through the Django admin)

**Comment by elainekamlley** [comment]
@colefemeno is this still a relevant ticket?

**Comment by colefemeno** [comment]
@elainekamlley Yes, I think this is a backlog issue that needs refinement where the outcome is improving Admin view & task-based functionality for campaign/project management
