### ISSUE TITLE
Build out MYM Help Center

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#341]
Basic pages exists but here is remaining work:

- [x] Breadcrumb for all static pages 

Help center page: 
- [x] Large call to action for welcome guide
- [x] Uniform cards for Guides section
- [x] Accordion for FAQ

![help center](https://user-images.githubusercontent.com/7362915/46969500-3b108900-d084-11e8-8de1-255d59883a2a.png)

- [x] Navigation for internal guides: 

![help center article](https://user-images.githubusercontent.com/7362915/46969509-4663b480-d084-11e8-8781-a718e3fac332.png)

**Comment by jbresner** [comment]
@rstorey - here are two versions of the header image for the Help Center page—one with the overlay mask and one without. I'm not if you have a preference but sometimes the overlay mask is added as CSS (if that's the case, the specs would be:

```
.Rectangle {
  width: 956px;
  height: 310px;
  opacity: 0.65;
  background-color: #000000;
}
```

![banner-with-mask](https://user-images.githubusercontent.com/4275957/47042656-dc1d4380-d159-11e8-8a33-3c9507f3e01c.jpg)
![banner](https://user-images.githubusercontent.com/4275957/47042657-dc1d4380-d159-11e8-951b-5bfd0a830cd2.jpg)
