### ISSUE TITLE
Revise content mapping for campaigns, projects, and items view

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#346]
This is to revise how we are mapping content from the importer. 

- As a community manager, I import large sets of campaign content using the bulk importer using these headers: 

1. Campaign title
2. Campaign short description
3. Campaign long description
4. Link order 
5. Link title
6. URL 
7. Project title
8. Project description 
9. Item URLs

- As a community manager, I need the content in the spreadsheet to map to the different sections across campaigns and projects pages
- As a community manager, I would like to update it in the admin dashboard so that I can make any last minute updates

### All campaigns page 
![campaign](https://user-images.githubusercontent.com/7362915/46505512-48658200-c7ff-11e8-9988-21942d0aa721.PNG)

### Projects page of a single campaign

![singlecampaignpage](https://user-images.githubusercontent.com/7362915/46505632-af833680-c7ff-11e8-9ce4-eb932036b25f.PNG)

### Items page of a single project
 
![projectview](https://user-images.githubusercontent.com/7362915/46505493-38e63900-c7ff-11e8-8ad9-848bf83f36b3.png)

**Comment by elainekamlley** [comment]
4/5 may need to change in the spreadsheet based on the design laid out in #294

**Comment by acdha** [comment]
This is going to involve a couple of database model changes. We should get more clarity on 4/5 — those are on the Campaign and the idea is that those are the title & link to an outside information page? Are they required? How confident are we that there is only going to be one pair?

**Comment by VVH** [comment]
If the space could be flexible to accommodate 2-4 links, that would be good.

**Comment by acdha** [comment]
Okay, so we'll add a (title, url) storage system to campaigns. Do we have needs to force ordering of those links (other than, say, alphabetical by title)? No thumbnails, right? Are we doing this for any other object type such as a Project or Item?

**Comment by elainekamlley** [comment]
Learn more (about this collection) and timeline are the most consistent and will be, I think the other two are supplemental

**Comment by acdha** [comment]
@elainekamlley does that mean we do need to have a way to specify ordering?

**Comment by elainekamlley** [comment]
Yes. Learn more and timeline will always be 1 and 2 but other links don't need a rank or order

**Comment by acdha** [comment]
And we're not adding this for Projects or Items, correct?

**Comment by elainekamlley** [comment]
Correct - just campaign level

**Comment by elainekamlley** [comment]
@acdha what do you think is the best solution to handle tumbnail images for Campaigns and Projects? 

Potential options: 
For campaigns - upload via django admin 
For projects - can start with upload from admin but eventually randomly pick an image from the items?

**Comment by acdha** [comment]
I was thinking about uploads for both on the theory that it gives the option of customization even if we use a project image – e.g. cropping, rotating, contrast-enhancement, overlaying text, etc.

**Comment by elainekamlley** [comment]
Yea upload sounds good. I'll create a separate ticket for that.

**Comment by VVH** [comment]
@elainekamlley one little tweak to the above for @jbresner 's sake: number 8 would correspond to what is currently labeled 7, and 6 should be 6/7. Right?

**Comment by rstorey** [comment]
I have omitted the link order / title / URL from this pass. So basically all that was needed was to add the campaign short description and use that on the campaigns page. See #361

**Comment by rstorey** [comment]
This is done
