### ISSUE TITLE
Simplify ALB configuration

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#350]
Currently we're setting up a default rule to a target group which doesn't work:

https://github.com/LibraryOfCongress/concordia/blob/master/cloudformation/infrastructure/load-balancers.yaml#L36-L44

The service still works because we add a /* path pointing to the group which is setup as part of the ECS service:

https://github.com/LibraryOfCongress/concordia/blob/master/cloudformation/services/concordia-service/service.yaml#L148-L173

I think the way to resolve this might just be not to create a listener at all in load-balancers.yaml so the one created by the concordia-service will be the default and only listener.

**Comment by rstorey** [comment]
Except you can't create a listener with zero rules, as far as I know.

**Comment by acdha** [comment]
I had to create a load balancer with no listeners and then let the app stack add the first (only) listener

**Comment by rstorey** [comment]
Ah ok. I know if you try to delete all the rules through the console UI, it won't let you do that.

**Comment by rstorey** [comment]
This is done
