### ISSUE TITLE
Add beta to logo

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#367]
As a user, I want to see a banner at the top of the screen that lets me know that this site is beta

**Comment by jbresner** [comment]
![header beta](https://user-images.githubusercontent.com/4275957/46829082-d21acf80-cd6a-11e8-9bc9-4f540b37d092.png)

**Comment by rstorey** [comment]
![loc-logo-make-your-mark](https://user-images.githubusercontent.com/5270415/47045640-4edded00-d161-11e8-9e69-b74c7062ff15.png)
![loc-logo-crowd](https://user-images.githubusercontent.com/5270415/47045642-4edded00-d161-11e8-9766-e32d1efbea0c.png)
