### ISSUE TITLE
UI updates - Asset View

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#372]
**UI updates - Asset View** 
These UI updates are organized based on where they occur, from the top of the Asset View wireframe to the bottom

**Notification of someone on the page** 
- [x] Update the banner with a message that someone is on the page
In page use Acceptance Criteria: When a visitor arrives on a page and someone else is already on that page, the visitor gets a message indicating someone is already working on that page and they should try to find a new page. Suggested language: "Someone else is already working on this image. You can help by transcribing a new page [link] or you can come back to review this page later." 

**Moving between images: Previous and Next Buttons**
- [x] Make Previous and Next buttons always visible
- [x] Make Previous button inactive when on first asset in an item
- [x] Make Next button inactive when on last asset in an item
Acceptance criteria: As a user, I want to know if there are additional pages in this item.  Previous and next buttons should both always be visible on the transcription interface, just grayed out if there is not a page for them to go to.

**Transcription Field** 
- [x] Transcription field size should be the same as registered field size - large field - note: appears to be an issue with Chrome.
- [ ] Make transcription field adjustable

**Nothing to Transcribe**
- [x] Nothing to Transcribe button
Acceptance criteria: When a user hits the Nothing to Transcribe button, the field should be populated with a message that reads "Nothing to transcribe in this image"
- [ ] Nothing to transcribe checkbox should have a hover message (see #368 )
- [x] If someone has transcribed on the field and then click the Nothing to Transcribe button, they should get a modal that warns them that this content will be lost 

**Button Labels in Review Task**
- [x] Change "Request Changes" to "Edit"
- [x] Switch position of Accept and Edit button to be Edit on left and Accept on right

**Notifications: Save, Submit, and Accept** 
- [x] Save Notifications should remain a banner as currently in crowd-test.loc.gov
- [x] Submit and Accept Notifications should be modal as in mocks  https://github.com/LibraryOfCongress/concordia/issues/286 
- [x] Notification should occur on the page on which the user has performed the task
- [x] Automatically reload to show the changed state and what actions are now available to me (as is a notification shows up but the page stays the same).
Acceptance criteria: User receives recognition that save, submission, or accept has been received by the system while they are still on the page by the system and is offered another page 

**Can't save tag**
- [x] When I add a tag and hit save, a banner comes up saying "Unable to save your tags"

**Contact a Manager Button**
- [x] Change label to "Questions?"
- [x] Contact button should always be displayed as a button (not just text)
- [x] Contact button has a scrollbar (in Firefox) - possibly is for the tags field
- [x] Contact button should be accessible above the fold
See this screenshot from Firefox
![rickeyassetpage](https://user-images.githubusercontent.com/31018169/46837422-4eb9a800-cd83-11e8-9b4a-57c989b4e987.png)

**Comment by colefemeno** [comment]
@cadams I see a small field in crowd-test on Chrome. Adding a screenshot from @elainekamlley 
![screen shot 2018-10-12 at 1 48 16 pm](https://user-images.githubusercontent.com/31018169/46885406-e40d7880-ce25-11e8-9ff7-7034f38b4958.png)

But I see a large field on Firefox 
![firefoxlargetransfield_12oct18](https://user-images.githubusercontent.com/31018169/46885471-14551700-ce26-11e8-8176-42d596c43024.PNG)

**Comment by acdha** [comment]
I'm tracking progress on these changes with screenshots in #379

**Comment by acdha** [comment]
Does “Make transcription field adjustable” mean removing the rule which prevents it from being resized?

**Comment by acdha** [comment]
@colefemeno @rstorey I've checked off the items which are complete as of #379. Do we want to leave that branch open until we finalize everything on this list or do we want to do a review of what's there and merge it so it rolls out to crowd-test sooner?

**Comment by acdha** [comment]
Maybe we just plan on merging this branch multiple times as we hit stable points?

**Comment by rstorey** [comment]
Sure, that's fine. I already merged, crowd-dev is already refreshed. I tagged it as well so we can deploy it to crowd-test.

**Comment by elainekamlley** [comment]
As per discussed this morning change `Transcription Tips` tab/button to `Quick Tips`

**Comment by elainekamlley** [comment]
It'll be `Questions?`. That will go to the self service support page that is not created yet. That is captured in #389

**Comment by acdha** [comment]
Both are in #394

**Comment by acdha** [comment]
@jbresner there's now a basic guard for entering text and also checking “nothing to transcribe” in #394:

https://www.dropbox.com/s/uoghcja9i550r1x/Screenshot%202018-10-15%2015.01.15.png?dl=0

I'm wondering whether we want to defer that until they hit the save button or make the checkbox control it so there's immediate feedback: i.e. when checked, you get a warning if there's text and based on your answer the text area is disabled.

**Comment by colefemeno** [comment]
@acdha @jbresner @elainekamlley Let's go with immediate feedback as a swift visual prompt about what will happen to any content in the field

**Comment by acdha** [comment]
#394 now has a basic modal for successful submission:

![screenshot_2018-10-15 crowd mss859430138-16 rosa parks papers letters from children](https://user-images.githubusercontent.com/46565/46977016-03600c00-d099-11e8-8135-f11381694ec3.png)

One question that raises is what we consider the primary action on that dialog – tagging, going to the next page, or do we mark both of them as default (i.e. not orange) since they're equally valid?

**Comment by acdha** [comment]
Also, note that I used “Continue Tagging” instead of the generic close on that dialog – I was curious how it would feel with button text matching the suggested action since we already have a default close button in the upper right corner (not to mention hitting escape or clicking outside of the modal).

**Comment by jbresner** [comment]
I like it. I might switch the button order so that the sentence order (add tags or go to a new page) matches the button order (go to a new page or add tags).

**Comment by acdha** [comment]
There's now a modal for the review results, too:

![screen shot 2018-10-15 at 17 00 00](https://user-images.githubusercontent.com/46565/46978171-3061ee00-d09c-11e8-8439-0c9ca03d0fe6.png)

One gap in the checklist above: it specifies that accepting a transcription should use the modal but what about rejecting it? The screenshot above attempts to handle both cases but it seems like we might want to have tailored text for both options.

**Comment by acdha** [comment]
@jbresner Here's what it looks like with the button order for a successful submission swapped:

![image](https://user-images.githubusercontent.com/46565/46978307-99e1fc80-d09c-11e8-96fc-2f00460fa60b.png)

**Comment by acdha** [comment]
@colefemeno “Nothing to transcribe checkbox should have a hover message” — how do we want to capture that we're deferring the popover help until someone has time to wordsmith it?

**Comment by jbresner** [comment]
Looks good. Not sure if it's my eyes but those oranges look like they're changing. The LOC orange we've been using is #FC4C02.

**Comment by acdha** [comment]
Good eyes: we’re using the primary color variable defined here which appears to be brighter:

https://github.com/LibraryOfCongress/concordia/blob/master/concordia/static/css/base.css

**Comment by acdha** [comment]
For the modals, we'll de-emphasize the continue tagging button, change the text to “Add Tags”, and set `justify-content: around` on the button row

**Comment by elainekamlley** [comment]
Closing due to most of the work finished. Additional tickets to be add to or made for larger work.
