### ISSUE TITLE
CSS cleanup

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#374]
Bring CSS more in line with Bootstrap 

https://github.com/LibraryOfCongress/concordia/pull/362#discussion_r224589595

https://github.com/LibraryOfCongress/concordia/pull/362#discussion_r224589792

https://github.com/LibraryOfCongress/concordia/pull/362#discussion_r224589866

**Comment by rstorey** [comment]
See #362

**Comment by acdha** [comment]
I'm voting that we close this issue now since the most significant changes have been made and we can continue to incrementally improve things as new work touches particular files

**Comment by rstorey** [comment]
Agree
