### ISSUE TITLE
Admin importer changes

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#381]
@rstorey some things I noticed when working in the importer for the demo 

- [x] Still getting a 500 error when doing a bulk import. The initial thought as to why, was that there was no project description in the spreadsheet. I added p. description and still got a 500 error. Still not sure why. However the first line in the spreadsheet was imported.  Could sit down with you and do a walk through. 
- [x] Implement hierarchal publishing at the item level to publish all assets in an item. CMs may not want to publish every item in a project but every asset in an item should. 
- [x] Add project description field in the project admin 
- [x] Map the project description to the project page

**Comment by rstorey** [comment]
Did you try deleting all the blank lines that were in your test spreadsheet? There were over a thousand lines in there.

**Comment by rstorey** [comment]
Nevermind - I found the reason is that the project titles are too long (or the way we're creating slugs which have a limit of 80 characters needs to be adjusted). Once I reduced the length of the project titles, I was able to get your spreadsheet to import in crowd-dev.

**Comment by elainekamlley** [comment]
Ohhhhh, ok. Mind making that update on the instructions? We'll make adjustment on our end.

**Comment by elainekamlley** [comment]
Nah, project titles should be short. The project description will provide more context
