### ISSUE TITLE
Configure Kibana for community manager reporting

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#385]
Consolidating many tickets into one. 

User story: 
As community managers, I need to be able to report on the activity on Make Your Mark so that I can communicate to stakeholders and our audiences various updates on the project. 

Acceptance criteria
Community managers join or be invited to Kibana, a GUI interface, to generate reports: 
- Based on time period by year, quarter, month, week, day or set own date range 
- How many pages have been transcribed
- The quality of the transcriptions
- by campaign 
- How many transcriptions are back in P1
- with dynamic visualizations
- on page status and task needed ex. How many pages are in review and what is the average time a page is in review.

**Comment by lalgee** [comment]
As a community manager I need to be able to find the assets/transcripts a specific user has worked on.

- Suggested soluntion:  In admin page for a user, link to their actions (like on user profile page) AND be able to search and sort by user in the admin transcriptions page


As a community manager, I want to remove accounts that have not been activated after a certain period of time. I recieve Mailer Daemon email when users have entered their email addresses incorrectly and therefore know that those profiles will never be activated.

- Suggested solution:  Admins are able to filter users by when their account was created and if it is activated so they can be deleted.  Alternately, admins can set up automated deletion of accounts that have not been activated within a certain time window (for example 30 or 60 days)

**Comment by acdha** [comment]
@lalgee Those are good issues but they should probably be in something like #203 since the functionality is for the Django admin rather than Kibana

**Comment by elainekamlley** [comment]
Ah yes, this is my bad. I led @lalgee astray! Moved the comments over to #203

**Comment by rstorey** [comment]
We need to break this up into smaller tickets for reports that aren't existing / available in the current ElasticSearch indexes. There's also the new site report functionality which provides some of these numbers. I need to automate the process of getting the DB dump and updating the ES indexes. For now, it's a manual process which I can do weekly or on request.

**Comment by rstorey** [comment]
So the main acceptance criteria - setting up a Kibana instance accessible to CMs - has been done. As far as these:

> Based on time period by year, quarter, month, week, day or set own date range

This comes with Kibana by default.

> How many pages have been transcribed
This is available in Django admin site report.

> The quality of the transcriptions
How is this supposed to be calculated programatically?

> by campaign
Search capabilities come with ES / Kibana
Filtering / slicing / dicing  can be done in Excel on the Django admin site report

> How many transcriptions are back in P1
This isn't something we track in our own data currently. I'd like to make this a separate ticket.

> with dynamic visualizations
Comes with Kibana by default

> on page status and task needed ex. How many pages are in review and what is the average time a page is in review.
The number of pages in review is available in the Django admin site report.
Let's please make a separate ticket for determining the length of time an asset has a particular status. I might need to add a new database table to do that.
