### ISSUE TITLE
Full screen doesn't work on tablet

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#415]
This is something we already know, but I'm logging it in case we have time to address it in future. 

This is an issue raised at an open house. Not sure details of what the user saw/experienced.

**Comment by acdha** [comment]
Can we reproduce this on anything? Some device / browser combinations don't allow fullscreen mode and others have a confirmation which people sometimes miss.

**Comment by elainekamlley** [comment]
On apple products, iPhone & iPad, using both safari and chrome does not work 
Works on Firefox and Chrome using Android

**Comment by acdha** [comment]
#528 is going to be as much as we can do on this since iOS doesn't support fullscreen mode at all.
