### ISSUE TITLE
Use dynamic port mapping in ECS

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#420]
https://aws.amazon.com/premiumsupport/knowledge-center/dynamic-port-mapping-ecs/

Currently our tasks are defined to match the host port with the container port. This isn't necessary - we should probably use dynamic port mapping.

**Comment by acdha** [comment]
I don't think this will matter with FarGate since each container gets a virtual network interface

**Comment by rstorey** [comment]
Works for me
