### ISSUE TITLE
Enable HTTPS redirects on deployment 

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#427]
We should enable the Django setting to automatically redirect to HTTPS once we update the CloudFormation template to setup HTTPS listeners by default.

**Comment by rstorey** [comment]
The application load balancer can actually do this. I changed the configuration to perform the redirect for the existing environments. Still need to automate the certificate bit and https listener rule in cloudformation templates.

**Comment by rstorey** [comment]
https://forums.aws.amazon.com/message.jspa?messageID=861188
