### ISSUE TITLE
Automated https setup

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#429]
Currently the process for setting up https is manually performed. We should automate putting the cert into ACM and setting up the load balancer listener rule.

From #395

**Comment by acdha** [comment]
For a first pass, let's just use a simple sub rule for the existing IAM certs using the public hostnames. That avoids the policy issues getting permission to use ACM and is available now using this pattern:

`"arn:aws:iam::${AWS::Account}:server-certificate/[FULL HOSTNAME]`

**Comment by rstorey** [comment]
What about situations where we're deploying to an environment that doesn't have a cert (doesn't have a DNS entry)? Or should we just not do that? I usually don't test the deployment code on any of the environments where other people might be working because it takes the site down.

**Comment by acdha** [comment]
I'm thinking a) we don't do that and b) if someone does get that error we tell them to make sure they have an IAM cert with the same hostname as they set in the appropriate CloudFormation property. We need this for #392 anyway.

**Comment by rstorey** [comment]
Okay, yeah you're right. So that needs to be added to the master template as a Parameter then. Maybe we should switch from secrets manager to ssm while we're making another round of changes to the deployment stuff.

**Comment by rstorey** [comment]
When we implement this it should include #427 as well at the ALB level.

**Comment by rstorey** [comment]
This is done
