### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#440]
**What behavior did you observe? Please describe the bug**
See screenshots

![screen shot 2018-10-19 at 12 40 13 pm](https://user-images.githubusercontent.com/5270415/47231990-740a6f80-d39c-11e8-9679-44594edaa0ad.png)
![screen shot 2018-10-19 at 12 39 42 pm](https://user-images.githubusercontent.com/5270415/47232002-7a98e700-d39c-11e8-9880-80b59c5959af.png)

**Comment by rstorey** [comment]
For the second screenshot, I was on the last page of the project item list which had only one item to display.

**Comment by acdha** [comment]
Do you have a way to reproduce the first screenshot?
