### ISSUE TITLE
Find a new page should exclude current page from set of potential pages

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#441]
**How can we reproduce the bug?**
1. Import a collection and publish everything.
2. Make sure no one else is logged into the site.
3. Go to a random asset page in the collection.
4. Click Find a new page.
5. Click Find a new page again.

**What behavior did you observe? Please describe the bug**
The page I was on refreshed and I didn't go anywhere new.

**What is the expected behavior?**
I expected to go to one of the many other pages which are currently open for edit and have no one transcribing. The "Find a New Page" function should ensure that the page it finds is actually a new one, not simply any eligible page which is open for edit.

**Comment by acdha** [comment]
This is a subset of the changes discussed with @colefemeno last week where we need to update that view to add biases in favor of keeping you within the same item, project, or campaign.

**Comment by acdha** [comment]
9b7bdde6c7e10dadfd203506070d59cb84606d28 changes the logic to avoid hitting the current asset unless there are no others available.

**Comment by rstorey** [comment]
Right on, it works now
