### ISSUE TITLE
Progress bar and item filtering

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#443]
**How can we reproduce the bug?**
1. Go to an item that has some assets open for edit, some submitted for review.
2. Observe the progress bar when filtering by all images.
3. Change the filter to open for edit and click go.
4. Change the filter to submitted for review and click go.

**What behavior did you observe? Please describe the bug**
1. The progress bar changed when the filter status changed. 
2. The progress bar seemed to reflect the progress of the filtered assets.

**What is the expected behavior?**
1. The progress bar should reflect the status of the item, not the status of the filtered assets being displayed.

**Got screenshots? This helps us identify the issue**
![screen shot 2018-10-19 at 1 30 06 pm](https://user-images.githubusercontent.com/5270415/47234169-f138e300-d3a2-11e8-83b6-286b0edefe6b.png)
![screen shot 2018-10-19 at 1 29 57 pm](https://user-images.githubusercontent.com/5270415/47234179-f85ff100-d3a2-11e8-8ee6-1ff9982c21b5.png)

**Comment by acdha** [comment]
Ah, yes, this is using the paginator's count as the max value
