### ISSUE TITLE
Confusing interface when an empty transcription is in review

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#453]
**What behavior did you observe? Please describe the bug**
I was confused when I viewed a transcription that had no text and was submitted for review.

**How can we reproduce the bug?**
1. Go to a transcription that is empty (where the nothing to transcribe box was checked) and has been submitted for review.
2. Observe the contents of the textarea.
3. Look at the buttons available to you.

**What is the expected behavior?**
If the transcription is empty on purpose, I want to know as I am reviewing that it is empty on purpose. It seems like a mistake that the textarea contains the default text and I'm supposed to accept that.

**Got screenshots? This helps us identify the issue**
![screen shot 2018-10-19 at 10 26 00 pm](https://user-images.githubusercontent.com/5270415/47250387-11da5a80-d3ee-11e8-9247-6f13761d6baf.png)

**Comment by rstorey** [comment]
Can we also eliminate the need to go through the step of Saving when there is nothing to transcribe? It seems redundant.

**Comment by acdha** [comment]
We might want to change the design so it doesn't even generate a text area for the review state, instead giving you a <div> with overflow scrolling enabled, and then add a “no transcribable content” special case for it.

The reason there's a separate save step is to prevent mistakes (see #372 / #394) – we guard one possibility by having [an immediate confirmation](https://github.com/LibraryOfCongress/concordia/pull/394#issuecomment-429985639) if you check “Nothing to transcribe” when there's text in the box but this is the other side where someone checks that box by mistake and wants to correct it.

**Comment by rstorey** [comment]
This is fixed
