### ISSUE TITLE
Jarring refresh occurs when I click Add Tags after submitting text

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#454]
**What behavior did you observe? Please describe the bug**
My browser went blank for a moment before the page I was on was refreshed. Then I was able to click the link to the page I actually wanted.

**How can we reproduce the bug?**
1. Go to a page that has a transcription task to be performed.
2. Submit a transcription for review or Accept a transcription that is already in review.
3. In the resulting modal, click Add Tags because you don't want to navigate away from this page to a random page, you want to click the Next arrow to go the the next page.

**What is the expected behavior?**
It shouldn't be a jarring experience when a user clicks Add Tags, particularly if the only reason they're clicking that button is in order to stay on the current page and click one of the other links on there.

**Additional context**
Perhaps we need a third option in that modal which allows you to go back to where you came from and choose your own next page or next navigation destination. It's kind of annoying to have to hit the server and load a page that I don't want just to be able to access the links on the original page. Or perhaps we can expose other links to other pages in the modal.

**Comment by rstorey** [comment]
Here's another situation where the refresh occurs when it might not be necessary.
Steps to reproduce:
1. View a transcription that has been submitted for review by someone else and has an error in it.
2. Click Edit so you can correct the error.
3. Click Add Tags in the pop-up modal just so you don't get redirected to another random page.
4. Correct the transcription.
5. Click Save.
6. Click Submit for review.

**Comment by acdha** [comment]
This was added as a requirement in #372 to reload the UI state after:

https://github.com/LibraryOfCongress/concordia/commit/85b051d1cba05b08dafb5366b00d417d6bce963a#diff-cf73fb468f6c2eb6ed5db013db2b60a7

Going back to the old way would require duplicating the action button generation in JavaScript or moving it there entirely, which would be a reasonable goal for a future release along with modernizing the toolchain.

**Comment by rstorey** [comment]
This'll be fixed in the new UI
