### ISSUE TITLE
Rate limit asset reservations

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#456]
**What behavior did you observe? Please describe the bug**
I can open as many browser tabs as I want with individual assets, thus reserving them for me to work on.

**How can we reproduce the bug?**
1. Go to an item page.
2. Open each asset for the item in a new tab.

**What is the expected behavior?**
After a certain number of assets, I should be prevented from being able to reserve more until I release some.

**Additional context**

**Comment by acdha** [comment]
This is due to the requirement to support anonymous users. We could set separate limits so a DoS would only affect anonymous users

**Comment by acdha** [comment]
See #480

**Comment by rstorey** [comment]
This is done, at least for now
