### ISSUE TITLE
Multi-Click on Item

### ISSUE THREAD

**Issue by BrittLong13** [LibraryOfCongress/concordia#470]
I noticed that when I went to click on the items to transcribe there was no option of just clicking on the item and it would open. I had to click on designated spots on the thumbnail in order for it to open. I was wondering if there was an option or upgrade coming where it doesn't matter where you click on the thumbnail and it will pop up?

**Comment by acdha** [comment]
Currently you can click on the header, image, or footer. From the sounds of it, were you looking at an item where the thumbnail did not cover the full height of the card?

**Comment by BrittLong13** [comment]
When I was clicking on the thumbnails I clicked in multiple areas and it would only respond when I clicked in the header. It did not respond when I clicked on the image or footer. It is very possibly that what you said could have been the issue and that is the thumbnail didn't cover the full height of the card.

**Comment by acdha** [comment]
Ok – in the future it would be extremely helpful to have a URL if possible so we can quickly narrow down the cause for a problem.

**Comment by BrittLong13** [comment]
So I am using Google Chrome as my platform for editing and you mentioned that I should be able to click the header, image, or footer to work on the item. In this specific case I can click the header an image, but not the footer. I have provided an URL this time.

https://crowd-test.loc.gov/campaigns/letters-to-lincoln/1840-1849-marriage-family-election-congress-temporary-exit-politics/mal0005700/
