### ISSUE TITLE
Crash on filepath

### ISSUE THREAD

**Issue by BrittLong13** [LibraryOfCongress/concordia#472]
While using the shortcut options there was an error that popped up when I would try to navigate backwards through the hyperlinks at the top of the screen.

**Comment by acdha** [comment]
Can you provide more information about this, such as the URL of the page where you had the problem and the error message?

**Comment by BrittLong13** [comment]
It seems as though it has now been corrected. When I tried today just a few minutes ago I had no issues navigating back and forth. There could of been some connection issues happening on the day that I was on the site.

**Comment by acdha** [comment]
Thanks for testing! I'll close this issue but feel free to re-open it if you find a problem. If you do, a URL would be extremely helpful so we could rule out something such as a bug which has already been fixed but hasn't yet been deployed to the server you were using.
