### ISSUE TITLE
Campaign Admin Updates

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#474]
* [x] Add weight to campaign: As a community manager, I want to be able to order the campaigns from the Admin dashboard, and adjust that value as campaigns and challenges progress. The default is alphabetical. I would also like to see the order reflected in the admin campaigns view
* [x] Add a flag to the campaign model which controls whether a campaign will be included on the homepage
* [x] Convert line breaks in all description fields to HTML newlines
* [x] Remove campaign button under each campaign image. Keep browse all campaigns button.
* [x] Update the homepage to show as many as three campaigns using the ordering and inclusion logic from the first two subtasks

**Comment by acdha** [comment]
The weight idea seems to intersect with @elainekamlley's #521 — perhaps that means we do something like add a priority field and say the homepage takes the highest 3 values?

What does “add line breaks” mean — preserving them in the HTML display if someone enters one?

**Comment by elainekamlley** [comment]
So in the description fields, at this time are unable to add styling like line breaks, bold, italic, etc. We may want to add book titles or break up a long paragraph into two smaller ones.

**Comment by elainekamlley** [comment]
Agree to try and make the solution for #521 and this interact or the same would be ideal.

**Comment by acdha** [comment]
> So in the description fields, at this time are unable to add styling like line breaks, bold, italic, etc. We may want to add book titles or break up a long paragraph into two smaller ones.

That's the text versus HTML issue: if we want to preserve line-breaks, that's easy but any other formatting, links, etc. would require adopting a rich text format — either HTML or something like Markdown (which can be safer) — and deciding whether we're adding any restrictions on what can be used.

**Comment by acdha** [comment]
@colefemeno @elainekamlley I'm assigning this ticket to you until we have enough consensus on the goals to start work.

We can very easily add support for preserving line breaks (see #670) but if we want more formatting or links, that involves converting that field to HTML or something like Markdown, which involves more decisions about allowed formatting, previews, whether projects also get the same separate `short_description` as campaigns, etc.

**Comment by elainekamlley** [comment]
Let's talk about this in our spike today. Question to also answer is - will this also affect static page updates #665

**Comment by elainekamlley** [comment]
Decision from spike: 
*Text editing*: just add line breaks for now and we will see how editing goes for static pages and whether or not we want to have the same type of formatting for campaigns. 

*Campaign ordering*: We are going to add a ranking for the campaigns in the admin and a checkbox for home page
