### ISSUE TITLE
Update Home with Campaign Images

### ISSUE THREAD

**Issue by jbresner** [LibraryOfCongress/concordia#476]
@elainekamlley - I scaled these so wouldn't use them but it gives you an idea of what I'd do for the cropping (i.e. lose the borders and non-image edges).

![marychurchterrell-cropped](https://user-images.githubusercontent.com/4275957/47310736-f9448d00-d605-11e8-8398-39fd9d8c111d.jpg)
![lincolncampaignimage-cropped](https://user-images.githubusercontent.com/4275957/47310737-f9448d00-d605-11e8-8364-5b9358d77a47.jpg)
![bartoncampaignimage-cropped](https://user-images.githubusercontent.com/4275957/47310738-f9448d00-d605-11e8-8841-4352861b0010.jpg)
![branchrickeycampaignimage-cropped](https://user-images.githubusercontent.com/4275957/47310739-f9448d00-d605-11e8-8890-7f274019d9a6.jpg)

**Comment by elainekamlley** [comment]
This is done
