### ISSUE TITLE
Display a policy on copyright status of contributions 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#48]
Acceptance Criteria: 

- [ ] As a [user], I want [action] so that I can [result].

**Comment by VVH** [comment]
This content has been added to the About/FAQ pages: 

**How will the transcriptions I create be used?**

The data contributed by volunteers like you can be used in many different ways. We are giving back to our community by making this data public. All contributions to this application are released into the public domain. Anyone is free to use this data set in any way they want. The data produced by volunteers is also free to reuse. If you need help accessing the data or want to share news of your research with the Make Your Mark community, please contact the Community Managers at crowd [at] loc.gov.
