### ISSUE TITLE
Update crowd.loc.gov home page banner image

### ISSUE THREAD

**Issue by jbresner** [LibraryOfCongress/concordia#486]
There is still ongoing discussion about the final home page banner image but it appears everyone is leaning toward using the image below:

![crowd-home-banner](https://user-images.githubusercontent.com/4275957/47322599-8a2b6080-d626-11e8-8deb-82f6c317c62c.jpg)

Once we get final approval, I'll reassign the ticket for the image to be updated.

(for reference, the image source is here: http://www.loc.gov/pictures/item/2014690491/

**Comment by elainekamlley** [comment]
This is done
