### ISSUE TITLE
Use Django form validation on collection name and URL fields

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#5]
https://github.com/LibraryOfCongress/concordia/blob/6e606eb0c7c1ff574d2aed2c7bca0013cc97b9c4/concordia/views.py#L217-L221 has a few areas for improvement:

* It would be better to use [`subprocess.check_call`](https://docs.python.org/3/library/subprocess.html#subprocess.check_call) (or `check_output`) which reliably raises exceptions on errors and escapes input parameters

* … and better still to use [`shutil.rmtree`](https://docs.python.org/3/library/shutil.html#shutil.rmtree) to avoid needing to invoke an external shell.

* This matters because https://github.com/LibraryOfCongress/concordia/blob/6e606eb0c7c1ff574d2aed2c7bca0013cc97b9c4/concordia/views.py#L216 doesn't validate the `POST` value it receives beyond hoping that the Celery tasks will fail to return a value. If that assumption proves to be untrue or changes in the future this might allow a shell injection attack because it only blocks spaces but not the other whitespace characters which shells accept:

```python
>>> payload = "echo\tfoo\tbar"
>>> print(payload)
echo	foo	bar
>>> os.system(payload.replace(" ", "-"))
foo bar
```

Beyond using [`pathlib`](https://docs.python.org/3/library/pathlib.html) to construct paths, I would also strongly recommend using something like Django's form validators to restrict that value to a known-good pattern rather than hoping we account for all of the possibilities.

**Comment by rstorey** [comment]
Remaining to do:

- [ ] Use Django form validators to ensure that values used for the collection name (which is subsequently used as a directory name for images on the filesystem) are known-good patterns and do not contain anything dangerous (e.g. other whitespace characters besides spaces)

**Comment by rstorey** [comment]
Obsolete
