### ISSUE TITLE
Navigating on the asset level takes me out of the full screen 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#505]
**What behavior did you observe? Please describe the bug**
When I am in the full screen asset view and try to navigate to the next asset or go to find another asset, it brings me out of full screen. 

**How can we reproduce the bug?**
1. Go to an asset view
2. Click on full screen
3.  Click the right or left arrow on the top left corner of the viewer
4. See error, it will take you out of the full screen view

**What is the expected behavior?**
When I am in full view I expect to navigate through other assets while staying in full view mode.

**Comment by acdha** [comment]
This is how the full screen API works. We’ll need to move rendering completely into JS to avoid that limitation.

**Comment by elainekamlley** [comment]
Ah, thats interesting. I'll close this and checkout OpenSeadragon if this has been an issue.

**Comment by acdha** [comment]
Let's leave it open: it's definitely something we should have a better experience for. It will take some time but that's a direction we want to go in anyway for other reasons like UI performance.

**Comment by rstorey** [comment]
This is currently solved in the new activity-based UI. I don't expect we'll support this type of feature in the classic UI.
