### ISSUE TITLE
Reduce friction on registration/login

### ISSUE THREAD

**Issue by benwbrum** [LibraryOfCongress/concordia#507]
When I first tried to register for an account, I encountered these difficulties:

* Password requirements are discouragingly strict; consider requirements that are both easier and more secure than arbitrary special character requirements.  cf. [XKCD on password strength](https://xkcd.com/936/)
* When I created an account, it was not at all obvious that I needed to check my email and click a validation link.
* When a user who has not clicked a validation link attempts to log in, the error message is a standard one of the form _bad username or password_, and does not hint that the account was not validated.  
* Generally, when a user registers for their account, they are not automatically logged into the system.  This means additional clicking, emailing, etc before they can actually contribute to login-required features.

I suggest reviewing the process of new user registration and creating specific issues addressing the friction points.

**Comment by VVH** [comment]
Any issue that references an XKCD cartoon gets an A+ in my book. Thanks for this thoughtful feedback @benwbrum. We'll circle up about this and see which aspects we can address when. Much appreciated.

**Comment by acdha** [comment]
See #168 for the plan to switch to zxcvbn to provide better password strength checks which are also less onerous.

**Comment by lalgee** [comment]
Remove slashes from username instructions.  Currently underneath the field for creating a username it says "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only." This leads some users to believe that slashes are allowed.

**Comment by elainekamlley** [comment]
@lalgee Let's take your comment and create a separate ticket for that. We can include that in this next sprint

**Comment by acdha** [comment]
Specifically, we should note that this is overriding this value: https://github.com/django/django/blob/e81955401885a93a459bcc130642b6ea5bf4ba4d/django/contrib/auth/models.py#L301

**Comment by elainekamlley** [comment]
Happy belated anniversary of this issue! Over the last year and especially in the latest release, we've many improvements to the registration process. Thanks to you, @benwbrum for creating this issue as it was a nice outline of the work. To learn more about what else we've been up to, check out [releases](https://github.com/LibraryOfCongress/concordia/releases. Thanks again!
