### ISSUE TITLE
Users logged out between crowdsourcing platform and discussion platform

### ISSUE THREAD

**Issue by benwbrum** [LibraryOfCongress/concordia#510]
When a user logs into the crowdsourcing platform and clicks on the "Discuss" link, they must also log into the discussion platform separately, which gives the sensation of having been logged out.

Post-login on LOCCrowd:
![loccrowd_login_1](https://user-images.githubusercontent.com/199961/47446032-ea81e580-d77f-11e8-9b9a-103391927281.PNG)

Click on "Discuss" and see:
![loccrowd_login_2](https://user-images.githubusercontent.com/199961/47446033-ea81e580-d77f-11e8-9376-8c7f94a3446b.PNG)

It looks like these may be separate platforms which have been integrated through branding, so it's not obvious that the user has navigated to a separate site.  Implementing single-sign-on may be a lot of work.

**Comment by VVH** [comment]
Hey @benwbrum, we are using two separate logins because these are two distinct platforms. We're not sure if we're going to be able to have a single log in, based on Library protocol, but @acdha is looking into it.

**Comment by rstorey** [comment]
These are two separate platforms. There currently isn't any plan to integrate login between both of them.
