### ISSUE TITLE
Repeat email confirmation process when user changes their email address

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#514]
When a user initially registers, they have to confirm their email. When a user changes their email address on the profile page, they don't have to repeat that step, and they probably should.

**Comment by acdha** [comment]
Agreed: they can't change it to an address which is in use by another user but they could change it to a mistaken address and then be unable to regain control of their account if they lose the password.

**Comment by rstorey** [comment]
Related to #662

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-66](https://staff.loc.gov/tasks/browse/CONCD-66)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
