### ISSUE TITLE
Improve Contact Us form

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#519]
Based on the first 24 hours of user emails, we should implement some usability improvements to contact us page to improve the public and community manager experience of creating and understanding emails.

As a community manager, I want to have crowdsourcing automatically indicated in the subject line when I respond to users' emails.
* [x] Change subject line generated by contact us form to “Contact crowd.loc.gov: [subject]” (currently is "Contact us: [subject]")

As a community manager, I want every user email to have a subject line, user email address, and content.
* [x] Make ~~email address~~, subject, and ~~body~~ required fields.
* [x] Indicate to users which fields are required

As a user, I want to understand when I have submitted an email via the contact us form.
* [x] Change “save” button to “send” or "send message"

As a user I want clearer form instructions
* [ ] Add help text for fields

**Comment by colefemeno** [comment]
As a community manager, I want to make sure I can view replies
- Automatically populate replies with cc: crowd at loc dot gov

As a user I want to understand what kind of response I can expect
Provide an automatic reply that indicates expected time to receive a response, like how many days, where else to find help or resources in the meantime, HH, etc

**Comment by acdha** [comment]
“Change field text to instructions rather than just field name” — this really should be adding help text in addition to the field name. You can see the `help_text` usage on other fields in https://github.com/LibraryOfCongress/concordia/blob/master/concordia/forms.py

**Comment by acdha** [comment]
`Automatically populate replies with cc: crowd at loc dot gov` — aren't all replies being sent with that as the from address, as was the case with the test message I sent?

**Comment by acdha** [comment]
Re: automatic replies, we have a generic message to the user telling them that their message has been sent. What kind of response time are we comfortably promising?

**Comment by lalgee** [comment]
Yep, help text is exactly what I meant.  

I'm not sure what @colefemeno's thoughts there.  @VVH @elainekamlley ?

We are aiming for responses in 3-5 days.

**Comment by acdha** [comment]
So the idea is that when someone sends that first message we'd send them an email roughly along the lines of “Your message has been sent. We attempt to answer all emails within 3-5 days.” — does anyone want to take a stab at the exact prose for that?

**Comment by acdha** [comment]
CC: is actually something which would need to happen elsewhere — the only message we send is to crowd@loc.gov and the replies are out of the app's control.
