### ISSUE TITLE
Selecting images for projects 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#520]
User stories: 

- As an admin, I would like to upload an image to a project and it is represented in the standard format of 368 x 272
- As an admin, I would like the project image to be represented by an image from one of the items

Context: 

When uploading images for projects it was time consuming to find and edit images. Becuase of the differences in layout of the image, editing to be 368 x 272 was at times challenging.

**Comment by acdha** [comment]
This sounds like about 4 separate changes:

* Change the existing images to 368x272 — the project images tend to have page aspect ratios like 368x473 — or is that only for the campaign listing?
* Setting the standard sizes on the image, with the appropriate responsiveness fallbacks, so they'll always be consistently sized on the listings
* Using something like [`object-fit: cover`](https://caniuse.com/#feat=object-fit) to handle images which are not quite the right dimensions without requiring someone to edit them manually
* Allowing the use of an item thumbnail or asset image as the project image

**Comment by elainekamlley** [comment]
Not necessary at this time
