### ISSUE TITLE
Only show specific campaigns on the home page 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#521]
**Is your feature request related to a problem? Please describe.**
Currently all campaigns show up on the home page. As this section grows, as a Community Manager, I would like to set only three campaigns to show up on the home page. This could be called `Featured Campaigns` 

**Describe the solution you'd like**
In the admin dashboard, I would like to be able to assign and order campaigns to be featured on the homepage

**Comment by acdha** [comment]
Are we certain that this will always be exactly 3 campaigns or will that potentially change? Can it be less than 3 — e.g. where we'd take 2 featured campaigns and then pick a third from the full list to keep the number of displayed campaigns consistent?

Is this just a simple toggle or will there be more complex rules such as date/time windowing?

**Comment by rstorey** [comment]
We also will want to be able to control the ordering of these featured campaigns similar to how we order the related links.

**Comment by acdha** [comment]
Based on @elainekamlley's answers to the questions above, this could be as simple as adding a priority integer field and having the homepage view sort the list in descending order and using the top 3.

**Comment by acdha** [comment]
@colefemeno @elainekamlley I'm assigning this to you until we have enough consensus on the approach to start development

**Comment by elainekamlley** [comment]
Decision is to add check box for `add to home page` in the admin and use the ranking in #474

**Comment by acdha** [comment]
I'm moving the one todo item from this ticket into #474
