### ISSUE TITLE
Update technical documentation to include how to stand up another instance

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#529]
User story:
As a person who works at an institution, I would like to know specific details in your documentation on how to stand up our own instance of Concordia, so that I can better understand if this tool would be right for our goals. 

Context: At MVP, Concordia importer is LOC specific. At every iteration our documentation should be transparent about where it is LOC reliant and the guidance on how to adopt the tool in its current state. Over time we will work towards improving this tool, not only for our users volunteering at crowd.loc.gov, but users that want to fork the code.

**Comment by acdha** [comment]
@rstorey has a pretty detailed guide at https://github.com/LibraryOfCongress/concordia/tree/master/cloudformation but it could definitely use some review for portions which might not make sense to someone new to the project since the dust was flying pretty heavily over the last week.
