### ISSUE TITLE
Add total number of contributions to profile page

### ISSUE THREAD

**Issue by VerifiedJoseph** [LibraryOfCongress/concordia#532]
**Is your feature request related to a problem? Please describe.**
Users can't quick find out how many contributions they have made to campaigns on the platform. 

**Describe the solution you'd like**
Show the total number of contributions next to or under the My Contributions section header on the profile page.

Ideas:

> My Contributions (10)

>**My Contributions**
>Contributions: 10

**Describe alternatives you've considered**
Show total number of contributions and number per campaign in a table or list. 

| Campaign           | Contributions |
|--------------------|---------------|
| Letters to Lincoln | 10            |
| Scouting Reports   | 20            |

**Comment by elainekamlley** [comment]
Thanks @VerifiedJoseph! This is a great additional feature and will add it to a future sprint. Really appreciate you jumping in.
