### ISSUE TITLE
Create lambda function to keep cloudflare IPs in security groups

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#534]
We need to run the script https://github.com/LibraryOfCongress/concordia/blob/master/cloudformation/add_cloudflare_ips_to_sgs.py periodically to ensure that cloudflare has access to the load balancer. Set up a lambda function to do this on a regular basis.

**Comment by acdha** [comment]
When I updated the script I was hoping it'd be pretty easy to add a handler function to call it as well. I believe testing it locally should be easier, too: https://aws.amazon.com/blogs/aws/aws-serverless-application-model-sam-command-line-interface-build-test-and-debug-serverless-apps-locally/

**Comment by rstorey** [comment]
This is done
