### ISSUE TITLE
Change to Python 3.7

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#538]
Python 3.6 is defined in the Pipfile as the supported version. I think it's time to go to 3.7.

**Comment by acdha** [comment]
I'd really like this but Celery hasn't been updated yet to support 3.7 in a released version yet — see https://github.com/celery/celery/issues/5101

**Comment by rstorey** [comment]
Ah okay nevermind for now

**Comment by acdha** [comment]
I think this should be open but in a further milestone since the Celery developers are trying to get the next release out the door pretty soon.

**Comment by rstorey** [comment]
Okay, works for me.

**Comment by rstorey** [comment]
This is done.
