### ISSUE TITLE
Progress bar is confusing when 100% complete

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#540]
**What behavior did you observe? Please describe the bug**
The progress bar is half yellow, half green.

**How can we reproduce the bug?**
1. Go to https://crowd.loc.gov/campaigns/letters-to-lincoln/1830-1839-first-forays-in-politics-and-law/mal4500049/

**What is the expected behavior?**
The progress bar should be fully green when everything is complete.
The In Progress: 0% caption should probably disappear once Complete is 100%.

**Got screenshots? This helps us identify the issue**
<img width="1282" alt="screen shot 2018-10-29 at 2 26 44 pm" src="https://user-images.githubusercontent.com/5270415/47678176-86a05800-db97-11e8-9ea6-f8738af15a8b.png">

**Comment by acdha** [comment]
With the change in https://github.com/LibraryOfCongress/concordia/pull/543/commits/7b008fc6718178559eb7ebbb3af786a3db3ab04e a completed item looks like this:

![image](https://user-images.githubusercontent.com/46565/47683613-793e9a00-dba6-11e8-89b4-ae10ff77b38d.png)
