### ISSUE TITLE
Update developer docs and add pre-commit webhook

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#541]
Some of the developer guide needs to be updated accurate steps and information on how to install and use pre-commit.

It would also be nice if recommended VS Code plugins and settings could be documented in our dev guide as well.

**Comment by jkueloc** [comment]
@rstory @acdha @rabiloc - Do you have specific VS Code plugins and settings that you would like to recommend in addition to the Python extension.

**Comment by acdha** [comment]
Most of them follow the same tools we're using in our Pre-Commit configuration. The most important one is the Editor Config extension, which causes VSCode to use the `.editorconfig` settings in the repo, and the Prettier one is handy for ensuring that you don't have to wait for pre-commit to run to reformat JavaScript, CSS, etc.

```
amazonwebservices.aws-toolkit-vscode
dbaeumer.vscode-eslint
shinnn.stylelint
EditorConfig.EditorConfig
esbenp.prettier-vscode
mrmlnc.vscode-scss
```
