### ISSUE TITLE
Allow admins to re-open completed assets for updates

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#544]
We need some kind of admin function to be able to edit, re-open, or otherwise change status of an asset that has already gone through the workflow and been marked completed. Functionality TBD

**Comment by acdha** [comment]
My comment from Slack:
> We have a fairly simple model where the transcription record has a single reviewed_by user field and accepted/rejected flags for the result of that review; In this case, it sounds like we want a way to create a new transcription record which supersedes the old one but I'd like a way to record that a CM overrode the original reviewer's decision and we don't have direct field to store that as well as the original reviewer.

**Comment by elainekamlley** [comment]
Here are some user stories:
