### ISSUE TITLE
Responsive design for Transcription page

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#549]
**Is your feature request related to a problem? Please describe.** 
On a iPhone X the transcription page is jumbled. While we want our users to primarily perform tasks on computer or tablet, many of the our users will find out about us on newsletters or twitter.

**Describe the solution you'd like**
A layout that is mobile or tablet friendly with the main purpose of the discovery of the asset. Community managers and some users are tweeting specific assets to generate stories, when a user clicks on that they should be able to interact with the asset and see the start of the transcription. 

**Describe alternatives you've considered**
Not sure but open to solutions

**Additional context**
Here is the current experience of mobile view: 

![image from ios 1](https://user-images.githubusercontent.com/7362915/47732910-8a86b580-dc3d-11e8-99d1-c497a5926ec6.png)
![image from ios](https://user-images.githubusercontent.com/7362915/47732915-8c507900-dc3d-11e8-833c-a9b125a827f6.png)

**Comment by acdha** [comment]
It seems like most of these could be addressed simply by changing the flex direction to a vertical column so you'd see the seadragon viewer and then the transcription field. That'll require some style adjustments (borders, etc.) but nothing heroic.

**Comment by elainekamlley** [comment]
Wait, you're not a super hero Chris? I'm all in favor for simple fixes and seeing how our users respond.

**Comment by jbresner** [comment]
Here's an initial set of the transcription page views with the different breakpoints:
![transcibe-1200](https://user-images.githubusercontent.com/4275957/48175540-895b2580-e2da-11e8-9b27-f0b554a316b7.png)
![transcribe-480](https://user-images.githubusercontent.com/4275957/48175541-895b2580-e2da-11e8-81a2-4e848231188d.png)
![transcribe-768x1024-landscape](https://user-images.githubusercontent.com/4275957/48175543-895b2580-e2da-11e8-87d0-91bb5b91dc24.png)
![transcribe-768x1024](https://user-images.githubusercontent.com/4275957/48175544-895b2580-e2da-11e8-8e6e-f2f03c5dbb35.png)
![complete-1200](https://user-images.githubusercontent.com/4275957/48175552-8f510680-e2da-11e8-8df8-12abec00d7eb.png)
![review-1200](https://user-images.githubusercontent.com/4275957/48175553-8fe99d00-e2da-11e8-8665-897b72fa8cf2.png)

**Comment by acdha** [comment]
@jbresner can you make an SVG for the splitter thumb?

**Comment by jbresner** [comment]
@acdha - You'll have to show me a better way to get a SVG file to GitHub but here it is...
[handle.svg.zip](https://github.com/LibraryOfCongress/concordia/files/2562511/handle.svg.zip)

**Comment by elainekamlley** [comment]
@jbresner do you mind adding these mocks to the confluence page along with your notes? Im gonna close this ticket and any additional improvements will be new ones.

**Comment by jbresner** [comment]
@elainekamlley The comps/notes have been added to Confluence (https://staff.loc.gov/wikis/display/NDI/2018-12-06+-+Transcription+Page)
