### ISSUE TITLE
Add Welcome Guide and Challenge to Carousel 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#550]
User story: 

- As a community manager, I want to highlight a challenge so that I we can signal to users what campaign to go to. 
- As a community manager, I want to add to the carousel
- As user, I am not quite sure where to start. I'd like to read instructions or a tutorial as a way to onboard. 

Acceptance criteria: 
- write CTA language for Welcome guide and Challenge
- Get images to the carousel image dimensions
- Add right side CTA as an option like in the loc.gov carousel below:  
<img width="1220" alt="screen shot 2018-10-30 at 12 24 36 pm" src="https://user-images.githubusercontent.com/7362915/47733546-df76fb80-dc3e-11e8-9acc-89b1027ae4a3.png">

**Comment by jbresner** [comment]
Here are two of the images we may consider using for the home page carousel. The Lincoln letter gets cropped a bit awkwardly so let me know if you think we need to replace it with something else or try another layout with it.

![branch-rickey](https://user-images.githubusercontent.com/4275957/47931536-6decb680-dea5-11e8-9ffb-fb37e83c3198.jpg)
![lincoln-letter-2](https://user-images.githubusercontent.com/4275957/47931541-734a0100-dea5-11e8-9672-368f7427aa8f.jpg)

**Comment by elainekamlley** [comment]
@jbresner mind adding your recommendations on carousel rules?

**Comment by jbresner** [comment]
@elainekamlley - Here are some general guidelines we should consider for the carousel if we use auto-rotation:

1. Slides should be displayed about 5 seconds before advancing to the next image (if there's a lot of text on the image, which there shouldn't be, then we could bump up the delay a second or two).
2. On hover, the carousel should pause and no longer auto-rotate. If the cursor is no longer over the carousel, the auto-rotate sequence may continue.
3. If the user is interacting with the carousel controls (i.e. the left/right navigation and/or the slide indicator buttons) then the system should also pause the auto-rotate.
4. At the mobile breakpoint, the auto-rotate should be disabled.
5. Also for mobile, the user should be able to swipe to advance slides in the carousel.

We can use the same UI elements that we have on the LOC.gov home page if that expedites building this out. I'll add a mockup of the UI for reference.

**Comment by jbresner** [comment]
@elainekamlley - Well, with auto-rotation, it still wouldn't happen right away—you'd still have the 5 second delay. I guess I'm not convinced people are loading a page and not doing anything on it (scrolling/clicking) for the pausing you described to take effect. We you suggesting this because of concern that a user won't see the first carousel item?

Also, here are the comps for the carousel at some of the various breakpoints.

![home-anon-480](https://user-images.githubusercontent.com/4275957/48501754-f35c5900-e80b-11e8-9d3d-eb734147cdbe.png)
![home-anon-992](https://user-images.githubusercontent.com/4275957/48501755-f35c5900-e80b-11e8-85c3-bb3344078282.png)
![home-anon-1200](https://user-images.githubusercontent.com/4275957/48501756-f35c5900-e80b-11e8-86c3-55d7a3c44808.png)

**Comment by elainekamlley** [comment]
@jbresner five seconds sounds good to me. We'll see how it feels when we test it. @colefemeno okay to sign off on these guidelines? @acdha what do you think? 

> @elainekamlley - Here are some general guidelines we should consider for the carousel if we use auto-rotation:
> 
> 1. Slides should be displayed about 5 seconds before advancing to the next image (if there's a lot of text on the image, which there shouldn't be, then we could bump up the delay a second or two).
> 2. On hover, the carousel should pause and no longer auto-rotate. If the cursor is no longer over the carousel, the auto-rotate sequence may continue.
> 3. If the user is interacting with the carousel controls (i.e. the left/right navigation and/or the slide indicator buttons) then the system should also pause the auto-rotate.
> 4. At the mobile breakpoint, the auto-rotate should be disabled.
> 5. Also for mobile, the user should be able to swipe to advance slides in the carousel.
> 
> We can use the same UI elements that we have on the LOC.gov home page if that expedites building this out. I'll add a mockup of the UI for reference.

**Comment by acdha** [comment]
@elainekamlley @colefemeno Do we have final text & images for me to start with tomorrow? I was planning to use Jamie's earlier uploads when testing the rotation & hover behaviour.

**Comment by elainekamlley** [comment]
@lalgee will take a pass at the text and the images @jbresner added above are the images we are going with. 

Welcome guide: 
![branch-rickey](https://user-images.githubusercontent.com/4275957/47931536-6decb680-dea5-11e8-9ffb-fb37e83c3198.jpg)

Letters to Lincoln challenge:
![lincoln-letter-2](https://user-images.githubusercontent.com/4275957/47931541-734a0100-dea5-11e8-9672-368f7427aa8f.jpg)

**Comment by VVH** [comment]
**Welcome guide:** 
Get the skinny on how to transcribe, review, and tag. 

**Lincoln:** 

Help us transcribe and review Letters to Lincoln: husband, father, postmaster, lawyer, politician, President.  

or

Happy birthday Mr President? Help us transcribe and review all of the Letters to Lincoln by his birthday on February 12, 2019.

@lalgee can you choose which you prefer for Lincoln?

**Comment by elainekamlley** [comment]
Thanks @VVH! For the welcome guide, that link will be for the `Get started` button. 

For Lincoln, do we want it to act like the current Lets go button or go to the campaign? What do you think @colefemeno?

**Comment by colefemeno** [comment]
@elainekamlley @vvh 
- For the L2L carousel image, can we do "goes into page that needs work in L2L"
- For the Let's Go button, can we do "goes into ANY page in any campaign that needs work" 

And to confirm: welcome guide carousel image goes to Help Center?

**Comment by lalgee** [comment]
@colefemeno is correct on what buttons should link where.

Thumbs up @VVH on the Welcome Guide words.

For Lincoln words let's do --
A grand challenge: Help finish Letters to Lincoln by the end of 2018!

**Comment by acdha** [comment]
The text & commentary about links don't match the comps above. Is the idea that these will replace the “By the People” box content or that we're adding them somewhere else? 

We should also get some thought on the alt text for the images. The current image has this description: https://github.com/LibraryOfCongress/concordia/blob/7121c49399c7644587d69e1e4819fcd6d6ec2aa1/concordia/templates/home.html#L16

@VVH I'm not sure what “if you just want people to click on whole carousel image as normal” means — the carousel image doesn't currently do anything if you click on it. Is that intended to change?

**Comment by VVH** [comment]
**Where the text goes:** I assumed that each part of the carousel would have a white box to the left, as on Crowd, and that the text inside those would reflect the current image rather than persisting across all images. 

**Clicking:** I was thinking of the carousels on loc.gov which do link out when you click on them. I think we'll want the behavior consistent with loc.gov, though our home page image need not link--just the Challenge and Welcome Guide. Thoughts @jbresner? 

As for **alt text**, can we make a new smaller issue for that or do you want it added here @acdha?

**Comment by acdha** [comment]
@vvh we're adding these new images here so they probably should have alt text but given that they're decorative rather than content it's not as critical from an accessibility perspective — not having the image at all wouldn't affect the informational content of the site.

**Comment by VVH** [comment]
Ok. I'll assign myself and circle back next week.

**Comment by acdha** [comment]
@vvh I believe the alt text is the only remaining task on this. Here's what we have currently:

* a crowd of girls waving handkerchiefs and smiling; possibly cheering
* Image of letters sent to Abraham Lincoln
* empty

I'm somewhat mixed about the value of these images for accessibility purposes since they're more decorative than content. I think it would be reasonable to either leave them as is or omit the alt text for all of them.

**Comment by VVH** [comment]
Just tested this new feature and it works as expected. I think that we should use a color other than white for the clickable lozenges/beads and arrows that rotate the carousel. The white dots are getting lost in the black and white image. @jbresner maybe you can suggest a color that will do well over most images? Or perhaps this is a detail for @elainekamlley. At the moment the white is lost on 2/3 images.

**Comment by jbresner** [comment]
In the mockup, the circles always have a stroke to help offset similar colors in the background.

- hover/active state is - base: #fc4c02, stroke: #ffffff
- inactive state - base is #ffffff, stroke: #333333

**Comment by acdha** [comment]
The controls currently are using SVG — it looks like we can change that from this:

```css
.carousel-control-next-icon {
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
}
```

to something like this (which inverts the colors above):
```css
.carousel-control-next-icon {
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath stroke='%23333333' stroke-width='.5' d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
}

.carousel-control-next-icon:hover {
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fc4c02' viewBox='0 0 8 8'%3E%3Cpath stroke='%23ffffff' stroke-width='.5' d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
}```

![image](https://user-images.githubusercontent.com/46565/49765641-21b14500-fca1-11e8-9775-2ab771ab4f42.png)
![image](https://user-images.githubusercontent.com/46565/49765667-32fa5180-fca1-11e8-917e-73b768116026.png)

**Comment by acdha** [comment]
@jbresner I updated the screenshots above to change the stroke width to 0.25.

**Comment by VVH** [comment]
Love the orange!

**Comment by acdha** [comment]
https://github.com/LibraryOfCongress/concordia/pull/708 has updated screenshots on multiple backgrounds

**Comment by VVH** [comment]
@elainekamlley is out atm, so I'm going to open this is a new issue in backlog @acdha
