### ISSUE TITLE
Refactor home page layout to be responsive

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#552]
Mocks for mobile view: 
[JB: see revised mobile comp in my comment below]

**Comment by jbresner** [comment]
Here's the 1200px breakpoint and also the 480px version with the correct header (I accidentally used the main LOC logo in that previous comp)

![home-anon-1200](https://user-images.githubusercontent.com/4275957/47753076-c4bb7b80-dc6c-11e8-89f2-238560cf6f25.png)
![home-anon-480](https://user-images.githubusercontent.com/4275957/47753081-c84f0280-dc6c-11e8-95e8-64327da36832.png)

**Comment by acdha** [comment]
This should be reviewed now that #568 has been deployed

**Comment by elainekamlley** [comment]
Closing for #568 and #555
