### ISSUE TITLE
P1 / Concordia integration

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#56]
Acceptance Criteria: 

- [x] As an admin, I want transcriptions to eventually be available on the main loc.gov website so that other internet users can use the "Show Text" feature on a per image basis. 

- [ ] As an admin, I want transcriptions to eventually be available on the main loc.gov website so that other internet users can use the Download PDF feature to download all text for an item (all pages) in a PDF file.

- [ ] As an admin, I want the text of transcribed items to be visible in search results with facets for Text / PDF content types.

- [x] As an admin, I want the text of transcribed items to be searchable in loc.gov.

- [ ] As an admin, if there is an active CHC project for an item, I would like the P1 loc.gov view of that item to include a link to that specific item in CHC.

- [x] As an admin, I want items in CHC to be linked to their P1 loc.gov sources.

**Comment by rstorey** [comment]
Changes in P1 and formatting / exporting PDFs are currently out of scope for this project.
