### ISSUE TITLE
Indicator of how much work is done on a item from the project page

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#566]
User story: 
As a user, when I am looking at a project page with all of the thumbnails of the item, I want to know how much work has been done on them so that I can determine which item to work on. 
![projectview](https://user-images.githubusercontent.com/7362915/47819707-aec3be80-dd31-11e8-87b2-37bda787ae48.png)

**Is your feature request related to a problem? Please describe.**
When I am in a project, I see all the items but can't tell what I should work on. I would like to know from that page what is complete or needs work. 

**Describe the solution you'd like**
An indicator of level of completeness, either in the form of a percentage or a circular representation of the progress bar in the item view.

**Comment by acdha** [comment]
We should think about how much it's worth to have a granular progress breakdown (with the extra work calculating and displaying a progress bar) versus a simple “complete” boolean display. 

One question which @jbresner may have ideas on is how we can indicate that transcription is complete but you can & should still tag things.

**Comment by jbresner** [comment]
In one of the original wireframes created (see below) for the Project page, I added an indicator that showed the percentage of what was complete for a specific item. I agree with Chris that it's work discussing further about what a user gains from a more detailed view of the percentage (or another TBD calculation). I can work on updating this design with some thoughts on which approach may benefit the user in selecting items to transcribe/tag.

![project-detail](https://user-images.githubusercontent.com/4275957/47856510-c8124c80-ddbd-11e8-8d0b-a16a635d1f27.png)

**Comment by elainekamlley** [comment]
To start, just apply the design of the progress bar to the items on the project page. Also persistent filter from projects page

**Comment by jbresner** [comment]
![project - items listed - gby](https://user-images.githubusercontent.com/4275957/48530978-4bc14400-e868-11e8-9c8c-68503d901194.png)
![project - items listed - gby2](https://user-images.githubusercontent.com/4275957/48530979-4bc14400-e868-11e8-9cbd-3916f92c96ba.png)
![project - items listed - monochrom](https://user-images.githubusercontent.com/4275957/48530980-4bc14400-e868-11e8-8dd3-9fbdc8701f9f.png)

**Comment by jbresner** [comment]
The hex values for the color schemes:

Monochromatic
Completed - 006477
Submitted for Review - 009CBA
Open for Edit - 83CFDD

Muted GBY
Completed - A2C800
Submitted for Review - 4A90E2
Open for Edit - FAAC1D

GBY
Completed - 2E8540
Submitted for Review - 205493
Open for Edit - FDB81E

**Comment by rstorey** [comment]
This is done
