### ISSUE TITLE
Would like the ability to leave notes on work.

### ISSUE THREAD

**Issue by DandCProfessionals** [LibraryOfCongress/concordia#569]
In the Lincoln letters I found the name JB Marrick when I reviewed a document.  I changed it to what it was supposed to be JB Herrick.  I would have been nice to make a note on the page that I changed the name do to some Google searches I found with the correct name of the person of the letter.  This is so other reviewers could check for accuracy.

**Comment by lalgee** [comment]
We currently advise users to utilize tags to indicate corrected spellings of key words within documents. It would be great to scope out in-app notes or other communication in the future, but it is currently out of project scope.
