### ISSUE TITLE
Refactor exporter - look at past tickets and start prelim tests

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#580]

**Comment by acdha** [comment]
Do we want to have streaming bag creation as a goal for this? I'm thinking that might be more hassle than its worth we just use another S3 bucket to assemble images but I think that also raises the question of whether we should bother with media at all vs. just the metadata.

**Comment by acdha** [comment]
That'll keep file sizes manageable — we probably just just be storing IDs & URLs anyway. One thing I remember from the last time I looked at the code was that it didn't seem well-defined how we handled things which weren't complete. Do we have a policy decision from @colefemeno about whether that means we need to exclude uncompleted items, expose the status, etc.?
