### ISSUE TITLE
Use Celery chains for chained tasks

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#6]
I noticed this block of view code:

https://github.com/LibraryOfCongress/concordia/blob/6e606eb0c7c1ff574d2aed2c7bca0013cc97b9c4/concordia/views.py#L203-L211 

There are several areas where that can be improved:

1. Each task should be independently checked and failures logged with debugging context

2. This will block for a potentially unlimited amount of time. It would be better to split this into stages so the user gets feedback immediately. That could be by using a streaming HTTP response, if the client can handle fragments on error, or by providing an API endpoint which client JavaScript could poll with the status for each of the task IDs.

3. It's not immediately obvious whether it's necessary to block the second task from executing until the first has completed (or even why we're using Celery at all if we're calling the code synchronously). In addition to an explanatory comment I generally like using [chains](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chains) or [chords](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chords) to convey that the serial execution is required, and in the latter case that execution should halt if the first task fails.

**Comment by acdha** [comment]
Yeah, I wanted to confirm that there was some eventual timeout for pending tasks as well in case of something like a very slow download.

**Comment by rstorey** [comment]
Each individual image download is a separate celery task. This bit of code is not how I intended the importer to be called except when doing so in an interactive console session. But if you do execute this you'd see that the main download task splits the download into sub-tasks one for each image file.

**Comment by acdha** [comment]
It looks like we should add a reasonable `timeout=` value to https://github.com/LibraryOfCongress/concordia/blob/4a0d7f87457d8f17ee56aec72afe5e769921a5b0/importer/importer/models.py#L158 so we don't tie a worker up for an indefinite amount of time if the source server is malfunctioning.

Does it make sense to approach retries at the task level – e.g. change the task declaration to something like this?

```python
@shared_task(autoretry_for=(RequestException,), retry_backoff=True, retry_backoff_max=1200)
```

**Comment by rstorey** [comment]
Done
