### ISSUE TITLE
Change review workflow for ”edit” path

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#603]
**What behavior did you observe? Please describe the bug**
When a reviewer decides to edit a transcription and clicks "Edit" rather than "Approve" they see a message: "Nice Job! Your review decision has been saved. You can stay on this page to add tags or go to the next page needing transcription." The message is confusing because you're not taken directly to the reviewing/editing mode. I think our assumption should be that if you want to edit something, you're immediately taken into that mode. This pop up is the equivalent of an "are you sure?" message, which I don't think we need.

If they click away from the box to the page behind they can start editing the transcription. So, the underlying functionality makes sense, but this pop up is confusing.

**What is the expected behavior?**
I click "Edit" and I am immediately able to edit the page. The page should ideally stayed focused in as I had it, rather than resizing and going out of full screen mode. 

**Additional context**
We discussed whether this was a bug or enhancement request, and decided it was a bug.

**Comment by acdha** [comment]
As discussed on the call, we'll update this initially by changing the review submission process to display the modal only for approved transcriptions, while the reject branch will cause the page to be reloaded so they can make further changes.
