### ISSUE TITLE
Make concordia data usable

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#606]
This addresses the need to make the data captured in crowd.loc.gov usable for multiple audiences

Issues include:  

- [x] Export data in BagIt format: #604 #169 
- [x] Establish workflow from crowd.loc.gov to loc.gov 

We know we are successful when:

**Comment by VVH** [comment]
Adding a bug here: When I try to export bagit from either live/prod or dev as of yesterday and today (Nov 14-15th) I get 500 errors. "HTTP 500 Error. The server encountered an unexpected condition which prevented it from fulfilling the request. Our staff have been notified about the failure."

**Comment by rstorey** [comment]
This bug is pretty old and I can't reproduce it. The original acceptance criteria have been satisfied.
