### ISSUE TITLE
Generate baseline site analytics

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#612]
Acceptance criteria: 

- [ ] Identifying all the places where we get reporting

Metrics: 
- Site movement and flow
- Volunteer activity on the site
- Engagement 

Platforms:
1. Adobe
2. Admin dashboard
3. Kibana(?)
4. Social 
5. History Hub
6. GovDelivery 
7. GitHub
8. Email
9. Cloudflare(?)

- [ ] Document the hacks to answer the open questions we still have
- [ ] Generate baseline report (slide deck)
- [ ] Document what is missing

**Comment by rstorey** [comment]
I believe this ticket is obsoleted by the reports @lalgee has been creating.

**Comment by elainekamlley** [comment]
We did this!!
