### ISSUE TITLE
Be able to make edits to static content w/out creating a release version

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#616]
Community managers often need to make edits to static pages to correct typos, refine guides or add a update to the latest page. We need a solution that by passes the regular PR process similar to campaign content.

**Comment by acdha** [comment]
We should decide whether this is anything more than migrating our current static pages into the database. In particular, do we want the ability to create _new_ pages on the fly or just to update the text on existing pages?

**Comment by elainekamlley** [comment]
We can hold off on this for a sprint or two as we are rethinking the `Latest` page and how we share updates with volunteers. We are creating mocks of that as described in #660. But definitively we won't create new pages and this will be only be updating existing static pages.
