### ISSUE TITLE
Newsletter export to include just email and username

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#624]
The admin feature to export newsletter subscribers includes additional. It should include just username and email address.

**Comment by rstorey** [comment]
Do we really want strictly the username and email address and no other fields? If so, the current PR needs to be modified.

**Comment by acdha** [comment]
I would like to avoid that since it increases the amount of code we have to support

**Comment by rstorey** [comment]
This is done?

**Comment by acdha** [comment]
I think so - it has more fields than originally requested but I believe @elainekamlley’s primary concern was not including the password hashes.
