### ISSUE TITLE
Update Data Model to represent "In Progress" and "Not Started"

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#634]
We will update the database to split the data model - from "Open for Edit" into its underlying components 

- Not Started (no one has entered text in the transcription field)
- In Progress (some text has been entered in the transcription field OR nothing to transcribe but not yet submitted for review)

Acceptance Criteria

- [ ] Update reflected in the progress bar on the campaign view of projects, project view of items, and item view of assets
- [ ] Update reflected in the filtering on the item view of assets 
- [ ] Accurate counts of available images based on their transcription, review, or completed state

Relates to data model #209 & filtering #321

**Comment by rstorey** [comment]
See https://github.com/LibraryOfCongress/concordia/tree/status-refactor
