### ISSUE TITLE
Assets that are in progress have no buttons

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#643]
**What behavior did you observe? Please describe the bug**
I'm unable to edit the text, the buttons for Save and Submit for Review are gone.

**How can we reproduce the bug?**
1. Go to any asset that isn't yet started.
2. Enter some text.
3. Click save.
4. Refresh the page.

**What is the expected behavior?**
Should be able to continue editing once something has moved from Not Started to In Progress.

**Got screenshots? This helps us identify the issue**
![screen shot 2018-11-15 at 5 01 12 pm](https://user-images.githubusercontent.com/5270415/48584576-1e23db80-e8f8-11e8-94d4-8f59bdfe4fd9.png)
![screen shot 2018-11-15 at 5 01 03 pm](https://user-images.githubusercontent.com/5270415/48584577-1e23db80-e8f8-11e8-8f88-6fa68d3e19a0.png)
![screen shot 2018-11-15 at 5 00 52 pm](https://user-images.githubusercontent.com/5270415/48584578-1e23db80-e8f8-11e8-92ba-bdae1b9dcb56.png)

**Desktop (please complete the following information):**

**Additional context**
https://crowd.loc.gov/campaigns/letters-to-lincoln/1862-civil-war-death-of-willie-lincoln-drafts-of-emancipation-proclamation/mal1801100/mal1801100-4/

**Comment by acdha** [comment]
Fixed in https://github.com/LibraryOfCongress/concordia/commit/a616d12097efbd5b9ec73239157ee97011554768

**Comment by colefemeno** [comment]
The same issue is present for assets in Review state
Additionally the "status" of the page does not appear about "Transcription" and field for pages that are In Progress and Review

**Comment by rstorey** [comment]
See #644

**Comment by rstorey** [comment]
Fixed in #645
