### ISSUE TITLE
Propagate selected filter settings to other navigation levels

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#647]
**When I filter on items or projects, the new project bar colors and filtering don't always lead me to where they should**

If I click on "not started" "submitted for review" or anything else, I get taken to a list of items or assets that either includes a range of these properties, or sometimes the opposite of what I'm looking for. I think this is partly the result of us showing all pages sequentially, and not weeding out things that don't fit with criteria we're searching on. It might also be a lag in the database and site syncing. 

**How can we reproduce the bug?**
1. Go to a project within a campaign
2. Click on one of the filtering options
3. Try selecting a page that meets the criteria you're looking for. 
4. In some cases the error won't occur--you'll see what you're looking for, but many time you drill down to assets that don't match the criteria. 

**What is the expected behavior?**
If I filter to see only not started pages, only show me not started pages. 

Confirmed on multiple machines and browsers, including pc. desktop and mac laptop high sierra, latest chrome. 

**Additional context**
These errors arose during a fast-paced build. A lesson to us to go slower with future feature changes.

**Comment by acdha** [comment]
Please include URLs for pages which are affected. It sounds like what is happening is that you’re finding a project/item which has assets in multiple states and the filter selections aren’t persisted as you drill down, which is scheduled to be added in the current sprint.

**Comment by acdha** [comment]
If you want to compare the difference, crowd-dev adds the code to pass filter values to other levels so e.g. when you're filtering the list of campaigns the list on a page like https://crowd-dev.loc.gov/campaigns/letters-to-lincoln/?transcription_status=in_progress will include that value in each project link such as https://crowd-dev.loc.gov/campaigns/letters-to-lincoln/1858-1859-presidential-nomination/?transcription_status=in_progress

**Comment by VVH** [comment]
When trying to grab a link to put in here today I found that if I click on the radio buttons again at each stage as I drill down from project, item, asset, the search results narrow again. I remember something from the stand up when we were talking about filtering that it didn't persist through, but that this would change in future. If yes, then this is a known behavior. I'd like to be able to feed back this information to our volunteers via History Hub if we're likely to have the current functionality in place for a while.

**Comment by acdha** [comment]
The code is already done & on test so it should go out in the next release with the other work from the second half of sprint 14

**Comment by elainekamlley** [comment]
This is done
