### ISSUE TITLE
Review anonymous rate limit thresholds

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#658]
We should review the asset reservation system so we could handle a room of students in the case where people don’t want to create accounts for kids

**Comment by elainekamlley** [comment]
Open questions we need to answer:

- [ ] What is the maximum time a asset can be reserved? 
- [ ] How many asset reservations should one IP address have? 
- [ ] What are the user stories in a classroom environment?

**Comment by acdha** [comment]
Also:
How would we know if someone hits the limit? Can we relax it with notice?

**Comment by rstorey** [comment]
@acdha - above has the current rate limits for anon activity. Should we adjust any of these?

**Comment by rstorey** [comment]
I sort of want to eliminate the save and submit rate limits for anonymous activity, and increase the number of assets that anonymous can reserve from one IP to something like 100.

**Comment by acdha** [comment]
Yeah, I think something like that is reasonable. One alternative would just be continuing our pivot to use the CAPTCHA more and change more of those to require a recent CAPTCHA but not a rate-limit.

**Comment by rstorey** [comment]
Summary of rate limit configuration:

The login form is rate limited by username. Three failed logins by the same user within 15 minutes will prompt a CAPTCHA.

The registration form is rate limited by IP address for invalid registration attempts. If there are more than 10 invalid registration attempts per hour from an IP address, the IP address will be blocked from using the registration form at all.

The asset reservation system is rate limited by IP address for anonymous users only. Up to 100 asset reservations can be made anonymously from one IP address per minute.
