### ISSUE TITLE
Add newsletter opt-in/out to user profile page

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#659]
**Is your feature request related to a problem? Please describe.**
Users currently can only opt in to the newsletter at registration.

**Describe the solution you'd like**
Users should be able to opt-in or out of the newsletter on their profile page.  This could be a tick box and a brief description of the newsletter for example:

☐ I would like to recieve updates about crowd.loc.gov collections, projects, and events

**Describe alternatives you've considered**
Is there a way to feed this data directly into GovDelivery?  I'm not aware of one, but that would be great.

**Additional context**

**Comment by acdha** [comment]
This is good to get back on the schedule. We need to talk about how this would work with GovDelivery to keep the status synchronized on both sides so e.g. someone who unsubscribes over there won’t be re-added later.

**Comment by rstorey** [comment]
As @acdha alluded to, we'd need some way to synchronize data between GovDelivery and our User database, so that folks who unsubscribe through GovDelivery don't get re-subscribed. Is that possible?

**Comment by lalgee** [comment]
Based on current workflows we would have to manually remove users who opted themselveso out in Concordia from GovDelivery so there would need to be an alert to CM's to make sure we do this.  I think this ticket should be moved into backlog.  Good call adding the CM WIP label, Rosie.
