### ISSUE TITLE
Document testing and release process

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#661]
As a agile team, we need to document how we are testing the new functionality that was worked on in the sprint so that we are aligned when acceptance user testing is complete 

As a agile team, we need to document when we are releasing new features to production

Acceptance criteria: 
- [x] updated `how-we-work.md` with testing and release cadence

**Comment by rstorey** [comment]
See #682

**Comment by rstorey** [comment]
This is done with #682 being merged
