### ISSUE TITLE
Send fresh activation email when activation time window expires

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#662]
**Is your feature request related to a problem? Please describe.**
If users wait beyond the 48 hour window for activating their account, there should be a way for them to ask for a new activation email.

**Describe the solution you'd like**
If activation fails, provide the user a link to send a new email.

**Comment by acdha** [comment]
Currently the activation process allows a one-time transition setting the user's active flag to true. The easiest way to implement this would be to simply have the reset password function set active=true on success but that would also remove the ability to disable someone's account without doing something like setting an unusable password. That seems reasonable to me and I'll implement it as a first-pass for review.

One alternative to this would be taking an approach like https://github.com/mfogel/django-simple-email-confirmation where we would allow multiple email addresses per-account (addressing #514) and decouple address validation from account activation. That would also allow us to reconsider the requirement to verify an address before logging in (see #507) but that's potentially a larger policy change than we want to deal with.

**Comment by elainekamlley** [comment]
Roughly 10% of registered users have not activated their accounts. Instead of having users request a new link could we send another email that prompts and provide users another opportunity to activate. Preferably it would be an email with a message reminding users that they registered that includes a fresh activation link after 48 hours of initial sign up.

**Comment by rstorey** [comment]
Few questions for @elainekamlley and @lalgee:

1. If a user attempts to log in with an inactive account (with username / password matching), should we re-send the/an activation email and give them a nice message? That way if a user tries to resolve the problem on their own, they can do so without CM intervention.
1. So for new users that register who are initially inactive, if they don't activate within 48 hours they'll get a follow-up email. What about after that?
1. What should we do with the 10% of existing users who aren't activated? Should they get a different email with different language?
1. What about the reset password function? Should that presumably also resend the activation email if the user is inactive? Can inactive users even reset their passwords?

**Comment by rstorey** [comment]
1. Reset password function will activate account
1. If you register you automatically get another email after 48 hours if still inactive
1. After login with correct username and password and it is not activated - a message shows to say check email to activate
