### ISSUE TITLE
Image adjustment and filtering in viewer (e.g. faint writing, poor photo)

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#666]
**Is your feature request related to a problem? Please describe.**
As a volunteer, some items are difficult to read due to the writing being faint or the photograph of it being poor.

**Describe the solution you'd like**
I would like to be able to adjust the image within the viewer.  In the same way that I can already zoom in and out, I would like to be able to adjust the contrast/brightness of an image and/or make it negative/positive.

**Describe alternatives you've considered**
Not sure if these features can be added to Open Seadragon or if another viewer would be necessary.

**Additional context**
Example hard-to-read documents: 
1. https://crowd.loc.gov/campaigns/civil-war-soldiers-disabled-but-not-disheartened/left-hand-penmanship-contest/mss13375008/mss13375008-52/
2. https://crowd.loc.gov/campaigns/clara-barton-angel-of-the-battlefield/diaries-and-journals-1881-1889/mss119730034/mss119730034-2/

**Comment by acdha** [comment]
We should start by trying NIST's filtering plugin:

https://github.com/usnistgov/OpenSeadragonFiltering

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-65](https://staff.loc.gov/tasks/browse/CONCD-65)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
