### ISSUE TITLE
Visually indicate whether image or text area has keyboard focus

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#679]
**Is your feature request related to a problem? Please describe.**
Currently some viewer keyboard shortcuts are letter keys which leads to users inadvertently moving/adjusting the image in unexpected ways when trying to transcribe.  For example the "F" key mirrors the image. 

**Describe the solution you'd like**
Keyboard shortcuts need to be retained for accessability. Change viewer keyboard shortcuts to be non-letter/central keys.

**Additional context**
Real user story: What am I clicking on that switches the page to a mirror image? How can I reverse it back to the normal view. It's happened twice in a matter of a few minutes.

**Comment by acdha** [comment]
Note that this is only possible when the keyboard focus is on the viewer, so perhaps a partial area for improvement might be to have a prominent focus indicator for the viewer to make it more obvious where keyboard events will be received.

**Comment by rstorey** [comment]
This is a dupe of #824

**Comment by acdha** [comment]
The textarea already has a focus indicator so this might be a good task for @klee72 to make some improvements to make it more prominent (e.g. it's very visible using the standard system cues on MacOS; I haven't tested on Windows recently) and to apply it to the image viewer's container when focused.
