### ISSUE TITLE
Improvements to CAPTCHA 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#684]
**Is your feature request related to a problem? Please describe.**
I was using the CAPTCHA feature when testing the rate limit and while it worked it was fairly difficult to read. Overall CAPTCHA, in the site is fairly difficult to read

On the log in page a few things: 
1. The window slightly bled into the text box
2. Make the window bigger 
3. Add a refresh button if the user can't read it
4. Add a boarder around the captcha window
![screen shot 2018-12-05 at 4 22 33 pm](https://user-images.githubusercontent.com/7362915/49552990-99026580-f8aa-11e8-919b-5a0f696dd9b8.png)

**Describe the solution you'd like**
1. Could we use another library or a set of numbers and letters that are more legible? 
2. If not can we increase the size of the boxes across the board. I think we can give more space on the page to this feature since it is the only action the user can take before getting to the site features.
3. Add more instructions to the log in page like below: 

![screen shot 2018-12-05 at 4 33 03 pm](https://user-images.githubusercontent.com/7362915/49553223-90f6f580-f8ab-11e8-9002-203cc56272ea.png)

**Describe alternatives you've considered**
I could zoom in using `command & +` but that's not always known to all computer users

**Comment by acdha** [comment]
We should be able to do make it larger and more distinct, like on the transcription page, but legibility changes are complicated by trying to keep it OCR resistant. Since this only applies to people who’ve hit the rate-limit I’m inclined to defer changes to that at first. If anything, we should switch to text from the left-handed penmanship contest items 😀

**Comment by jbresner** [comment]
@acdha - I'm sure you've explored it as an option but what's the downside to starting with reCAPTCHA v2 (the "I'm a human" checkbox) for this instead? Is it not considered as foolproof as starting with challenge?

**Comment by acdha** [comment]
reCAPTCHA is a third-party service which we don't have permission to use. We'd need to get that approved before we could use it.

**Comment by NGTmeaty** [comment]
I like the idea of switching to text from the left-handed penmanship contest!
