### ISSUE TITLE
Next iteration of mobile and tablet layout - transcription page

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#685]
**Is your feature request related to a problem? Please describe.**
When looking at an asset on a mobile smart phone, there are still noticeable layout issues. A few items that stuck out to me when testing: 
1. The find new page button is outside the main view
2. The slider is to the right and I am unable to engage with this feature
3. The first thing I want to do is look at the picture so I click the full page icon in the viewer, but there is no obvious way to get out of full view unless I hit the back button that takes me to the last page I was on.  

![image from ios](https://user-images.githubusercontent.com/7362915/49553823-56db2300-f8ae-11e8-83e2-72f8b02efabe.png)

**Describe the solution you'd like**
1. Update the layout to bring in the find a new page button like the mocks below. 
2. Move the divider of the viewer and the text field and the slider below the viewer
3. Add a exit full screen button when you are in full screen

![transcribe-480](https://user-images.githubusercontent.com/4275957/48175541-895b2580-e2da-11e8-81a2-4e848231188d.png)
![transcribe-768x1024-landscape](https://user-images.githubusercontent.com/4275957/48175543-895b2580-e2da-11e8-87d0-91bb5b91dc24.png)

_Originally posted by @jbresner in https://github.com/LibraryOfCongress/concordia/issues/549#issuecomment-436859031_

**Comment by VVH** [comment]
In addition to improving the layout, the community managers and our in house LOC informatics person discussed the idea of showing a pop up when people have hit the site while on a mobile device. Pop up could, for example, say "Welcome! By the People is a transcription and review website best used on a larger device. Would you like to send yourself the link for later?" --a box for them to enter their email could appear if they click on "send yourself the link for later". The email could include crowd.loc.gov link itself, and information on how to register.

**Comment by elainekamlley** [comment]
Transcription activities are recommended for a larger screen. Closing this ticket since it is not a priority.
