### ISSUE TITLE
Show/Hide Tags button on Transcription page

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#686]
**Is your feature request related to a problem? Please describe.**

Opening this ticket to resume the conversation about hiding and showing tags. From #444 @colefemeno: the “show tags” button corresponds to what is shown in the “Submit”/Accept modal (the “add tags” button), so that seems like a starting point for reminding folks it’s possible to tag. @jbresner any thoughts about having “Show”/“Hide” tags in the UI? Anyone have thoughts about See vs Show vs Add for that button?

**Describe the solution you'd like**
Add a show tags button from @acdha in #444: 

![image](https://user-images.githubusercontent.com/46565/47240486-737ed280-d3b6-11e8-975d-ed1f076d35a2.png)

**Comment by acdha** [comment]
That might also be a good use of an accordion or a disclosure triangle since those are common UI controls for this kind of task. We might also want to regroup around the tagging discussion since this will further de-emphasize that activity.
