### ISSUE TITLE
Search transcriptions by username

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#691]
Testing in stage for issue #203 item: "In admin transcriptions page be able to search on usernames", I can perform this in dev but not stage. 

**How can we reproduce the bug?**
1. Go to https://crowd-dev.loc.gov/admin/concordia/transcription/ 
2. Type a known username into the search field, i.e. VVH
3. Click enter/return/search and there are no results in stage, but there are results in dev.

**What is the expected behavior?**
See all transcriptions for a user when you search on their name in transcriptions as in dev

 - Windows 7 (Library machine)
 - Chrome 70

Most other aspects of the ticket are in order.

**Comment by elainekamlley** [comment]
Thanks @VVH! @rstorey could we add this to the latest release? or should we just wait till the next one?

**Comment by rstorey** [comment]
Yes, we can cherry-pick this commit into the release branch: https://github.com/LibraryOfCongress/concordia/commit/659e2b1362604be3c7b8532f1fc61cf4e47b106e

I'll do that now.

**Comment by elainekamlley** [comment]
Thank you!

**Comment by elainekamlley** [comment]
This is being pulled into stage, so we can close this ticket.
