### ISSUE TITLE
Spike on tagging - accepting tag policy and tag utility

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#694]
**Is your feature request related to a problem? Please describe.**
Currently, users are able to add any tag. We need to refine our policies around accepted tags

**Describe the solution you'd like**
We need to answer the following questions: 
1. What is the utility of tags? Collating and gathering a group of assets? Are they for discovery and establishing a relationship with other items across campaigns? Personalization ex. `For Mrs Smith's class` 
2. How are we not duplicating the exiting controlled vocabulary at the library? 
3. Are we tagging from campaign level? Do we want CM to be able to add these tags? 

**Describe alternatives you've considered**

**Acceptance Criteria**
- Document with agreements from spike
- Issues generated based on new policies

**Comment by acdha** [comment]
As an extension from the second point we should consider whether the answers to the first question  mean that we actually have multiple concepts for tagging where some tags are completely arbitrary values and others are favoring or requiring selection from an outside list (e.g. language codes, Civil War regiments or battles, baseball teams, etc.). That could have significant implications for the database and UI design as well as the utility of the data (e.g. having standard ISO language codes makes it a lot easier to tell search tools how to index text).
