### ISSUE TITLE
Add license and contribution policy documentation

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#70]
All projects — whether internal and open-source — should make it easy to tell
which license(s) apply to their code. The best way to do this is to avoid
committing code which is not owned by the Library and instead using a package
manager to download it as part of the build process. This keeps our repositories
small, affirms that we are not modifying the code in question, and avoids having
to document which third-part code is being redistributed and that we are legally
allowed to do so.

If there is a good reason why this cannot be done, such as an upstream project
which does not cleanly package its code, third-party code should be stored in a
vendor or external directory in a directory which contains both the code and
a README or LICENSE file providing context and making it clear that the Library
is not claiming ownership of the code in question.

Acceptance criteria:

- [x]  As a potential user of this software, I want to easily see under what license this software is distributed. This includes any third-party libraries included in the code distribution, which should each have README and LICENSE files.
- [x] As a potential contributor of code, I want to know under what license my contributions would be redistributed.
- [x] As a potential contributor of code, I want to know what the policy is for accepting or rejecting code contributions to this project.
- [x]  As a potential end user or developer, I need to know the copyright status for the code base.

**Comment by rstorey** [comment]
Examples:
https://github.com/LibraryOfCongress/bagger-js/blob/master/LICENSE.md
https://github.com/LibraryOfCongress/bagger-js/blob/master/README.md#contributor-guidelines
https://github.com/LibraryOfCongress/django-tabular-export/blob/master/CONTRIBUTING.rst
https://github.com/LibraryOfCongress/django-tabular-export/blob/master/LICENSE
https://help.github.com/articles/about-issue-and-pull-request-templates/

**Comment by rstorey** [comment]
See #22

**Comment by rstorey** [comment]
We still don't have a license file in the codebase. There's probably something standard we should distribute.

**Comment by elainekamlley** [comment]
This is done
