### ISSUE TITLE
Inconsistent status on item page and asset page 

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#705]
**What behavior did you observe? Please describe the bug**
When I am an anonymous user on the item page, viewing the assets, I see a page labeled as "Review" status. 
When I click through to the page (still anonymous), the asset is "In Progress". 
This discrepancy persists when I am logged in as a registered user (and Admin).

**How can we reproduce the bug?**
1. Go to https://crowd.loc.gov/campaigns/letters-to-lincoln/1861-secession-inauguration-start-of-civil-war/mal0942600/
2. Find the third asset, which is listed as "Review" status
3. Arrive on https://crowd.loc.gov/campaigns/letters-to-lincoln/1861-secession-inauguration-start-of-civil-war/mal0942600/mal0942600-3/
3. See the status above the transcription window is "In Progress"

**What is the expected behavior?**
The status of an asset on the item page should show as the same status on the asset page. 

**Got screenshots? This helps us identify the issue**

![falsereviewstate_itemassetsview_20181210](https://user-images.githubusercontent.com/31018169/49763901-eceebf00-fc9b-11e8-876e-f3a6c70fdd04.PNG)

![falsereviewstate_20181210](https://user-images.githubusercontent.com/31018169/49763906-ef511900-fc9b-11e8-8c44-e4b60fae5bcf.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
This may connect more widely to issues with surfacing "what can be done" in a project using the filters. We are exploring other volunteer feedback to determine if that's what has happened.

**Comment by colefemeno** [comment]
@lalgee @VVH please add other examples or add context - thanks!

**Comment by VVH** [comment]
This is related to #647. I've seen the example that @colefemeno described numerous times, but hadn't captured an example.

**Comment by acdha** [comment]
This is why it's so important to include the steps to reproduce a problem: #647 didn't and the prose is vague enough that it could have referred to the known lack of status propagation or something new.
