### ISSUE TITLE
Allow community managers to delete accounts but preserve its transcription/tags

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#712]
**Is your feature request related to a problem? Please describe.**
Community managers need to be able to meet user requests to delete their accounts without losing any transcription or tagging data accumulated by that account.  Currently all of that data is lost if a user is deleted.

**Describe the solution you'd like**
At the time of deletion of a user's account in the admin interface, allow community managers to choose to either delete the users' contribution or transfer to anonymous.  The preferred/more common choice is expected to be to keep the user data, so perhaps that is the default that can be unchecked or overridden as necessary.

**Comment by acdha** [comment]
Rather than having two ways to delete things, we could also just have a command to move a user's data to a different account which could be used before running the standard deletion UI. Since this is a somewhat invasive operation we'd also want to think about whether there would be some need to move individual records back (in case of mistakes) or at least confirm that the modifications are recorded in the admin history at a sufficient level of detail to notice this.

**Comment by elainekamlley** [comment]
@acdha would this be a command line command or a action you can do in the Admin?

**Comment by acdha** [comment]
That would depend on exactly what we decide it needs to do. If we need the ability to assign them to a different account that would have to be an admin action with a screen to select the target user. If we just say that deleting a user will assign their transcriptions to the anonymous user we could have Django do that automatically using the [`on_delete` `SET()`](https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.ForeignKey.on_delete) mechanism.

**Comment by rstorey** [comment]
What about users who have reviewed transcriptions? What should we do with those contributions?

**Comment by elainekamlley** [comment]
How about stripping the user info from the account? Essentially keeping the user unique ID and preserving the actions but removing all personal information.

By stripping all personal info I think this falls inline with EU's right to erasure: https://gdpr-info.eu/art-17-gdpr/
