### ISSUE TITLE
Replace logo with correct orange color

### ISSUE THREAD

**Issue by jbresner** [LibraryOfCongress/concordia#713]
The orange in the logo is the wrong hex value. The attached SVG file has the approved orange color (#F05129).
[logo.svg.zip](https://github.com/LibraryOfCongress/concordia/files/2669730/logo.svg.zip)

**Comment by jbresner** [comment]
Correct. Wasn’t sure if that could/should be same ticket.

**Comment by acdha** [comment]
I'll put in there since we're reviewing that actively. Thanks!
