### ISSUE TITLE
unable to use Hypothes.is bookmarklet/extension to annotate page

### ISSUE THREAD

**Issue by emckean** [LibraryOfCongress/concordia#714]
**What behavior did you observe? Please describe the bug**
In both Firefox (63.0.3) and Chrome (Version 70.0.3538.110 (Official Build)) the Hypothes.is [bookmarklet](https://web.hypothes.is/start/#)/[extension](https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek?hl=en) is unable to annotate text. 
**How can we reproduce the bug?**
1. Install the bookmarklet or Chrome extension
2. Go to https://crowd.loc.gov/campaigns/branch-rickey-changing-the-game/scouting-reports/mss37820001/mss37820001-2/
3. Activate the extension or bookmarklet by clicking on the icon
4. Highlight the sentence "Everything depends upon stage fright, or possibly give-up-ness. "
5. No Hypothes.is annotation tooltip appears. 

**What is the expected behavior?**
When highlighting a sentence with Hypothes.is enabled, you should see a tooltip that annotates that particular sentence. 

**Got screenshots? This helps us identify the issue**
Screenshots from NYT to show how it looks when it's enabled, also a screenshot from the LoC site showing no "quote" button
<img width="721" alt="screen shot 2018-12-11 at 4 53 51 pm" src="https://user-images.githubusercontent.com/225433/49839762-6a323680-fd65-11e8-9b3c-233fbe311290.png">
<img width="478" alt="screen shot 2018-12-11 at 4 53 01 pm" src="https://user-images.githubusercontent.com/225433/49839764-6a323680-fd65-11e8-8f37-445e90022c54.png">
<img width="720" alt="screen shot 2018-12-11 at 4 52 54 pm" src="https://user-images.githubusercontent.com/225433/49839765-6a323680-fd65-11e8-8841-95136f88caa5.png">
<img width="710" alt="screen shot 2018-12-11 at 4 41 28 pm" src="https://user-images.githubusercontent.com/225433/49839766-6a323680-fd65-11e8-9d47-ab28971908d7.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox (63.0.3) and Chrome (Version 70.0.3538.110 (Official Build))

**Additional context**
I checked with the Hypothes.is Slack and they said: "Looks like they’ve added a “readonly” class to the `textarea` where the transcription text is. I’m guessing there’s something in their CSS or JS that is preventing the annotation adder from popping up"

Thank you!!

**Comment by rstorey** [comment]
Since we're using textareas to display the content in the classic UI, it seems our site is incompatible with this particular browser extension. It might work with pages in review or completed pages in the new activity-based UI.
