### ISSUE TITLE
Include attribution in exported text files

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#717]
**Is your feature request related to a problem? Please describe.**
The plain text files, one per page / asset, which are exported in BagIt form need to have attributions at the bottom of the text.

**Describe the solution you'd like**
Each text file should contain the attribution "Transcribed and reviewed by volunteers participating in the By The People project at crowd.loc.gov." at the bottom.

**Comment by acdha** [comment]
This feels like something which should be done on the display side since it's not part of our content and would need to be stripped out by any other user of that data. Maybe that should happen in ETL?
