### ISSUE TITLE
As a user, I can begin transcribing a document that has not been transcribed before 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#72]

**Comment by rstorey** [comment]
Is this ticket meant to encompass the functionality of the "Get started" button on the home page? As a user, when I arrive at the home page and click the Get Started button, I should go to a page that needs to be transcribed (has not yet been transcribed).

**Comment by elainekamlley** [comment]
No not quite. It is when a user clicks on the transcribe button on an image thumbnail and there is no transcription, just the large image and a clean text box. A follow up question: would this be the experience for all transcriptions whether or not there has been a previous user who has transcribed that same artifact? Or will you see the partially completed transcript?
