### ISSUE TITLE
User Profile Page: Break out My Contributions Campaign level Actions into Transcribe & Review

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#723]
**Is your feature request related to a problem? Please describe.**
My Contributions tells me my total contributions per project as a cumulative "Actions." 

**Describe the solution you'd like**
As a user setting goals for myself for review and transcription, I would like to see my "Actions" for each project broken out into transcriptions and reviews. 

As an admin I want to see review count next to transcription count in the Django admin.

**Describe alternatives you've considered**
- I can try to keep track of them myself as I work
- I can copy the reports of time - action - item (etc) and then make my own tallies in a spreadsheet

**Additional context**

relates to #532

**Comment by acdha** [comment]
https://github.com/LibraryOfCongress/concordia/pull/678 should be in the next release and it breaks down contributions for each page separately. Perhaps it would be useful to discuss additional changes against that as a baseline.

**Comment by colefemeno** [comment]
@acdha sure thing - this is specific enhancement request for the top reporting for the Campaigns contributions.  Definitely think we'll iterate on this and I will revise the requested enhancement based on what is implemented with #678. Additionally, we can couple with feedback from volunteers based on the next release :+1:

**Comment by lalgee** [comment]
Superceded by https://github.com/LibraryOfCongress/concordia/issues/1335
