### ISSUE TITLE
First help center question not opening up

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#725]
While making changes via the new static page editor in admin I did something wrong and now the first question "What is By the People and what is crowdsourcing?" doesn't open. I thought I'd found the problem--an extraneous " after a # but that wasn't it. Will try again tomorrow.

**Comment by acdha** [comment]
Those pages have a 5 minute cache time – add a querystring with a number (e.g. `?1234`) if Control-F5 / Shift-Command-R doesn’t get the latest version.
