### ISSUE TITLE
Add the "By the People" text to the History Hub banner

### ISSUE THREAD

**Issue by jbresner** [LibraryOfCongress/concordia#727]
Add the "By the People" text to the History Hub banner.

**Comment by jbresner** [comment]
@lalgee here are two updated banners for History Hub. The "By the People" text is the more emphasized copy and uses the "Druk" typeface in the orange color. Let me know if you have a preference or additional feedback.

![banner-02](https://user-images.githubusercontent.com/4275957/50175030-c4814900-02c9-11e9-9482-ec91754858e4.png)
![banner-03](https://user-images.githubusercontent.com/4275957/50175031-c4814900-02c9-11e9-83bb-802f591e1fb5.png)

**Comment by lalgee** [comment]
thanks @jbresner !  Let's go with option 1.
