### ISSUE TITLE
Anonymous user asset reservation should be browser session based

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#730]
**Is your feature request related to a problem? Please describe.**
From @acdha 

> with anonymous users the locks are all shared since they’re mapped to the same user behind the
> scenes. That probably needs to be linked to a browser session cookie so we can distinguish 
> between people who happen across the same page. The find-next-page feature skips assets with
> active registrations but it’s still possible to hit them.

**Describe the solution you'd like**
DIsambiguate the anonymous user asset reservations so that different browser sessions aren't  shared behind the scenes.

**Comment by rstorey** [comment]
> **Is your feature request related to a problem? Please describe.**
> From @acdha
> 
> ```
> with anonymous users the locks are all shared since they’re mapped to the same user behind the scenes. That probably needs to be linked to a browser session cookie so we can distinguish between people who happen across the same page. The find-next-page feature skips assets with active registrations but it’s still possible to hit them.
> ```
> **Describe the solution you'd like**
> DIsambiguate the anonymous user asset reservations so that different browser sessions aren't shared behind the scenes.

**Comment by acdha** [comment]
I'm also wondering whether this is time to move locking into Redis since we're already decoupling it a bit from the database as it is.

**Comment by acdha** [comment]
This seems like a good time to make a couple of related changes — how's this sound?

* Switch locking to redis
* For anonymous users, tie locks to a session ID following a successful CAPTCHA (which is also just doing things like HTTP 400s for reservation requests without a session rather than starting a new one)
* Adding some metrics for something like the number of active locks, the subset which are anonymous, number of distinct real/anonymous users, etc.

**Comment by rstorey** [comment]
I have some questions about how you imagine the CAPTCHA bit would work. I don't think we should tie the session ID to a successful CAPTCHA - I think that puts CAPTCHA completion too early in the flow. Can't we establish a session without requiring CAPTCHA? The first time an anonymous user saves something, then they have to complete the CAPTCHA. If they're just browsing, they shouldn't have to complete it.

**Comment by acdha** [comment]
I was thinking about making the CAPTCHA a requirement to *lock* an asset which would also mean changing it so we don't reserve until someone attempts to start editing.

**Comment by rstorey** [comment]
We need to do this in order for the prototype reservation system to function effectively with anonymous users. Perhaps we have to consider launching it only for registered users until we get this done.

**Comment by acdha** [comment]
I think that's reasonable — the problem being that we want to badge the asset list for unavailable assets?

**Comment by rstorey** [comment]
Yep. Currently there's no way to be able to badge unavailable assets for anonymous users because they all share the same user pk. Also, I'm wondering whether letting anonymous users consume our websocket messages, which have user pks in them, is a good idea.
