### ISSUE TITLE
Print friendly view for transcriptions

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#734]
**Is your feature request related to a problem? Please describe.**
There's no way to create nice-looking PDFs of transcribed assets / items. Only plain text is exported.

**Describe the solution you'd like**
I'd like a way to print completed transcription for an asset or an item with some basic formatting. The printable version could also be made into a PDF.

**Describe alternatives you've considered**
Considered converting plain text into plain PDFs directly, but it doesn't yield a nice result and it's a lot of dev time.

**Comment by acdha** [comment]
Rough thought here: add either a print-friendly stylesheet for the asset detail page (which gives the latest transcription) or a separate text/plain alternative view, both of which are useful for working with the content and allow the path to generating PDFs to be as simple as [`chrome --print-to-pdf`](https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom) or [using puppeteer](https://www.npmjs.com/package/puppeteer#usage) with no duplication of effort beyond the standard web stack.

**Comment by klee72** [comment]
Is this the page in discussion? https://crowd.loc.gov/campaigns/letters-to-lincoln/1850-1857-death-and-birth-of-children-and-re-entry-to-politics/mal0043300/mal0043300-1/

**Comment by klee72** [comment]
It looks like adding a print friendly stylesheet and utilizing bootstrap print display classes shouldn't be too difficult to do. If you guys are up for it, I can start looking into this.

**Comment by acdha** [comment]
That seems reasonable to me — since the basic Bootstrap approach tends to result in printing being like a mobile device it should be mostly about hiding things like form inputs & labels which don't make sense (or, in the transcription's case, adjusting the borders & max-height to act like a text block).

**Comment by rstorey** [comment]
Sounds good to me

**Comment by rstorey** [comment]
This has been merged
