### ISSUE TITLE
One project progress bar is inaccurate on Letters to Lincoln Campaign page 

### ISSUE THREAD

**Issue by colefemeno** [LibraryOfCongress/concordia#738]
**What behavior did you observe? Please describe the bug**
On the Letters to Lincoln Campaign page (projects view), the 1858-1859 project progress bar suggests over 50% of the project has not been started. However, the project is 50% completed, 50% submitted for review when you click through to the project page (items view). All other project progress bars seem to accurately reflect progress at the Campaign and Project level.

**How can we reproduce the bug?**
1. Go to https://crowd.loc.gov/campaigns/letters-to-lincoln/
2. See the 1858-1859: Presidential nomination project and its progress bar
3. Click on 1858-1859: Presidential nomination project (https://crowd.loc.gov/campaigns/letters-to-lincoln/1858-1859-presidential-nomination/?)
4. See the project progress bar

**What is the expected behavior?**
The project progress bar should be the same at each level - campaign and project.

**Got screenshots? This helps us identify the issue**
Inaccurate progress bar on Campaign page
![image](https://user-images.githubusercontent.com/31018169/50612033-89c10880-0ea6-11e9-9932-28a34f966815.png)

Accurate progress bar on Project Page
![image](https://user-images.githubusercontent.com/31018169/50611999-6c8c3a00-0ea6-11e9-80c8-bd8416e51699.png)

**Desktop (please complete the following information):**
 - Chrome 
 - Windows 7 Enterprise

**Additional context**

**Comment by acdha** [comment]
That project has a substantial number of unpublished items – 145 out of 245 — and that's around the same percentage non-empty portion of the bar on the campaign page.

**Comment by colefemeno** [comment]
Thanks @acdha - we have published the items now. Looks like that may have been an artifact of the manual publishing process.

**Comment by acdha** [comment]
Thanks for reporting this! That definitely needed to be fixed since it's confusing and it's entirely reasonable to hold back items for arbitrary reasons.
