### ISSUE TITLE
Discrepancy in number of published/unpublished assets

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#743]
Recently the number of total unpublished assets in By the People decreased by 12, yet the number of published assets does not appear to have changed.  

Hypotheses:
- The spreadsheet that shows the discrepency is incorrect.  We think this is unlikely but could be checked using Kibana.
- The 12 assets were lost sometime during/following original import and this was revealed when we recently published items in Letters to Lincoln that were accidentally hidden.
- ?

This change was only noticed today and we are also wondering if it could be linked to the items that were published yesterday re: #738 

@colefemeno please add any additional thoughts/hypothesis

**Comment by acdha** [comment]
What are the sources of the various numbers?

**Comment by lalgee** [comment]
Unpublished assets found and accounted for!  They were in Bourne.  Probably just missed during the manual import/publish process back in October and somehow unnoticed until now.

All 12 are now published

**Comment by elainekamlley** [comment]
Also, we found them in the site report. So yay @rstorey!
