### ISSUE TITLE
As a reviewer, when I accept a completed transcription I want the option to keep reviewing

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#749]
**Is your feature request related to a problem? Please describe.**
The low rate of acceptance numbers could be a sign of bottle neck in the process. When a user clicks accept the only option is to transcribe a new page or tag, essentially pulling the user out of review.

**Additional context**
By creating a review track, we want to improve the rate of review to completion and overall awareness of the ability to review. The health of the program relies on the volunteers completing all tasks. 

**Acceptance criteria:** 
- [x] As a reviewer, when I accept a completed transcription and see the message, I want to continue doing a similar task when I click `Find a new page` 
- [x] As a reviewer, I am brought to a page that I did not submit for review
- [x] Create a new message that aligns with the review track

**Comment by acdha** [comment]
Just to record the standup conversation, I think we should do #753 now and start working with @jbresner to think about how incorporating the concept of a mode preference will ripple through the UI.

**Comment by rstorey** [comment]
How should the buttons in this dialog be arranged? What should they say? Here's a screenshot of what it currently looks like in my branch with placeholder text:

<img width="638" alt="screen shot 2019-01-17 at 2 21 20 pm" src="https://user-images.githubusercontent.com/5270415/51343034-662fbd80-1a63-11e9-97ee-b1d6c139a80f.png">

@lalgee @jbresner @VVH

**Comment by VVH** [comment]
Based on discussion in backlog: 'Review another page' 'Transcribe another page' 'Add tags' in that order

**Comment by rstorey** [comment]
![screen shot 2019-01-18 at 5 09 46 pm](https://user-images.githubusercontent.com/5270415/51415393-ab2b2100-1b43-11e9-93f7-6a958fea88bf.png)

**Comment by rstorey** [comment]
![screen shot 2019-01-18 at 5 14 54 pm](https://user-images.githubusercontent.com/5270415/51415602-5a67f800-1b44-11e9-8dbe-4e877adff6b1.png)

**Comment by colefemeno** [comment]
@rstorey I prefer the stacked buttons! The button language looks good. 
For the rest of the dialogue, can we try: 
"Nice Job!"
Thanks for your help - we've saved your decision. 
You can stay on this page to add tags or select your next page to review or transcribe."
 
@lalgee @VVH @jbresner  I've specifically left out the word "review" in the second line so we can use this message more flexibly for both saves of edits and reviews

**Comment by rstorey** [comment]
FYI, currently there is no dialog pop up that comes up when someone clicks the Edit button to reject a transcription.

**Comment by VVH** [comment]
Yes, that's right @rstorey I think we took that away in the last sprint because it was an unnecessary "Are you sure? Are you sure?" feeling. For this pop up, I think it would be clear if we cut that second sentence and tweak to read: "Nice job! Your review decision has been saved. What do you want to do next?"

**Comment by colefemeno** [comment]
Thanks @rstorey @VVH. I misused the word save instead of submit. If we're using the shared dialogue for submitting edits and for reviewing, we'll want to drop the word review. I like the final sentence "what do you want to do next." I advocate for thanking volunteers for their efforts in this step.

**Comment by acdha** [comment]
Each separate state has its own dialog, except for rejecting a transcription since that was intentionally removed. You can see the current text and buttons in the template source here:

https://github.com/LibraryOfCongress/concordia/blob/3d48d075b46de44f120b02cfd7312e9a013b3add/concordia/templates/transcriptions/asset_detail.html#L362-L417

**Comment by rstorey** [comment]
How's this?
![screen shot 2019-01-22 at 10 43 22 am](https://user-images.githubusercontent.com/5270415/51546518-4c5ef380-1e32-11e9-94c2-0d266bcfd299.png)

**Comment by acdha** [comment]
Would it be better to make this slightly shorter by collapsing the two related operations (“Review…”, “Transcribe…”) onto a single line and leaving the tags activity on the line below?

**Comment by colefemeno** [comment]
@acdha even better! So let's scratch my comments above and go with a review specific message. 
@rstorey can we have the dialogue message for review say: 
"Thanks! 
Your review decision has been saved. 
What do you want to do next?"

**Comment by rstorey** [comment]
I'm confused. @acdha suggestion is to change the thing that I did (not mocked, implemented). Do you want me to implement his suggestion or keep with how it is? I'm not sure where the idea of separate dialogs comes in. This text, and this set of buttons, is only displayed when someone clicks the "Accept" button on a transcription.

**Comment by colefemeno** [comment]
@rstorey sorry about the confusion (edited my comment above to read _implemented_). 
Please keep how it is, as you have implemented it - thanks!

**Comment by rstorey** [comment]
Preview is here: https://review-after-accept.crowd-test.loc.gov

**Comment by colefemeno** [comment]
Message and stacked buttons look great, @rstorey! 
When I clicked "Review a new page" I got a 500 error & @elainekamlley also had the same error. 
Here's the link for reference https://review-after-accept.crowd-test.loc.gov/campaigns/letters-to-lincoln/next-reviewable-asset/?project=1858-1859-presidential-nomination&item=mal0096100&asset=2854 
![image](https://user-images.githubusercontent.com/31018169/51773505-09fd1700-20bd-11e9-8cc4-4d8b773f1fa3.png)

**Comment by rstorey** [comment]
I'm deploying a bug fix now for the 500 error. The PR is pending: #767

**Comment by colefemeno** [comment]
Echoing @elainekamlley - thanks so much @rstorey! (and for the bug fix, too)

**Comment by rstorey** [comment]
Took a bit longer than I hoped for the bug fix to go out, but it's there now.
