### ISSUE TITLE
Add review section to carousel

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#750]
**Is your feature request related to a problem? Please describe.**
There is a bottle neck when reviewing transcriptions likely due to unawareness that this task exists. By adding a section to the carousel is one pathway to invite users to review. 

Acceptance criteria: 

- [x] Add image that depicts review
- [x] Write copy for CTA to invite users to review
- [x] Add button that goes directly to an asset that needs review, that was not submitted by the user. Can be added when #749 is done.

**Comment by rstorey** [comment]
Here's what my placeholder looks like in my branch. Need an image, headline, and copy. Is it okay that the button reads "Let's Go" regardless of which carousel item is active? @jbresner @VVH @lalgee 

<img width="947" alt="screen shot 2019-01-17 at 2 33 25 pm" src="https://user-images.githubusercontent.com/5270415/51343709-f7ebfa80-1a64-11e9-96c1-d74794216b41.png">

**Comment by VVH** [comment]
Text for review call to action in white box overlay in carousel: "Review other volunteers' transcriptions so these can be published on the Library's website." 

As for an image, that's a bit harder, but these are some options: 

Sheers, but this seems rather violent and not the point!
https://www.loc.gov/item/2017776362/ https://cdn.loc.gov/service/pnp/fsa/8b16000/8b16800/8b16860r.jpg 

Mary Church Terrell, first speech to NAACP:
I think we could focus in on just a part of the image where there's heavy editing: 

https://tile.loc.gov/image-services/iiif/service:mss:mss42549:mss42549-020:00518/full/pct:100/0/default.jpg 

![image](https://user-images.githubusercontent.com/6482891/51415616-6b186e00-1b44-11e9-91f0-05be97842970.png)

**Comment by lalgee** [comment]
The phrasing could be a little more action oriented. What about...

Review other volunteers' transcriptions. Completed pages need peer (or your?) approval to cross the finish line!

**Comment by elainekamlley** [comment]
Any thoughts on the button language? Keep it to `Let's go!` or maybe `Let's review!`

**Comment by rstorey** [comment]
Also, that "Let's Review" headline is something I just made up, so might wanna change that.

**Comment by acdha** [comment]
I'm wondering whether switching to the specific activity verbs would make it read better as “Start Reviewing”, “Start Transcriber”, etc.

**Comment by jbresner** [comment]
Agree with Chris. Try to keep the CTA buttons as action-oriented as possible. "Let's Review!" doesn't convey the same sense of urgency as "Review Now" or "Start Reviewing".

**Comment by jbresner** [comment]
Here are the two images Victoria selected cropped for the Crowd home page...
![sheers](https://user-images.githubusercontent.com/4275957/51548744-ef197100-1e36-11e9-92e2-1105e20550db.jpg)
![marychurchterrell](https://user-images.githubusercontent.com/4275957/51548745-efb20780-1e36-11e9-8ebc-b9011eb8d457.jpg)

**Comment by VVH** [comment]
Thanks @jbresner would you be happy to correct the skew of the handwritten page? Also, is it just me or is that hand very creepy? It reminds me of Edwards Scissorhands (Johnny Depp)

**Comment by rstorey** [comment]
Here's a draft with @lalgee text and "Review Now"
![screen shot 2019-01-22 at 11 38 35 am](https://user-images.githubusercontent.com/5270415/51550289-1291eb00-1e3a-11e9-8203-570fff94dd91.png)

**Comment by VVH** [comment]
Either Review or Review Now works for me.

**Comment by jbresner** [comment]
Here's the slightly rotated image:
![marychurchterrell](https://user-images.githubusercontent.com/4275957/51564318-ecca0d80-1e5c-11e9-862c-226e1b3c9742.jpg)

As for the scissors, it's a little Edward Scissorhands-ish but I don't think that's the problem. The issue for me is when the text box overlay is on top (on left OR right), it obscures the image a bit too much:

![scissors-left-text](https://user-images.githubusercontent.com/4275957/51564433-4a5e5a00-1e5d-11e9-844a-62c66f3836b9.png)
![scissors-right-text](https://user-images.githubusercontent.com/4275957/51564434-4a5e5a00-1e5d-11e9-9c06-ea5df008709e.png)

**Comment by acdha** [comment]
Hmmm, we currently only have the default left & right options defined: 

https://github.com/LibraryOfCongress/concordia/blob/b8f02601922355a6de41789ec4ec6af23713eac7/concordia/static/css/base.css#L760-L763

We could add another one but I'm not sure where that would go to be that much better — maybe the lower right?

**Comment by jbresner** [comment]
No, I'm not suggesting we move the box (other than the two locations we've defined). We just either need a different image OR I could try playing around with the scaling of this one.

**Comment by rstorey** [comment]
With the review section of the carousel in 4th place, it makes the most sense for the overlay to be on the right. So that way we don't have three on the left and one on the right.

**Comment by VVH** [comment]
Review carousel will need changes to order because we need to take out the Lincoln challenge carousel: 

1) Home page as is with 'Let's go'
2) Review Now  
3) Instructions
