### ISSUE TITLE
Registered users can return back to review after submitting edits

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#753]
**Is your feature request related to a problem? Please describe.**
Review is two actions, edit or accept. If a user submits an edit there is no easy option to get back to review. There needs to be a pathway for users to continue reviewing if they choose. 

**Additional context**
In #749 the option to keep in a review track when a transcription is accepted. 

**Acceptance criteria**

- [ ] When editing and clicking submit, users are able to return to review or transcribe new page within modal
- [ ] Update modal to include options to transcribe new page or review a page
<img width="592" alt="screen shot 2019-01-08 at 4 06 08 pm" src="https://user-images.githubusercontent.com/7362915/50858773-5fb48e00-135f-11e9-9dfd-432e604f21e5.png">

**Comment by acdha** [comment]
Here's the current status:

![image](https://user-images.githubusercontent.com/46565/52007468-85374200-249c-11e9-8b61-580a5932c37e.png)


This reminds me that we could still improve the layout of these buttons in the dialog if @jbresner  / @klee72 want to take a stab at it.

**Comment by acdha** [comment]
If we wanted to do the two-level flex, something like this is easy as long as we set a fixed button width for consistency:

![image](https://user-images.githubusercontent.com/46565/52008627-ff68c600-249e-11e9-8414-efe6538df5cf.png)

**Comment by rstorey** [comment]
This has been merged
