### ISSUE TITLE
Change database auth credentials to use IAM

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#757]
https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-rds-postgresql-now-supports-iam-authentication/

AWS RDS now supports IAM authentication for Postgres. We should use that instead of SecretsManager to eliminate the need for managing database passwords.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-63](https://staff.loc.gov/tasks/browse/CONCD-63)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
