### ISSUE TITLE
Update pyyaml when 4.x is released

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#777]
GitHub's vulnerability scanner has tripped an alert for having pyyaml < 4.2 installed. Unfortunately, no 4.x release has been made yet:

https://pypi.org/project/PyYAML/

(see https://github.com/yaml/pyyaml/issues/243 for the upstream issue)

Fortunately, we don't have any network-facing code which uses this — according to `pipenv graph` it's a dependency for the CloudFormation template linter and pre-commit, so we can wait until the upstream release happens.

**Comment by rstorey** [comment]
We're now on pyyaml 5.1.2
