### ISSUE TITLE
Determine behavior for when find a new page has nothing left

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#785]
**User story/persona**
As a user, I want to click a Find a new page button so that I can keep transcribing or keep reviewing.

**Is your feature request related to a problem? Please describe.**
When I click Transcribe a new page while I'm in a campaign that has no more pages to transcribe, I'm redirected to the campaign page.

When I click Review a new page while I'm in a campaign that has no more pages to review, I'm redirected to the campaign page.

**Acceptance Criteria**

- [ ] Display an appropriate message when there are no remaining pages to transcribe

- [ ] Display an appropriate message when there are no remaining pages to review

**Acceptance Test:**
1. Log in and browse to a campaign that has no remaining pages to transcribe. Accept a page in this campaign. In the resulting popup, click Transcribe a new page.
1. Log in and browse to a campaign that has one remaining page to review. Accept this final page. In the resulting popup, click Review a new page.

**Comment by acdha** [comment]
Have we decided whether this is a modal dialog which pops up on the current page, a separate page which explains the options, or more direct action cues on the campaign/project page? https://github.com/LibraryOfCongress/concordia/issues/668#issuecomment-454463130 had some discussion back in November but I don't believe an answer was agreed upon.

It seems like a site-wide available action view might be useful for other reasons beyond just the transcription page but it would require more of @jbresner's time to review.

**Comment by rstorey** [comment]
I don't think there have been any decisions made yet. I put this issue in more as a placeholder to document current behavior / functionality gaps.

**Comment by rstorey** [comment]
This has since changed to redirect to the home page when there's nothing left to retrieve when the user clicks "Find a new page." The banner message language could be clarified.

**Comment by rstorey** [comment]
This ticket is obsolete.
