### ISSUE TITLE
Content audit of BTP 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#792]
Community managers to perform a content audit - listing and analysis of all the content on an existing website (including pages, files, videos, audio or other data) that your users might reasonably encounter to inform workflow and editorial process.

Acceptance criteria: 
- [ ] Gather and review other helpful resources
- [ ] To identify content that needs to be revised in new versions of a website 
- [ ] Identify who is responsible for content and how often it should be updated
- [ ] Identify what role a particular piece of content plays for users

Resource: 
https://methods.18f.gov/decide/content-audit/
https://www.usability.gov/how-to-and-tools/methods/content-inventory.html
https://uxmag.com/articles/from-content-audit-to-design-insight

**Comment by lalgee** [comment]
Moved to program Jira board - [CONC-879](https://staff.loc.gov/tasks/secure/RapidBoard.jspa?rapidView=360&projectKey=CONC&view=planning&selectedIssue=CONC-879&issueLimit=100)
