### ISSUE TITLE
Additional print improvements 

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/concordia#800]
* Hide remove tag button
* use flat list 
* disable breadcrumb ellipsis truncation

**Comment by acdha** [comment]
@klee72 I think this is the full list from the meeting but @jbresner mentioned one other detail: https://github.com/LibraryOfCongress/concordia/blob/c2a10f9e59d2247b96a7e3c8774f9b7c2c287a00/concordia/templates/transcriptions/asset_detail.html#L240-L260 generates the X for tag removal but we should add `authenticated-only` to that so they don't display for anonymous users who won't have permission to save the change. It's cosmetic but confusing.

**Comment by elainekamlley** [comment]
Won't fix printing improvements. Not a priority at this time. 

Will create a new ticket to address the removal of a tag by an anonymous user.
