### ISSUE TITLE
Confirmation email has crowd-prod in the URL

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#803]
**What behavior did you observe? Please describe the bug**
When I register for an account the confirmation email link says crowd-prod causing the link to break. 

**How can we reproduce the bug?**

1. Register
2. Got to your email 
3. URL has `crowd-prod`
4. Page goes to unsecured prod site

**Got screenshots? This helps us identify the issue**
Add screenshots to help explain your problem.
<img width="900" alt="screen shot 2019-02-06 at 10 47 05 am" src="https://user-images.githubusercontent.com/7362915/52353687-0b074000-29fd-11e9-8ae0-ab94f4c6b987.png">

<img width="689" alt="screen shot 2019-02-06 at 10 49 33 am" src="https://user-images.githubusercontent.com/7362915/52353694-0e9ac700-29fd-11e9-892c-39cdbd163974.png">

Additional info: The link worked when removing `-prod` from the URL

**Comment by acdha** [comment]
The sites record had crowd-prod in it. We should make sure the database setup process has an exception for that hostname.

**Comment by acdha** [comment]
https://github.com/LibraryOfCongress/concordia/blob/5f6ab64a732810057bf4f4a4892593c87f5af9c4/cloudformation/master.yaml#L88-L96 should probably not allow "crowd-prod.loc.gov" since that hostname is no longer used

**Comment by rstorey** [comment]
This is fixed in the current AWS task definition. Also see #804
