### ISSUE TITLE
Prototype: Volunteer confusion with flip in viewer

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#824]
We have had a few emails from users when they flip the image in the viewer. Here are some examples

```Several times as I have been transcribing a page in more   than one document, all of a sudden the page becomes a mirror image. I know   how to invert a page or rotate it, but not convert it from a mirror image. I   just went back to the page, and now it is OK. What can I do without leaving the page?```

```I hit something that didn't just rotate the image but   inverted it so it's backwards (like reading from the back through transparent   paper). How can I undo this? I've already made the mistake twice!```

What are ways we can help our users out? Can there be a message that lets them know about `F` if the image was flipped?

**Comment by acdha** [comment]
We should probably add a flip button to the controls so people who accidentally focus the viewer and hit f can see how to flip it again without knowing about the hotkey.

**Comment by elainekamlley** [comment]
@acdha that sounds good to me!

**Comment by rstorey** [comment]
The same thing happened to me. The only way I could figure out how to un-flip it was to refresh the page.

**Comment by rstorey** [comment]
@elainekamlley  I added a button in the prototype branch so that, in the event the image accidentally becomes flipped, if the user tries each button, one of them will fix the problem. Please take a look and let me know if that's sufficient to close this ticket.

**Comment by rstorey** [comment]
This is done
