### ISSUE TITLE
Optimize / update fontawesome usage

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#833]
This is a code cleanup task.

- [ ] Switch from using 'fa' and 'fas' classes to only use 'fas' and 'fab'

- [ ] Only load the symbols we actually use or only load SVG

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-62](https://staff.loc.gov/tasks/browse/CONCD-62)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
