### ISSUE TITLE
Add tags activity to user profile

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#834]
**User story/persona**
As a user I want to see the tags I have added in my profile so I can keep track of my work.

**Additional context**
We've received this request from a teacher who wants to assign tagging to their students.

**Acceptance Criteria**
Users can see the pages they've tagged in their profiles, and the list of tags they've created for that page. They can link out to the page from their profile.

**Acceptance Test:**
I click on my profile, I see my tags as well as my pages transcribed and reviewed. 
I can easily see the number of tags I have created as well as numbers of pages transcribed and reviewed.

**Comment by lalgee** [comment]
Research needs to be undertaken to determine how to move forward with tagging.  Currently out of scope.
