### ISSUE TITLE
Refactor d-flex into row / col for most pages

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#843]
From @klee72 

d-flex vs row/col: I think for most of our pages, it’d be better to use row/col classes. Because it’s easier to follow the grid system. d-flex will be useful for complex layouts like transcription (asset detail) page which don’t necessarily need to follow the grid rules.

See #821

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-61](https://staff.loc.gov/tasks/browse/CONCD-61)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
