### ISSUE TITLE
Use meaningful / semantic markup and clean up static pages

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#844]
From @klee72:
 
Meaningful/semantic markup: I’m seeing incorrect markup and inconsistent heading level in some pages. For example, about page (https://crowd.loc.gov/about/), news/ press items should be a list `<ul> <li>` rather than `<p>`. And inconsistent heading level example: (https://crowd.loc.gov/help-center/how-to-transcribe/), this `<h3>All in order:</h3>` should be `<h2 class=“h3">All in order:</h2>` (http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/help-transcribe.html)

From @acdha:
Re: #8, most of those pages are Markdown content & can be edited in the admin area — see https://crowd.loc.gov/admin/concordia/simplepage/.

From @rstorey:
- [ ] Fix markup in simple pages

- [ ] Fix markup in non-simple pages

See #821

**Comment by lalgee** [comment]
Also need to document/implement how best to create anchors and table-of-contents for navigating long simple pages like the transcription instructions: https://crowd-stage.loc.gov/help-center/how-to-transcribe/

**Comment by klee72** [comment]
Here's a jump menu example on loc.gov: https://www.loc.gov/collections/tibetan-oral-history-project/articles-and-essays/glossary

So the table of content markup can look something like this, link is hash+id (ex: `#first`):
```
<nav class="border p-3 mb-4">
	<h2 class="h5">Table of Contents</h2>
	<ol class="m-0">
		<li><a href="#first">First</a></li>
		<li><a href="#second">Second</a></li>
		<li><a href="#third">Third</a></li>
	</ol>
</nav>
```

And just add `id` to the headers like this:
```
<h2 id="first">First</h2>
<p>....</p>

<h2 id="first">Second</h2>
<p>....</p>

<h2 id="first">Third</h2>
<p>....</p>
```

**Comment by elainekamlley** [comment]
Elaine to move these instructions to the Admin Guide
