### ISSUE TITLE
Clean up markup on gallery view

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#845]
From @klee72 

Gallery view:
https://crowd.loc.gov/campaigns/letters-to-lincoln/
https://crowd.loc.gov/campaigns/letters-to-lincoln/1830-1839-first-forays-in-politics-and-law/?
https://crowd.loc.gov/campaigns/letters-to-lincoln/1830-1839-first-forays-in-politics-and-law/mal0003400/mal0003400-1/
Main content in above pages look similar to search results list to me. `<ul>` or `<ol>` list would be more fitting for these lists in my opinion, because these are basically a list of links. And image’s alt tag should be empty because its purpose is decorative/thumbnail in this case. And naturally  heading tag `<h6>` should be removed too if unordered list is used. Here’s my example: http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/transcription.html. Anyways I didn’t have a chance to see Zuhair’s review yet, it’s just that we did a similar layout update with loc.gov search results.

From @acdha 

Re #9, I don't mind converting the card deck to a UL but I do wonder whether it might be better to review the ARIA roles now and think about how we might want to overhaul that more. I put that together in a hurry and have been wanting to come up with something which could work as a unified approach for both the asset listing (e.g. 
https://crowd.loc.gov/campaigns/letters-to-lincoln/1830-1839-first-forays-in-politics-and-law/mal0003400/) and the campaign/project/item lists (e.g.
https://crowd.loc.gov/campaigns/letters-to-lincoln). That whole part of the site hasn't really had much attention in the last few months.

See #821

**Comment by lalgee** [comment]
This issue superceded by design changes made in 2021.
