### ISSUE TITLE
Edit and accept buttons not working in review

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#858]
A user reported via email: 

"I'm trying to review documents, and all of a sudden I can't click on "Edit" or "Accept," that is, those two buttons are there but they're grayed-out/dead and I can't click on them. Is the site down or is it operator error on my part? I'm currently on the page that I included above, but I've tried opening other pages in Terrell and in Barton and encountered the same problem. I was reviewing/accepting/editing earlier today with no problems. I also just emptied my cache and reloaded everything, to no avail.  https://crowd.loc.gov/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/diaries-and-journals-1888-1951/mss425490004/mss425490004-58/"

**How can we reproduce the bug?**

1. Open a page for review. 
2. Buttons are grayed out. Not a problem in transcribe

update: if there is another reviewer on the page, and you are the second person to be on there reviewing, the buttons work. Only the person who actually has the asset reservation can’t click the buttons.

**Screenshot**

![Screenshot_2019-03-21 Crowd mss425490560-1 (Mary Church Terrell Advocate for African Americans and Women Speeches and writi](https://user-images.githubusercontent.com/6482891/54773437-f3b49880-4bdf-11e9-9989-34e1a2c152fc.png)

tested in multiple browsers by team members and problem present across all.

**Comment by rstorey** [comment]
See https://github.com/LibraryOfCongress/concordia/commit/7d3097cbddc5599fac7db9561be95fc5971ce1d1 and https://github.com/LibraryOfCongress/concordia/commit/e31668ae9201fc7d1d57b3b9377c0280a44a9d19

**Comment by rstorey** [comment]
Fixed in v0.4.24
