### ISSUE TITLE
Add carousel image for new campaign

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#874]
Acceptance criteria: 

- [x] Choose image 
- [x] Edit photo
- [x] Add as first slide?
- [x] Add link to let's go button

**Comment by VVH** [comment]
Adding myself to this ticket for step 1-choose image. I will coordinate with MSS curators

**Comment by rstorey** [comment]
I'd like to put this in behind a feature flag so there's no time pressure to deploy it. That way, you can enable the new carousel slide at the same time that you publish the campaign (whenever you want).

**Comment by elainekamlley** [comment]
@VVH We would need two images here - One for the carousel and one for the campaign. 

Carousel dimension 1200 x 480 (Horizontal) 
Campaign image: : 465 × 365 (Vertical)

**Comment by rstorey** [comment]
The campaign image (and also project images) can be uploaded through the Django admin. I'm not sure of the dimensions for the project images.

**Comment by elainekamlley** [comment]
@rstorey we are going to use the same one in loc.gov: 
![young-walt-whitman-loc](https://user-images.githubusercontent.com/7362915/56438684-c841ce00-62b1-11e9-9dbb-f8e7a2ae8da3.jpg)

Alt text: Walt Whitman in his younger years, a black and white engraving. Whitman with his right hand on his hip and his left in his pocket wearing a black rimmed hat. 

Box text: Transcribe and review poetry, letters, and writings of Walt Whitman. Discover how he wrote and lived for yourself.

**Comment by elainekamlley** [comment]
Carousel order: 
1. Whitman 
2. Review
3. Instructions
4. Jump in.

**Comment by rstorey** [comment]
This image is bigger than the other homepage carousel images.

**Comment by elainekamlley** [comment]
@rstorey its the height? This image is 560 and ours are 480, correct?

**Comment by rstorey** [comment]
Yeah it's the height. Not sure of the exact difference in dimension but it's taller than the other images.

**Comment by elainekamlley** [comment]
Try this: 

![young-walt-whitman-loc](https://user-images.githubusercontent.com/7362915/56515636-53b39d00-6506-11e9-9f25-3ac46743a39e.jpg)

**Comment by rstorey** [comment]
That's better. I have a PR ready: #899
