### ISSUE TITLE
Add ability for Community Managers to upload files in Django Admin

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#883]
**User story/persona**
As an admin, I want to be able to add document files within the Django admin interface so that I can link to them in a Concordia public page.

**Is your feature request related to a problem? Please describe.**
We need an easy process for admins to be able to upload files including documents, for example the worksheets and powerpoint files now on the Resources page. These images will need to live at a Concordia path and so they can be linked to from elsewhere in the website and downloaded or saved by users.

**Acceptance Criteria**
A Community Manager can upload a file without a technical team member's assistance for access and download by the public. 

**Acceptance Test:**
- Community manager can upload a document through the Django admin interface.
- Community manager can link to those files on a static page.
- Public user can save the file to their device.

**Comment by rstorey** [comment]
As a workaround for now, if there are things you want to publish I can put them in our public S3 bucket and you can link to them from there.

**Comment by acdha** [comment]
Why don't we setup a separate S3 bucket for this? We can add it to storages.py and then it'll be a single config on a file field once we decide what model these will be managed under.

**Comment by lalgee** [comment]
Community managers can now manage files in AWS.
