### ISSUE TITLE
Expand all option in FAQ page

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#887]
**User story/persona**
As a user I want to be able to click `Expand all` the FAQ section so that I can open all of the items and search the full text using `ctrl + F`

**Additional context**
We use bootstraps collapse component

**Acceptance Test:**
1. Go to crowd.loc.gov/help-center
2. Scroll down to the FAQ section
3. click on `Expand all` to open all the sections

**Comment by rstorey** [comment]
@elainekamlley Please see https://crowd-stage.loc.gov/help-center/

If this is acceptable, I'll publish my changes to production.

**Comment by rstorey** [comment]
This is done.
