### ISSUE TITLE
Use P1 thumbnail image in asset detail page opengraph markup

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#892]
The opengraph tag in the asset detail page which links to the image should use the P1 thumbnail instead of the full size image.

See https://github.com/LibraryOfCongress/concordia/commit/478de95

**Comment by acdha** [comment]
I should note that 478de9526ebfece687580e63ed596239588fa033 has been in #812 for awhile and the results have not been bad if you want to reuse that work.
