### ISSUE TITLE
Barton asset links to Whitman asset

### ISSUE THREAD

**Issue by VVH** [LibraryOfCongress/concordia#896]
**What behavior did you observe? Please describe the bug**

In Concordia Admin I clicked on a Clara Barton asset and it took me to a Whitman asset. Barton is published and Whitman is not yet published. Maybe resource ID is be duplicate?

**How can we reproduce the bug?**

1) From Concordia admin > Barton Campaign 
2) Click transcriptions of assets 
3) Enter search term "susan anthony 200" and get 3 results relating to mss119730027-8
4) follow asset tab for this item and get to asset page which gives https://www.loc.gov/resource/mss18630.17701/ as resource link
5) click link and find it goes to Whitman item.

**What is the expected behavior?**

Click asset resource and go to relevant asset.

**Machines/software**

Reproduced on both PC and mac, chrome browsers

**Comment by acdha** [comment]
When you're reporting errors, please include the URLs in question to save time

**Comment by acdha** [comment]
It appears that these are the assets in question:

https://crowd.loc.gov/admin/concordia/transcription/?q=susan+anthony+200&asset__item__project__campaign__id__exact=2

**Comment by rstorey** [comment]
Looks like the link to the asset from the transcription page in the admin is incorrect.

**Comment by acdha** [comment]
https://crowd.loc.gov/admin/concordia/asset/62071/change/ has the title/slug of a Barton item but the linked item is one of the Whitman collection items: https://crowd.loc.gov/admin/concordia/item/20077/change/

**Comment by acdha** [comment]
The import job for that is also a Whitman item: https://crowd.loc.gov/admin/importer/importitem/20581/change/

**Comment by rstorey** [comment]
Those transcriptions should be linking to this asset https://crowd.loc.gov/admin/concordia/asset/2960/change/?_changelist_filters=q%3Dmss119730027-8 and not asset 62071

**Comment by rstorey** [comment]
It's nothing serious - it's just using the transcription PK instead of the asset PK when forming the link to the asset. Easy fix.

**Comment by acdha** [comment]
Hah, that makes sense.
