### ISSUE TITLE
Enhancements to admin text editing functions

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#901]
**User story/persona**
- [x] As a community manager, I want the text in the simple / static page editor to soft wrap so I don't have to scroll horizontally.
- [x] As a community manager, I want to be able to provide links to content within the campaign description (and project description) and add breaks
- [x] ~~As a community manager, I want to display a system message in a banner on (some? all?) pages~~ ticketed in #1059 
- [x] As a community manager, I want to be able to edit sections of text that appear on the site such as the QuickTips in the activity interface sidebar in HTML format

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Acceptance Criteria**

**Acceptance Test:**

**Comment by rstorey** [comment]
Sprint 24

**Comment by acdha** [comment]
> As a community manager, I want to be able to easily edit text and formatting on static pages (specifically wrapping text)

As written, this is already satisfied. Was there some additional changes requested to the way the HTML wrapping occurs or the Markdown formatting rules are applied?

**Comment by acdha** [comment]
> As a community manager, I want to be able to provide links to content within the campaign description (and project description) and add breaks

Line-break support was added in #474 (ecb4612b84300c318c9ff55f17cf48dce679f717), which also discussed other formatting. This should probably be a separate ticket since it will involve [the other questions in that issue](https://github.com/LibraryOfCongress/concordia/issues/474#issuecomment-442467717) about whether this means converting the field to HTML or using Markdown, and what formatting operations are supported.

**Comment by rstorey** [comment]
> **User story/persona**
> * [ ]  As a community manager, I want to display a system message in a banner on (some? all?) pages

Attention @elainekamlley : we'll need @jbresner to draft something for how the system message would look. And probably @klee72 to work on the front end code for that.

**Comment by rstorey** [comment]
> **User story/persona**
> * [ ]  As a community manager, I want to be able to edit sections of text that appear on the site such as the QuickTips in the activity interface sidebar

@elainekamlley : what format should be used for this editing these types of content blocks?  HTML? Plain text? Markdown?
