### ISSUE TITLE
Shareable URLs in new activity UI experience

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#917]
**User story/persona**
As a user, I want to share a URL to a specific asset while I am using the new javascript UI experience so that the user who loads that URL gets that specific asset in the new javascript UI.

**Is your feature request related to a problem? Please describe.**

**Additional context**
This needs to be able to work for assets in any status (including completed assets).

**Acceptance Criteria**

**Acceptance Test:**

**Comment by acdha** [comment]
#922 adds sharing buttons to the activity UI for the basic “See this asset” type sharing in a way which should make it easy to also share an activity-based views but I'm not sure what the best way to show this in the UI will be (do you go to the old or new view, etc.) unless we decide to replace the older view entirely. cc: @jbresner

**Comment by rstorey** [comment]
This is done with #979
