### ISSUE TITLE
As an admin, I want to publish specific style guides for each Project

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#94]
As an admin, I want to publish specific style guides for each Project

- [ ] Each project may have its own specific style guide / help text / formatting instructions. As an admin, I need to create a style guide for each project.

- [ ] As an admin, I need to edit project style guides.

- [ ] As an admin, I may want to duplicate a style guide from one project to another, or use the same style guide across all projects in a collection.

**Comment by rstorey** [comment]
@acdha this is relevant to both static content and needed data model changes.

**Comment by acdha** [comment]
Yes. What's the idea for how this would be edited — part of the project / campaign release process?

**Comment by rstorey** [comment]
@VVH would know

**Comment by VVH** [comment]
Belatedly: I think we've been working this out through some of the static content tickets in sprints 10 and 11. At the moment we're having generic style guides and quick tips rather than individuating for each Campaign.

**Comment by rstorey** [comment]
If a concrete need comes up for this, we can reopen.
