### ISSUE TITLE
As an admin, I want to be able to apply tags to a Project

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#96]
- [ ] ~~As an admin, I want to be able to apply tags to a Project~~
- [ ] ~~As an admin, I want to be able to exhibit or feature certain Project-tags~~
- [x] As a curator I want to draw attention to items from several collections. I propose a campaign that would serve this need.
- [x] As a community manager, I want to pull together some projects that need a little extra love. I don’t want them to be taken out of their parent campaigns, and I want to move them out of a campaign when they’re done
- [x] As a volunteer, I want to look through some categories or topics I can transcribe, instead of just the person’s name
- [ ] As a community manager, I want to be able to apply a category when I’m importing projects
- [x] As a community manager, I want to be able to easily edit categories and group projects for temporary needs
- [x] As a community manager, I want to be able to pull an existing project into a new campaign and I need a solution for that
- [x] As a volunteer, I want to see what themes and topics are available for me to explore and see the context of them
- [x] As a volunteer, I would like to pick from a drop down menu a topic I would like to transcribe or review (campaigns and topics in same list together)
- [x] As a community manager, I want to continue to develop the topics for our volunteers beyond just “subject” into aggregating items/projects by date, activity (almost done, etc) or challenge
- [x] Add short description and published attributes
- [x] Rename to Topic
- [x] Do a sample page of listing campaigns + topics together - URL for campaigns and topics: /campaigns-topics/
- [x] ~~Add option for progress bar in Admin view - when creating topic~~ Progress bar is always included on topic detail pages
- [x] ~~Add topics to project django admin list view~~ ManyToMany fields in django admin list views aren't supported
- [x] Add ordering to Topics model similar to Campaigns
- [x] Use the same ordering field to order things in the dropdown
- [ ] ~~Grouping in the dropdown for options~~
- [x] What should the ordering for topics be? Should there be an ordering field like campaigns have? Or do it alphabetical? What about when listing alongside campaigns (in the dropdown or on a page)?
- [ ] Let's Go link for Topics that can be used in the carousel
- [ ] Use ordering field to integrate campaign and topic list

**Comment by rstorey** [comment]
cc: @colefemeno

**Comment by acdha** [comment]
It seems like we have a number of tagging-related issues open like #694. Maybe we should have a tagging roadmap?
