### ISSUE TITLE
Refactor error Django templates to use base

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#961]
The error templates (such as 404, 500, and 429 templates) don't inherit from the base template. This means front-end dependencies need to be updated in multiple places. This ticket is for someone to refactor the Django error page templates so they use the base template and front end dependencies can be declared only in the base template.

**Comment by jkueloc** [comment]
Moved to Jira: [CONCD-58](https://staff.loc.gov/tasks/browse/CONCD-58)

**Comment by jkueloc** [comment]
This issue is closed as the work has been moved to the Library's Jira repo as noted above.
