### ISSUE TITLE
Fix sidebar tab style for active/inactive states

### ISSUE THREAD

**Issue by klee72** [LibraryOfCongress/concordia#963]
**What behavior did you observe? Please describe the bug**
Currently sidebar tabs only display an active state style (white background). 

**What is the expected behavior?**
This is a newly added functionality by @acdha, and new classes have been added. Some minor css adjustment is needed.

**Got screenshots? This helps us identify the issue**
![Screen Shot 2019-05-14 at 3 54 10 PM](https://user-images.githubusercontent.com/3189000/57727865-8ada2180-7660-11e9-9a62-ded135faad67.png)

**Comment by acdha** [comment]
While we're on the subject, I was wondering yesterday whether this should be replaced with standard radio buttons using the Bootstrap classes. That should be an accessibility improvement and I'm not sure what we do which is different conceptually.

**Comment by klee72** [comment]
> While we're on the subject, I was wondering yesterday whether this should be replaced with standard radio buttons using the Bootstrap classes. That should be an accessibility improvement and I'm not sure what we do which is different conceptually.

I see this as a tabs component, so I think we can add some "tab" ARIA attributes, example: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role. However `id="asset-list-container"` is not really a `role="tabpanel"` in gridview, would this be easy to switch?

**Comment by acdha** [comment]
That might be a good question for @zuhairmahd — I don't know off-hand whether it's appropriate to toggle a value like that when we switch between modes or if there's a better way to indicate that. Since the toggle is always present in the DOM even if it's not visible when the viewer isn't open it should at least not break anything.

**Comment by zuhairmahd** [comment]
As long as the status is reported correctly, regardless of whether the component is visible or not, we should be OK.

**Comment by rstorey** [comment]
I tested this, LGTM.
