### ISSUE TITLE
Unable to accept transcriptions in activity UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#993]
**How can we reproduce the bug?**

1. Go to the activity UI.
2. Click on any asset in Review.
3. Click Accept.
4. Open the same asset in classic UI.

**What behavior did you observe? Please describe the bug**
1. In activity UI, the Edit and Accept buttons remain after I click Accept.
2. In activity UI, I get an error message that I'm unable to save my work, this transcription has already been reviewed.
3. In classic UI, I see that the transcription has not been reviewed and is still in Needs Review status.

**What is the expected behavior?**
If the asset is in "needs review" status, I should be able to accept it within the activity UI.

**Additional context**

Occurs intermittently

**Comment by rstorey** [comment]
Actually I think this might be another symptom of #986

**Comment by acdha** [comment]
I'm pretty sure it does — there are only a few assets where this reproduces and I'd bet that stale transcription IDs are the cause.

**Comment by rstorey** [comment]
I'd like to leave this open as a reminder to myself to retest after #986 is fixed

**Comment by rstorey** [comment]
Fixed
