### ISSUE TITLE
Handle 409 errors more gracefully in activity UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#995]
In the new activity UI, a suggestion:
> Handle the 409 reservation errors more gracefully than the generic error banner — probably just by suppressing them unless we want to do something like display a “Will try again in n seconds…” timer message with a “try right now” button

Stems from #992

**Comment by acdha** [comment]
I marked my comment as a suggestion because while I think we'll probably go with that at first there's possibly room to do something nicer based on feedback and what we/@jbresner come up with given more time.
